### ISSUE TITLE
Drop Swift 5.5 & 5.6 support

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1010]
### Describe the feature

Remove support for Swift 5.5 & 5.6 on `aws-sdk-swift` and `smithy-swift`, leaving Swift 5.7 as the minimum supported Swift version.  For reference, Swift 5.7 was introduced in Xcode 14.0 in September 2022.

Specific tasks:
- Set `swift-tools-version` and other minimum Swift version limits in our targets from 5.5 to 5.7.
- Remove conditional code for Swift version 5.5 & 5.6.
- Remove Swift 5.5 & 5.6 from CI tasks, replace with versions up to latest Swift where needed.
- Remove Catapult builds using Swift 5.5 & 5.6

### Use Case

- To allow for the use of more modern Swift
- To reduce the burden of supporting old Swift versions
- To reduce the complexity and build time on build & CI systems

### Proposed Solution

Specific tasks:
- Set `swift-tools-version` and other minimum Swift version limits in our targets from 5.5 to 5.7.
- Remove conditional code for Swift version 5.5 & 5.6.
- Remove Swift 5.5 & 5.6 from CI tasks, replace with versions up to latest Swift where needed.
- Remove Catapult builds using Swift 5.5 & 5.6, replace with versions up to latest Swift where needed.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
This task is blocked by amplify-swift currently supporting Swift 5.6.

This task may be unblocked once amplify-swift raises their minimum Swift version to 5.7.

**Comment by jbelkins** [comment]
Be sure to inform AWS doc writers prior to the release of this change in requirements.

**Comment by jbelkins** [comment]
Amplify dropped Swift 5.6 support in `amplify-swift` 2.18.0 so we are now free to move to Swift 5.7 as our minimum for SDK and smithy-swift.

Removing the "Blocked" label accordingly.

**Comment by jbelkins** [comment]
The CI part of this ticket will be accomplished in #1132 and #1133.

**Comment by jbelkins** [comment]
@shepazon Tagged you here for your info

**Comment by jbelkins** [comment]
Build system has been updated to run Xcode 14.0 / Swift 5.7 minimum, Xcode 15.0 / Swift 5.9 max.
Internal ref: CR-102886049

**Comment by dayaffe** [comment]
Released in 0.28
