### ISSUE TITLE
Refactor encoding of URL paths

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1011]
### Describe the feature

URL path encoding is currently performed in a manner inconsistent with other URL components and susceptible to bugs, especially when handling paths with special characters.

URL path components should be encoded as they are created or added, similar to query items, and not unencoded/re-encoded throughout the remaining lifecycle of the HTTP request.

### Use Case

To allow for cleaner, more maintainable, more bug-free code

### Proposed Solution

- Encode URL path components solely at the point of creation.
- Eliminate use of Foundation URL handling types and other types that have side-effects on path & other URL components, such as changing character escaping.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by zketosis** [comment]
Specifically having this issue with channelARN used in ListChannelMessagesInput (AWSChimeSDKMessaging).  Double url encoding makes this not work.

**Comment by jbelkins** [comment]
@zketosis This is a refactoring ticket for future work, and it's not clear from your message what your problem is.  If you have found a bug, please file a new issue on this repo, select "Bug Report", and fill in the fields with the requested info.

**Comment by jbelkins** [comment]
This is being performed along with #1043

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.20.0
