### ISSUE TITLE
Add a guide to error handling in developer docs

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1032]
### Describe the issue

A guide to error handling should be added as a link on the main SDK README.

Topics:
- Error types
- Error protocols
- Examples for handling common types of errors

### Links

N/A

**Comment by jbelkins** [comment]
Will check with doc writer about whether this is under their responsibilities

**Comment by shepazon** [comment]
I've already started working on a chapter in the AWS SDK for Swift Developer Guide to cover error handling. It will include appropriate information from the error handling design document on Quip as well as other sources, plus samples and recommended best practices.

I've run into a couple of issues while working on it and have either filed tickets (like #1058) about them or asked questions directly.

I'm sure I'll have to hit the dev team up for a good bit of added info to make this all correct and awesome, but it's underway.

**Comment by shepazon** [comment]
[Done](https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/using-errors.html)!

**Comment by jbelkins** [comment]
Closed as completed.
