### ISSUE TITLE
Endpoints 2.0 Refactoring

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1037]

**Comment by kstich** [comment]
The package `smithy-rules-engine` has undergone a major refactoring in an effort to improve validation, separate AWS and non-AWS concerns, add a specification, and better align with Smithy's coding standards. [A code-stable pull request is available here](https://github.com/smithy-lang/smithy/pull/1855). General notes are provided in individual commit messages. The format of the rules documents have _**not**_ changed, meaning a successful migration to the refactored codebase will involve _**no changes**_ to code generated for an SDK client.

The Smithy team plans to release this update on August 15th, 2023. Please reach out to us for any additional information or concerns.

**Comment by cmoher** [comment]
The coordinated release is being pushed to 09/06. This does not change or impact the required changes for the SDKs.

**Comment by kstich** [comment]
The coordinated release of this refactoring has been delayed until 09/20.

**Comment by jbelkins** [comment]
Updating Smithy used by Swift SDK to latest version, in prep for this refactor.

**Comment by jbelkins** [comment]
Moving to Blocked until the refactor ships in the Smithy project.

**Comment by jbelkins** [comment]
Endpoints refactoring shipped in Smithy 1.39.0.  Moving this issue from Blocked to Pending Release.

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.26.0
