### ISSUE TITLE
Analysis of all Credential Providers and doing gap analysis

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1040]
The purpose of this task is to identify 

-what the full universe of credential providers are
-  what all credential providers we have been implemented already - prove through testing
- what the new ones are
- review the Auth SRA and see what changes need to be done to adhere to Auth SRA
Definition of done
- Create a design doc which can be handed over to someone to start implementing the credential providers one by one
- identify issues in backlog for the ones to be implemented and create new items in backlog if they dont exist
- create issues where tests are required for existing implementations of credential providers

**Comment by dayaffe** [comment]
I have created this quip document for the team to review

https://quip-amazon.com/Jf6WA9g0bRG4/Gap-Analysis-of-all-Credential-Providers-in-Swift-SDK

**Comment by dayaffe** [comment]
This document has been reviewed by all team members.

@sichanyoo to draft a design for changes required to comply with Identity and Auth SRA
@sichanyoo to implement bearer token providers
@sichanyoo to finish SSO credentials provider
@dayaffe to implement ECS credentials provider
(tbd) to implement IMDS credentials provider
Cognito credentials provider will not be included as a GA deliverable
