### ISSUE TITLE
Build system dry run fails when there are no smithy-swift changes since last release

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1060]
### Describe the bug

When performing a dry run and there have been no changes to smithy-swift source code since the last release, the build process fails.

Relevant logs: 
```
[Container] 2023/07/05 21:33:36 Preparing to copy secondary artifacts smithySwiftReleaseManifest
[Container] 2023/07/05 21:33:36 Expanding base directory path: ${CODEBUILD_SRC_DIR}/smithy-swift
[Container] 2023/07/05 21:33:36 Assembling file list
[Container] 2023/07/05 21:33:36 Expanding /codebuild/output/src3315853193/src/smithy-swift
[Container] 2023/07/05 21:33:36 Expanding file paths for base directory /codebuild/output/src3315853193/src/smithy-swift
[Container] 2023/07/05 21:33:36 Assembling file list
[Container] 2023/07/05 21:33:36 Expanding release-manifest.json
[Container] 2023/07/05 21:33:36 Skipping invalid file path release-manifest.json
[Container] 2023/07/05 21:33:36 Phase complete: UPLOAD_ARTIFACTS State: FAILED
[Container] 2023/07/05 21:33:36 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found
```

### Expected Behavior

Dry run build succeeds

### Current Behavior

Dry run fails on step `PrepareSmithySwiftReleaseCodeBuildStepTask` with logged error message above

### Reproduction Steps

Run a successful release in the build system
Without merging any additional code to aws-sdk-swift or smithy-swift, start a dry run

### AWS SWIFT SDK version used

Latest / main

### Compiler and Version used

Xcode 14.3.1

### Operating System and version

macOS 13.4

**Comment by sichanyoo** [comment]
Enable E2E test for catapult after this is addressed.

**Comment by sichanyoo** [comment]
Released with https://github.com/awslabs/aws-sdk-swift/releases/tag/0.42.0.
