### ISSUE TITLE
Sending Email with SES Only Works with Xcode

### ISSUE THREAD

**Issue by minimalistcode** [awslabs/aws-sdk-swift#1063]
### Describe the bug

I have some simple code to send an email using SES. Sending the email works fine with Xcode using a simulator (iPhone, iPad, Mac), and sending the email also works fine with Xcode using a physical device (iPhone, iPad).

However, when I try to send the email using only a physical device, without Xcode, it fails. It seems like sending email with SES only works when running in Xcode.

### Expected Behavior

I expect the email to be sent using SES.

### Current Behavior

If the app is run on a device, and not with Xcode, sending the email fails. I get this error.

The operation couldn't be completed. 
(AwsCommonRuntimeKit.CommonRunTimeError error:0.)

### Reproduction Steps

I created a simple SwiftUI test app and the complete code is below.  You just need to put in valid SES from and to email addresses.

```
struct ContentView: View {
    @State var isButtonDisabled = false
    @State var showAlert = false
    @State var alertMessage = ""
	
    var body: some View {
        VStack {
           Button("Send Mail") {
               isButtonDisabled = true
               Task {
                    do {
                         try await sendEmail(fromEmailAddress: fromEMailAddress, toEmailAddress: toEmailAddress, subject: "SendMail Test Mail", message: "This is a test email from the SendMail app")
                        }
                        catch (let error) {
                             print("Error: \(error.localizedDescription)")
                             alertMessage = error.localizedDescription
                             showAlert = true
                        }
                        isButtonDisabled = false
                    }
                }
            .disabled(isButtonDisabled)
        }
        .padding()
        .alert(isPresented: $showAlert) {
               Alert(title: Text("SendMail Error"), message: Text(alertMessage), dismissButton: .default(Text("OK")))
        }
    }

     func sendEmail(fromEmailAddress:String, toEmailAddress:String, subject:String? = nil, message:String? = nil) async throws {
          let sesClient = try SESClient(region: "us-east-1")
          var sendEmailInput = SendEmailInput()
          sendEmailInput.source = fromEmailAddress
          sendEmailInput.destination = SESClientTypes.Destination(toAddresses: [toEmailAddress])
          var body = SESClientTypes.Body()
          let bodyContent = SESClientTypes.Content(charset: "UTF-8", data: message ?? "")
          body.text = bodyContent
          let subject = SESClientTypes.Content(charset: "UTF-8", data: subject ?? "")
          sendEmailInput.message = SESClientTypes.Message(body: body, subject: subject)
          let _ = try await sesClient.sendEmail(input: sendEmailInput)
    }
}
```

### AWS SWIFT SDK version used

0.20.0

### Compiler and Version used

Xcode 14.3.1, Swift 5.8.1

### Operating System and version

iOS 16.5.1, macOS 13.4.1

**Comment by jbelkins** [comment]
@minimalistcode How are you providing credentials to the SDK when you are running on device?

Certain means of providing credentials (i.e. from your `~/.aws/credentials` file) that work when running in Xcode don't work when running on device.

**Comment by minimalistcode** [comment]
Thanks, that must the problem. The credentials are in ~/.aws/credentials and also in the the Xcode scheme environment variables. I was trying an old app that doesn't use Amplify.  It used to use credentials with Cognito and a single identity pool so I guess I can figure out how to do that with this new SDK.

**Comment by minimalistcode** [comment]
That was the issue. Thanks. I will close this since it's not a bug.
