### ISSUE TITLE
Expose timeout setting configuration from CRT

### ISSUE THREAD

**Issue by harsh62** [awslabs/aws-sdk-swift#1065]
### Describe the feature

A way to configure the equivalent of [URLSessionConfiguration.timeIntervalForRequest](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1408259-timeoutintervalforrequest) and [URLSessionConfiguration.timeoutIntervalForResource](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1408153-timeoutintervalforresource), either on a request or client configuration level?

### Use Case

This was possible in AWS SDK for iOS whereas the AWS SDK for Swift doesn't support this configuration. Hence it creates a parity issue between Amplify versions. 

Reference Issue: https://github.com/aws-amplify/amplify-swift/issues/3004

### Proposed Solution

Expose a configuration which would allow passing in custom timeout to CRT. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by grutts** [comment]
Hi @harsh62 do you have an update on when this bug will be fixed? It remains a blocker to upgrading from Amplify 1.X which is currently in maintenance / end of life status.

**Comment by smivij** [comment]
Adding needs-triage label again to revisit priority

**Comment by dayaffe** [comment]
Equivalent should be the ability to configure socketOptions as mentioned [here](https://github.com/smithy-lang/smithy-swift/blob/main/Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift#L81). This value should be made configurable in the exposed wrapper [here](https://github.com/smithy-lang/smithy-swift/blob/main/Sources/ClientRuntime/Networking/Http/SdkHttpClient.swift#L9).

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.26.0
