### ISSUE TITLE
STSAssumeRoleCredentialsProvider initialization fails

### ISSUE THREAD

**Issue by tachyonics** [awslabs/aws-sdk-swift#1067]
### Describe the bug

When using the `STSAssumeRoleCredentialsProvider` initialization fails with a thrown crtError error.

### Expected Behavior

Role should be successfully assumed.

### Current Behavior

```
crtError(AwsCommonRuntimeKit.CRTError(code: 34, message: "An invalid argument was passed to a function.", name: "AWS_ERROR_INVALID_ARGUMENT"))
```

### Reproduction Steps

```
let credentialsProvider = try DefaultChainCredentialsProvider()
let logger = Logger(label: "credentials.initialization")
        
logger.info("assumedCredentialsProvider creation start.") <-- is logged
            
let assumedCredentialsProvider = try STSAssumeRoleCredentialsProvider(
  credentialsProvider: credentialsProvider,
  roleArn: someValidRoleArn,
  sessionName: "ASSUMED_\(UUID().uuidString)",
  durationSeconds: 3600) <-- throws error
            
logger.info("assumedCredentialsProvider creation finish.") <-- not logged
```

### AWS SWIFT SDK version used

0.12.0

### Compiler and Version used

5.8.1

### Operating System and version

amazonlinux:2.0.20230628.0

**Comment by jbelkins** [comment]
Related issue on aws-crt-swift: https://github.com/awslabs/aws-crt-swift/issues/133

**Comment by smivij** [comment]
Closing as https://github.com/awslabs/aws-crt-swift/issues/133 is closed.
