### ISSUE TITLE
Make waiter initializers public for mocking

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#1068]
### Describe the feature

Mocking in Swift requires an abstraction layer and then an object that implements SDK functions' signatures but uses and returns mock data. This mostly works fine, but I've discovered it doesn't work with waiters, because, for example, I need to be able to create an error in my mocked implementation of `waitUntilBucketExists()`. But the following gets me a compiler error telling me that "'WaiterOutcome<Output>' initializer is inaccessible due to 'internal' protection level".

```
    public func waitUntilBucketExists(options: WaiterOptions,
                input: HeadBucketInput) async throws
                -> WaiterOutcome<HeadBucketOutputResponse> {
        let response = ClientRuntime.HttpResponse(
            statusCode: .ok
        )
        let output = try await HeadBucketOutputResponse(
            httpResponse: response
        )
        return WaiterOutcome<HeadBucketOutputResponse>(
            attempts: 1,
            result: .success(output)
        )
    }
```

### Use Case

Mocking requires being able to create and return these types.

### Proposed Solution

Make these types public.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.23.0
