### ISSUE TITLE
Request Compression

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1072]
### Describe the feature

Request compression allows the body of large requests to be optionally compressed for faster transmission.

Request compression is defined in the Smithy spec, and shipped in Smithy 1.31.0:
https://smithy.io/2.0/spec/behavior-traits.html#smithy-api-requestcompression-trait

Request compression is also described by SEP:
`--/seps/in-progress/shared/compression-trait.md`

Turn on request compression protocol tests back on along with implementation.

### Use Case

For performant use of operations with large request bodies.

### Proposed Solution

Implement as described.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2149
