### ISSUE TITLE
Operations do not model errors defined on the parent service

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1080]
### Describe the bug

Services may define error shapes that may be returned by any operation defined by the service.
https://smithy.io/2.0/spec/service-types.html#service

However, our generated error deserialization code does not attempt to deserialize errors defined on the service, only errors defined on the operation.

### Example: CodeCatalyst service.

CodeCatalyst defines several errors at the service level:
https://github.com/awslabs/aws-sdk-swift/blob/main/codegen/sdk-codegen/aws-models/codecatalyst.2022-09-28.json#L129

### Expected Behavior

When an error modeled by the service is thrown by one of the service's operations, the error should be deserialized as the modeled type.

### Current Behavior

When an error modeled by the service is thrown by one of the service's operations, the error is deserialized as an `UnknownAWSHTTPServiceError` type.

### Reproduction Steps

For an example, run the following code which is intended to throw an error:

```
import AWSCodeCatalyst
import struct Foundation.UUID

        let client = try CodeCatalystClient(region: "us-east-1")
        let input = GetUserDetailsInput(id: UUID().uuidString, userName: "nonexistent user")
        do {
            let output = try await client.getUserDetails(input: input)
            print("Request succeeded")
            print("Output: \(output.primaryEmail)")
        } catch {
            print("Request failed")
            print("Error: \(error)")
        }
```

The following `UnknownAWSHTTPServiceError` error is thrown:
```
UnknownAWSHTTPServiceError(typeName: Optional("ValidationException"), message: Optional("There were errors validating the input"), requestID: nil, requestID2: nil, httpResponse: /* omitted */ )
```
even though `ValidationException` is an exception type that is modeled on the service, and should have been modeled and thrown.

### Possible Solution

Include errors modeled on the service as candidates when parsing an error response from an operation.

### AWS SWIFT SDK version used

Latest / main

### Compiler and Version used

Xcode 14.3.1

### Operating System and version

macOS 13.5

**Comment by sichanyoo** [comment]
Tracked in this PR: https://github.com/smithy-lang/smithy-swift/pull/581
