### ISSUE TITLE
Add support for Bearer Tokens

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1083]
### Describe the feature

Bearer token authorization and token providers are detailed in `seps/accepted/shared/token-providers.md`

### Use Case

CODE.AWS is a new SaaS experience that brings together the tools that development teams need to plan work, collaborate on source changes, store and manage artifacts, and automate their CI/CD workflows. This service aims to offer a high level experience over the code suite of services that do not require an AWS account to make use of. Because of this customers of the Code.aws APIs will not have traditional AWS credentials and instead will rely bearer tokens for authentication.

### Proposed Solution

- Investigate changes that need to be made on the CRT side
- Expose Bearer Token Providers in Swift SDK (See Java Implementations for reference as listed in [this doc](https://quip-amazon.com/Jf6WA9g0bRG4/Gap-Analysis-of-all-Credential-Providers-in-Swift-SDK#temp:C:TKV703fe4441e234b2daf7bcbbeb))

### Other Information

#236 will accomplish a portion of the mentioned SEP which involves being able to read Bearer Tokens from a file. However, it will not accomplish exposing a wrapper for that token provider which is implemented in the CRT and used behind the scenes. It will also not accomplish workflows for refreshing them.

Regarding the initial SSO token creation, it should be left to AWS CLI for now. Allowing users to create SSO token via SDK will be post-GA feature that will be prioritized based on user requests.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
As per internal discussion, not tracking this for GA. We will look at adding support for Code Catalyst as  post-GA work (bearer tokens are required to support Code Catalyst)
