### ISSUE TITLE
[Analysis] Specialize HTTP client for Apple platform to fix the connection issue while running in the background

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1086]
### Describe the feature

Enable the CRT HTTP client to continue handling events in the background on Apple platform clients.

The standard event handling mechanism used by the CRT HTTP client (kqueue) is not fully supported on Apple platforms (i.e. native iOS/iPadOS, tvOS, macOS applications).  Using the CRT HTTP client as-is on Apple platforms will result in broken connections if the application is not in the active state for the entire duration of the connection; this is a severe limitation for most use cases, especially for mobile devices where connection speeds are limited and users are restricted to one foreground app at a time.

To remedy this limitation, an alternative event handling mechanism ("dispatch queues") must be used on Apple platforms, since dispatch queues continue to handle events as expected throughout the application lifecycle.  The CRT HTTP client will be modified to use the correct event handling mechanism when building for the platforms that require it.

### Use Case

To enable efficient, background HTTP communications via the AWS SDK for Swift.

### Proposed Solution

Use Apple platform-native event handling on Apple platforms, instead of CRT's current event handling which is based on POSIX threads.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by waahm7** [comment]
I have completed an analysis of the PR and discussed it with Jonathan Henso. The PR requires cleanup and a few quirks that need to be sorted out. We can pick up the implementation task in Q1 2024. It won't require anything on the Swift SDK side.
