### ISSUE TITLE
IMDS identity resolver & integration test

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1094]
### Describe the feature

IMDSv2 Credentials Provider is currently implemented in CRT (see [aws-crt-swift](https://github.com/awslabs/aws-crt-swift/blob/main/Source/AwsCommonRuntimeKit/auth/credentials/CredentialsProvider.swift#L225)) and part of the default chain credentials provider. However, it is not currently exposed to users. Swift SDK should implement a wrapper that exposes this credentials provider.

### Use Case

Users may want to force the user of IMDS Credentials Provider without having to go through the default chain. Exposing via wrapper may also allow for additional configuration.

### Proposed Solution

Implement a wrapper that exposes this credentials provider.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
Updated priority based on feature matrix

**Comment by dayaffe** [comment]
Effort includes writing an integration test

**Comment by sichanyoo** [comment]
Went out with the release: https://github.com/awslabs/aws-sdk-swift/releases/tag/0.38.0
