### ISSUE TITLE
fix: Add integration tests for SSO credential provider

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1097]
### Describe the issue

SSO credentials provider wrapper in Swift SDK is currently tested manually. Integration tests that automatically test it using AWS CLI should be added.

### Links

SSO credentials provider source: https://github.com/awslabs/aws-sdk-swift/blob/main/Sources/Core/AWSClientRuntime/Auth/CredentialsProviders/SSOCredentialsProvider.swift

**Comment by sichanyoo** [comment]
PR: https://github.com/awslabs/aws-sdk-swift/pull/1129

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.26.0
