### ISSUE TITLE
Add programmatic SSO token creation flow in SDK

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1098]
### Describe the feature

This feature will add SSO token creation flow in the SDK to allow end-user of an application built with SDK to perform SSO log-in to create a SSO token to use.

### Use Case

In some applications, developers may want to use Swift SDK to allow end-users to perform SSO log-in to create SSO token.

### Proposed Solution

Add token creation API to SSO token provider in the SDK ([token provider / bearer auth support is yet to be implemented](https://github.com/awslabs/aws-sdk-swift/issues/1083)).

### Other Information

This feature will be post-GA and will be prioritized based on user requests for the feature. After discussion with other SDK teams, this feature is non-GA at the moment.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Being tracked in #646
