### ISSUE TITLE
JSON Value Trait for Arbitrary Structured Data

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1104]
### Describe the feature

SEP: `/accepted/shared/json-value-trait.md`

### Use Case

Required for GA

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
We will update this issue with relevant details after SEP reading session on Friday.

**Comment by smivij** [comment]
As per Cross SDK feature matrix and a note from Rust SDK team, this is only for C2J models not for SDKs built on Smithy, to be closed after SEP reading.

**Comment by sichanyoo** [comment]
quipt: /2ZtwA9mqnvtd/101323-Sep-Reading-Meeting-Notes
