### ISSUE TITLE
Smithy Execution Interceptors

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1105]
### Describe the feature

Quip: `g3DoAzTyXlo6`
SRA doc: `design_and_implementation_of_aws_sdks.pdf`

### Use Case

Required for GA

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Being tracked in #307
