### ISSUE TITLE
Retry Information Header

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1108]
### Describe the feature

SEP: `accepted/shared/retry-header.md`

### Use Case

Required for GA

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
We will fill out details after reviewing the SEP.

**Comment by sichanyoo** [comment]
/2ZtwA9mqnvtd/101323-Sep-Reading-Meeting-Notes

**Comment by sichanyoo** [comment]
Released with https://github.com/awslabs/aws-sdk-swift/releases/tag/0.42.0.
