### ISSUE TITLE
Configurable TLS Trust / Key Store

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1110]
### Describe the feature

Quip: `nY63AaBMJcoU/Cross-SDK-Feature-Matrix-Items-Deprecated-or-Without-SEPs#temp:C:UcSd201249e88184a9aa77e6d825`

### Use Case

Required for GA

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Feature: SDKs MUST allow the customer to configure the trust and key stores used during HTTPS handshakes.

**Comment by dayaffe** [comment]
Released in 0.43
