### ISSUE TITLE
S3 Object Lambda support

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1112]
### Describe the feature

SEP: `seps/accepted/shared/s3-banner.md`

### Use Case

Required for GA

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Will update issue after reviewing related SEP.

**Comment by jbelkins** [comment]
Determined that this customization is not needed once Endpoints 2.0 is supported by a SDK. Closing.
