### ISSUE TITLE
S3 throws errors after HTTP/200

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1113]
### Describe the feature

Internal tracking: `SDK-153398`

### Use Case

Required for GA

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Discussion related to issue: https://amzn-aws.slack.com/archives/G017UPVDRAS/p1693326099352059

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.34.0
