### ISSUE TITLE
Distribute AWS SDK for Swift internally

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1158]
### Describe the feature

Set up the AWS SDK for Swift for distribution via AWS internal distribution channels.

### Use Case

For secure, compliant internal distribution of AWS SDK for Swift.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Be sure to add the user-agent metadata for internal distribution.
See SEP `accepted/shared/sdk-user-agent-header.md`

**Comment by sichanyoo** [comment]
GA milestone removed after investigation. Left as optional upon internal customer demand.

**Comment by sichanyoo** [comment]
Wrote a one pager for future reference (/PBNRATqP5rU1); removing the ticket from sprint board.

**Comment by sichanyoo** [comment]
Moved to 2148
