### ISSUE TITLE
Improve error messaging for modeled errors that provide their own message

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1166]
### Describe the feature

Many AWS service errors have a modeled `message` property, that the service can use to provide detailed information about the error.  Because modeled error properties are namespaced under `properties`, this error message is accessible as `error.properties.message` on an error named `error`.

However, many modeled error types don't provide a message; presumably the type of the error is sufficient to inform the caller of the nature of the error in this case.

Every service error also has a `message` property that they inherit through the `ServiceError` protocol.  This `message` property is intended to provide a human-readable error message, even for errors that don't explicitly provide one as a modeled field.  This property is exposed on an error named `error` as `error.message`.

So, for service errors that provide their own modeled `message` property, they actually have two message properties: `error.message` and `error.properties.message`.  It's not clear to the customer why there are two properties, nor what one might contain versus the other.  It should be presumed, though, that when the service provides a modeled error message, that it should contain the most useful and relevant message.

### Use Case

It should be clear to customers how to get the most useful error message for any error that is returned by an AWS service.

### Proposed Solution

A `message` accessor should be provided that selects the best option between a modeled error message and a `ServiceError` protocol-provided message, and returns the most appropriate of the two.

This will likely have to be done using code-generation, based on whether the error models its own `message` or not.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2157
