### ISSUE TITLE
feat: Add support for event stream input to protocols that use RPC

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1175]
[ 3/1/24 - Additional context edit by @sichanyoo ]

Currently the SDK does not support event stream input for RPC-based protocols.
This is in part because currently there is no AWS service that uses event stream input over a RPC-based protocol.
But this may change in future and services may want to add an operation that accepts event stream input over RPC-based protocol.
Therefore, the codegen for SDK must correctly generate code that handles event stream inputs, given it finds a union shape with streaming trait in the Smithy model of a service.

The AWS protocols that use RPC API architecture instead of REST API architecture are:
`awsJson1_0`, `awsJson1_1`, `awsQuery`, & `ec2Query`.

**Comment by sichanyoo** [comment]
Quip doc with details: /e7tTALANYJ03/Event-Streams-Knowledge-Document

**Comment by sichanyoo** [comment]
Effort is for investigation - 0.8. There's no known service that currently has event streams over RPC in request. Investigation needed.

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.40.0
