### ISSUE TITLE
Minimize EC2 resources in alpha / beta stages of build system

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1176]
### Describe the feature

The alpha and beta stages of the SDK's automated build system, which are currently unused, have the same resources allocated as the production stage.

This includes costly Mac EC2 dedicated hosts, which are billed 24/7 whether they are in use or not.

### Use Case

To reduce the cost of build system without sacrificing functionality.

### Proposed Solution

Modify the build system to reduce the size of auto scaling groups to one on the alpha / beta stages.  Maintain current size in production and development, which are actually used.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Changes will need to be reverted back as part of trebuchet onboarding - but in the meantime, we can save some money.
