### ISSUE TITLE
Support STSWebIdentity credential provider

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1189]
### Describe the feature

aws-crt-swift 0.14.0 added needed parameters for the STSWebIdentity credential provider.  https://github.com/awslabs/aws-crt-swift/pull/199/files

Create a SDK wrapper for this credential provider and integration tests.

### Use Case

To support all standard AWS credential providers

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
Add Integration test

**Comment by sichanyoo** [comment]
Released with: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
