### ISSUE TITLE
Add a Privacy Manifest to the SDK

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1191]
### Describe the feature

Apple has introduced the "privacy manifest" which is a machine-readable file that describes the type of data collected by a Swift package or app:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

To aid Apple platform developers in complying with their data collection disclosure obligations to Apple, the Swift SDK should supply its own privacy manifest that discloses the data collected by the SDK.

### Use Case

To comply with Apple requirements for disclosing data collection to consumers.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
@rowanlsnapper 

[This PR](https://github.com/awslabs/aws-crt-swift/pull/254) added privacy manifest to aws-crt-swift.
The 2 PRs linked in this issue's history adds privacy manifest to smithy-swift & aws-sdk-swift, which depend on aws-crt-swift.

Unless something unexpected happens, all of this will go out in a new release next Tuesday (4/23/24) with a v0.42.0 release of aws-sdk-swift.

However, note that [amplify-swift must bump their dependency on our aws-sdk-swift from 0.36.1](https://github.com/aws-amplify/amplify-swift/blob/main/Package.swift#L12) to 0.42.0 before this bubbles up to your application.

**Comment by sichanyoo** [comment]
@rowanlsnapper

Hello, just wanted to give a heads up that this change has just been released with the v0.42.0 of the AWS Swift SDK : https://github.com/awslabs/aws-sdk-swift/releases/tag/0.42.0.

As mentioned before, please note that [amplify-swift must bump their dependency on our aws-sdk-swift from 0.36.1](https://github.com/aws-amplify/amplify-swift/blob/main/Package.swift#L12) to 0.42.0 before this bubbles up to your application.
