### ISSUE TITLE
fix: Rename defaultContentType to differentiate between request & response

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1196]
### Describe the feature

Right now we hardcode `defaultContentType` to always be `"application/x-www-form-urlencoded"`. While this is correct for requests, it is incorrect for responses which should have a `defaultContentType = "text/xml"`. This issue is mentioned in the following comment:

[// TODO: Rename defaultContentType to differentiate between request & response](https://github.com/awslabs/aws-sdk-swift/blob/a0ce157d94c295742ff6592c5c81f19408eda9e6/codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/awsquery/AwsQueryProtocolGenerator.kt#L33)

Include looking at the [Smithy 2.0 docs](https://smithy.io/2.0/aws/protocols/aws-query-protocol.html) to ensure that our implementation of `awsquery` follows the protocol specification properly.

### Use Case

We should correctly set the content type of responses to `text/xml`

### Proposed Solution

Refactor this code to correctly differentiate between request/response and set the content type accordingly.

### Other Information

Related Issue: #710 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
After investigation, reached conclusion that the mentioned TODO item isn't referring to renaming the _value_ of the variable but rather the _name_ of the variable itself. The value of the variable _is_ supposed to be fixed at `"application/x-www-form-urlencoded"` and no change is needed. TODO item is likely referring to renaming `defaultContentType` variable to something like `defaultRequestContentType` to erase possible confusion arising from different default content types of response and request of AWS query protocol (response content type is `text/xml`).

Confirmed that the SDK works correctly currently, using `STS::GetCallerIdentity` which uses AWS query protocol. The returned content type is `text/xml` as expected and response is correctly deserialized.

System works correctly already, and the original thought process behind adding this TODO doesn't really make sense given the SDK obviously only sets content type of requests. Will proceed with just deleting TODO item and submitting PR.

**Comment by sichanyoo** [comment]
https://github.com/awslabs/aws-sdk-swift/pull/1288

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.34.0
