### ISSUE TITLE
feat: Ensure models and SDK properly support disabled auth (AuthTrait set to empty list) 

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1197]
### Describe the feature

Disabled Auth is when a smithy model sets the AuthTrait to an empty list. For more info see: https://smithy.io/2.0/spec/authentication-traits.html?highlight=disabled#auth-trait

Currently, we manually set AuthTrait to empty list for a select set of services and operations likely because we did not support disabling auth properly. This work is related to the following code comment:

[// TODO: If or when the service team adds this trait to their model, we can remove this customization (DisabledAuth)](https://github.com/awslabs/aws-sdk-swift/blob/a0ce157d94c295742ff6592c5c81f19408eda9e6/codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/DisabledAuth.kt#L58)

### Use Case

A service/operation with auth disabled allows only un-authenticated requests.

### Proposed Solution

Disabled authentication is a planned feature of SRA Identity & Auth work that is currently on-going. When it is complete, we should ensure that all operations mentioned in the aforementioned file possess the disabled auth trait in their model definition and work as intended with the new SRA-compliant code. If so, we can remove the mentioned file.

Services and their operations which are currently hardcoded to use disabled authentication:

- com.amazonaws.sts#AWSSecurityTokenServiceV20110615
     -  [com.amazonaws.sts#AssumeRoleWithSAML](https://github.com/awslabs/aws-sdk-swift/blob/5366bfc01bb25457f655ff480b72879dcb55fe11/codegen/sdk-codegen/aws-models/sts.2011-06-15.json#L2461) **Missing Disabled Auth in Model**
     -  [com.amazonaws.sts#AssumeRoleWithWebIdentity](https://github.com/awslabs/aws-sdk-swift/blob/5366bfc01bb25457f655ff480b72879dcb55fe11/codegen/sdk-codegen/aws-models/sts.2011-06-15.json#L2636) **Missing Disabled Auth in Model**

- com.amazonaws.cognitoidentity#AWSCognitoIdentityService
    - [com.amazonaws.cognitoidentity#GetId](https://github.com/awslabs/aws-sdk-swift/blob/5366bfc01bb25457f655ff480b72879dcb55fe11/codegen/sdk-codegen/aws-models/cognito-identity.2014-06-30.json#L1669) **Has Disabled Auth in Model**
    - [com.amazonaws.cognitoidentity#GetOpenIdToken](https://github.com/awslabs/aws-sdk-swift/blob/5366bfc01bb25457f655ff480b72879dcb55fe11/codegen/sdk-codegen/aws-models/cognito-identity.2014-06-30.json#L1824) **Has Disabled Auth in Model**
    - [com.amazonaws.cognitoidentity#UnlinkIdentity](https://github.com/awslabs/aws-sdk-swift/blob/5366bfc01bb25457f655ff480b72879dcb55fe11/codegen/sdk-codegen/aws-models/cognito-identity.2014-06-30.json#L3456) **Has Disabled Auth in Model**
    - [com.amazonaws.cognitoidentity#GetCredentialsForIdentity](https://github.com/awslabs/aws-sdk-swift/blob/5366bfc01bb25457f655ff480b72879dcb55fe11/codegen/sdk-codegen/aws-models/cognito-identity.2014-06-30.json#L1580) **Has Disabled Auth in Model**

- com.amazonaws.cognitoidentityprovider#AWSCognitoIdentityProviderService
    - **service and associated operations can no longer be found in aws-sdk-swift**

### Other Information

Depends On: #1119
Related Issue: #710 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Related Issue in aws-sdk-kotlin: https://github.com/awslabs/aws-sdk-kotlin/blob/d5087ba80ece7353f34cdd0066396603452fc3d2/codegen/smithy-aws-kotlin-codegen/src/main/kotlin/aws/sdk/kotlin/codegen/customization/BackfillOptionalAuth.kt#L38

**Comment by sichanyoo** [comment]
Concluded that this task is unrelated to SRA I&A rework. This customization is a matter of coordinating with service teams to have them add auth trait to their smithy model (until that happens, we do need this customization). Preprocessing smithy model is unrelated to SRA I&A.

**Comment by sichanyoo** [comment]
Moved to 2141
