### ISSUE TITLE
feat: Add ability to configure IMDS Client with features supported by CRT

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1199]
### Describe the feature

Currently our IMDS client only allows the user to config the `numRetries` as opposed to the entire `retryStrategy` and does not allow the user to specify the `protocolVersion`. CRT also supports falling back to V1 if V2 does not work, but currently `protocolVersion` is hardcoded to V2.

This relates to the following comment:
[// TODO: support more config options that are required to be supported when the CRT adds the ability to pass them down.](https://github.com/awslabs/aws-sdk-swift/blob/a0ce157d94c295742ff6592c5c81f19408eda9e6/Sources/Core/AWSClientRuntime/IMDS/IMDSConfig.swift#L10)

### Use Case

We should allow the user to configure the IMDS Client with all available features supported by CRT.

### Proposed Solution

- Create logic for using CRT's fallback support for V2 to V1
- Allow the user to configure the `protocolVersion` in `IMDSConfig`
- Allow the user to configure the entire `retryStrategy` rather than just `numRetries`

### Other Information

Related Issue: #710 
Related CRT Code: [IMDSClient.swift](https://github.com/awslabs/aws-crt-swift/blob/326f95c24679984b81177d5d66ec1203489ded71/Source/AwsCommonRuntimeKit/auth/imds/IMDSClient.swift#L7)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2142
