### ISSUE TITLE
feat: Log caught token error in RetryMiddleware

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1207]
### Describe the feature

During the `sendRequest` function we catch and throw the `operationError`. However, there is a situation where we attempt to refresh the token for retry that could result in an error. Currently, we only catch this error and continue to throw the operation error. We should at least log additional errors with refreshing the token. 

Related comment:
[// TODO: log token error here](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/Sources/ClientRuntime/Middleware/RetryMiddleware.swift#L42)

### Use Case

Better user experience when debugging.

### Proposed Solution

Log the relevant caught error.

### Other Information

Related Issue: #710 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.44.0
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.44.0
