### ISSUE TITLE
fix: Properly unwrap optional data values

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1208]
### Describe the feature

In ShapeValueGenerator.kt we currently write `".data(using: .utf8)!, isClosed: true))"` and `".data(using: .utf8)!"`. We should properly unwrap .data optional values rather than force them to be non-null using `!`.

Related comment:
[// TODO: properly handle this optional with an unwrapped statement before it's passed as a value to a shape.](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ShapeValueGenerator.kt#L204)

### Use Case

Forced un-wrapping with `!` should be avoided. Un-wrapping using other methods allows us to gracefully/explicitly handle unexpected null values.

### Other Information

Related issue: #710

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
This ticket will involve changes that need to be made to all places where force-unwrap is currently done, as well as possibly creating a new error type that should be used for this case.

**Comment by jbelkins** [comment]
Closing since it is part of ongoing code review
