### ISSUE TITLE
Write runbook page for manually performing a "patch" release

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1212]
### Describe the issue

There needs to be a written procedure for generating a "patch" release from an existing SDK release, to allow for the release of emergent fixes that consumers (i.e Amplify) cannot wait to adopt until they update their SDK version to latest.

Write such a procedure and add it to the team's runbook.

### Links

N/A

**Comment by sichanyoo** [comment]
Please add the Quip doc under the `SDKs and Tools Team/SDKs/Swift/Oncall` once completed.
