### ISSUE TITLE
fix: Address edge case in Shape.isInHttpBody() function

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1213]
### Describe the bug

The following comment was left in the code:
[// TODO fix the edge case: a shape which is an operational input (i.e. has members bound to HTTP semantics) could be re-used elsewhere not as an operation input which means everything is in the body](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt#L78)

Related issue: #710 

### Expected Behavior

`fun Shape.isInHttpBody()` checks to see if a shape is in the body of the http request. This should work for any valid shape with bound members.

### Current Behavior

The TODO comment suggests that the code logic does not work properly when an input to operation is re-used elsewhere not as an input to an operation.

### Reproduction Steps

This issue includes the work to re-produce this edge case which can likely be accomplished by creating a smithy file and corresponding test.

### AWS SWIFT SDK version used

to be confirmed

### Compiler and Version used

to be confirmed

### Operating System and version

to be confirmed

**Comment by sichanyoo** [comment]
Moved to 2143
