### ISSUE TITLE
feat: add test coverage to restxml

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1214]
### Describe the feature

In tests for restxml/xml-enums.smithy we currently tests structures, lists, nested lists, and enum lists, but do not tests sets and maps. The following comment was left in code found [here](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/test/resources/Isolated/Restxml/xml-enums.smithy#L84):

```
//  Todo: sets, maps
//  1.  This will be part of: XmlEnumsInputOutput
//    fooEnumSet: FooEnumSet,
//    fooEnumMap: FooEnumMap,
//
//  2.  Then add this:
//    set FooEnumSet {
//        member: FooEnum,
//    }
//
//    map FooEnumMap {
//        key: String,
//        value: FooEnum,
//    }
//
```

### Use Case

We should support sets and maps in smithy files sent over restxml protocol and therefore should also provide adequate test coverage of these scenarios.

### Proposed Solution

Add test coverage and address any gaps in our implementation.

### Other Information

Related issue: #710 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Is it possible that Smithy has added these as protocol tests in the restxml suite since the TODO was written?
(Such a test is not Swift-specific and I would expect it to be in the cross-platform protocol test suite if it is needed to ensure an implementation understands the protocol)

**Comment by sichanyoo** [comment]
This ticket will be part of clean-up: https://github.com/awslabs/aws-sdk-swift/issues/1217. 
Look into whether the files in same directory are covered by protocl tests in Smithy project already: https://github.com/smithy-lang/smithy/tree/main/smithy-aws-protocol-tests/model/restXml

**Comment by sichanyoo** [comment]
Moved to 2144
