### ISSUE TITLE
chore: clean up unnecessary TODOs in smithy-swift

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1217]
### Describe the feature

The following TODOs can be removed as they are no longer necessary:

https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/design/DESIGN.md
- let's take a look at this one as a group

[// TODO: this file will change post AWS Service config design most likely.
](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/Sources/ClientRuntime/Networking/Http/HttpClientConfiguration.swift#L10)
- This file does not seem to have needed any changes as it has not been touched in 2 years

[/// TODO: simplify logger creation](https://quip-amazon.com/AdHHAD6zAQaJ/Address-all-TODOs)
- Logger creation seems to work well and does not need to be simplified further

[ // TODO:: fix indentation when `writeInline` retains indent
](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ShapeValueGenerator.kt#L116)
- Indentation issues don't seem pervasive & comment is 2 years old

TODO:: When https://github.com/apple/swift-numerics supports Integer conforming to Real protocol, we need to
            change  [UInt8] to Complex<Integer>. Apple's work is being tracked in apple/swift-numerics#5
- [ShapeValueGenerator.kt](https://github.com/smithy-lang/smithy-swift/blob/6037a8157082d00da6ff1be1462022dcaccb3662/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ShapeValueGenerator.kt#L340)
- [SymbolVisitor.kt](https://github.com/smithy-lang/smithy-swift/blob/6037a8157082d00da6ff1be1462022dcaccb3662/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SymbolVisitor.kt#L119)
- Apple's work is being tracked in https://github.com/apple/swift-numerics/issues/5 & our open issue is https://github.com/awslabs/aws-sdk-swift/issues/235
- Neither has been touched since they were created. It seems Apple is not going to complete work on this anytime soon.

[// TODO create resource type](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SymbolVisitor.kt#L200)
- the same TODO exists in [smithy-python](https://github.com/smithy-lang/smithy-python/blob/94fdd7de0baffe536bc7fd62f23a1352c1b66ecf/codegen/smithy-python-codegen/src/main/java/software/amazon/smithy/python/codegen/SymbolVisitor.java#L312) as well
- let's take a look at this one as a group

[// TODO: MUST FIX BEFORE SHIPPING. check to see if new synthetic input or output shapes conflict with any other shapes in the model by walking the model and fail code generation](https://github.com/smithy-lang/smithy-swift/blame/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/AddOperationShapes.kt#L42)
- comment is 2 years old and we haven't run into any issues with conflicting shapes during codegen. next steps / reproduction steps are unclear.
- Let's take a look at this one as a group

[// TODO: Support proper deserialization of http response query](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/httpResponse/bindingTraits/HttpResponseTraitQueryParams.kt#L19)
- unclear what is improper about our deserialization
- let's take a look at this one as a group

[// TODO: Make this pluggable so that this code can exist in aws-sdk-swift](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/formurl/StructEncodeFormURLGenerator.kt#L70)
- unclear why we would want this code in aws-sdk-swift as it appears to be a general smithy function that is not specific to AWS

[TODO("Organize test suites of smithy-swift and aws-sdk-swift and see if this class and consumers of this class should be moved to aws-sdk-swift OR AWS protocol tests in aws-sdk-swift should be moved to smithy-swift.")](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/test/kotlin/mocks/MockHttpResponseBindingErrorGenerator.kt#L41)
- written by @sichanyoo
- Let's discuss as a group. Maybe we need or have a backlog ticket on examining the state of smithy-swift and what can and should be moved to aws-sdk-swift and vice versa.

### Use Case

Clean up repository.

### Proposed Solution

Remove unnecessary TODOs to clean up repo.

### Other Information

Related issue: #710

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
[This document](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/design/DESIGN.md) will be moved to Quip, and be edited / revised before being put public again.

**Comment by sichanyoo** [comment]
[// TODO create resource type](https://github.com/smithy-lang/smithy-swift/blob/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SymbolVisitor.kt#L200) - check for other SDKs whether this is common across SDKs

**Comment by sichanyoo** [comment]
Pick up next grooming with [// TODO: MUST FIX BEFORE SHIPPING. check to see if new synthetic input or output shapes conflict with any other shapes in the model by walking the model and fail code generation](https://github.com/smithy-lang/smithy-swift/blame/53fbde27f536f4287edfd4ff08bb5ebe8dc75169/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/AddOperationShapes.kt#L42)

**Comment by dayaffe** [comment]
DESIGN.md document will be deleted. I have moved a copy of the raw file to `/7wBGA7k8jGyM/Smithy-Swift-SDK-DESIGNmd`

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.32.0
