### ISSUE TITLE
Bump up CRT version with included fix for forced unwrapping

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1226]
### Describe the feature

When CRT fixes [#212](https://github.com/awslabs/aws-crt-swift/issues/212) we will need to include the update in our release.

### Use Case

Ensure customers who use Swift SDK dont run into this issue!

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Blocked until CRT publishes a fix

**Comment by jbelkins** [comment]
Fixed in aws-crt-swift 0.23.0, moving back to Todo

**Comment by jbelkins** [comment]
Already shipped, closing.
