### ISSUE TITLE
ClientRuntime.URLQueryItem typealias

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1229]
```[tasklist]
### Tasks
```

**Comment by smivij** [comment]
Tracking issue for https://github.com/smithy-lang/smithy-swift/issues/561

**Comment by sichanyoo** [comment]
Released with:
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
