### ISSUE TITLE
Remove public extensions from Swift standard library & Foundation types

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1230]
### Describe the feature

Swift allows the developer to extend types with new functionality.  This includes Swift's built-in standard library and Foundation types.  This technique is often used to produce easy-to-read code.

However, when these extensions are exposed publicly, this can also cause confusion.  Extended methods will "leak" into whatever context the enclosing module is imported into.

To prevent this, we should audit our type extensions to ensure that they are not exposed publicly, and create an alternative where needed.

### Use Case

To minimize the leakage of extensions to Swift standard library & Foundation types.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2155
