### ISSUE TITLE
Configure proxy settings on CRT HTTP client

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1256]
### Describe the feature

Expose configuration settings on AWS service clients to allow for the configuration of HTTP proxy settings.

### Use Case

To allow for:
- Use of the SDK behind a proxy
- Monitoring HTTP traffic while debugging

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2156
