### ISSUE TITLE
Improve codegen-build-test workflow with team-scoped authorization to run

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1264]
### Describe the feature

To prevent excessive use of CI minutes, restrict the codegen-build-test CI workflow to running only when authorized by a Swift team member.

### Use Case

To allow for easy, secure authorization of lengthy CI tasks.

### Proposed Solution

Implement team-scoped manual authorization using Github deployment environments.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Blocked: Waiting for AppSec to provide their review
