### ISSUE TITLE
chore: bump up CRT version for IMDSv1 fallback fix

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1271]
### Describe the feature

Bump up CRT version to latest to take advantage of IMDSv1 fallback fix

### Use Case

Fix IMDSv1 fallback in default chain provider

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.34.0
