### ISSUE TITLE
UnauthorizedOperation error generates an UnknownAWSHTTPServiceError

### ISSUE THREAD

**Issue by sebsto** [awslabs/aws-sdk-swift#1278]
### Describe the bug

When I call an API for which I don't have authorization, the code receives  an  `UnknownAWSHTTPServiceError` that wraps a `typeName` of `UnauthorizedOperation`

Is it possible to directly catch a more descriptive error type than `UnknownAWSHTTPServiceError` ?

```text
UnknownAWSHTTPServiceError(typeName: Optional("UnauthorizedOperation"), message: Optional("You are not authorized to perform this operation. User: arn:aws:sts::486652066693:assumed-role/amplify-ec2manager-dev-191541-authRole/CognitoIdentityCredentials is not authorized to perform: ec2:DescribeInstances because no identity-based policy allows the ec2:DescribeInstances action"), requestID: Optional("a97a0f5a-7c3b-4819-a437-2a90da59abc3"), requestID2: nil, httpResponse: 
Status Code: http_status_403 
 Transfer-Encoding: chunked, 
Content-Type: text/xml;charset=UTF-8, 
Cache-Control: no-cache, no-store, 
Strict-Transport-Security: max-age=31536000; includeSubDomains, 
vary: accept-encoding, 
x-amzn-RequestId: a97a0f5a-7c3b-4819-a437-2a90da59abc3, 
Date: Wed, 27 Dec 2023 16:53:13 GMT, 
Server: AmazonEC2)
```

Code Example, run with temporary credentials that don't have `ec2:DescribeInstance` permission.

```swift
        let request = AWSEC2.DescribeInstancesInput()
        do {
            let response = try await ec2Client().describeInstances(input: request)
            // do something with response 
        } catch let error as AWSServiceError {
            print("AWSServiceError")
            print(type(of:error)) // UnknownAWSHTTPServiceError
            print(error) // UnknownAWSHTTPServiceError(typeName: Optional("UnauthorizedOperation"), message: Optional("You are not authorized to perform this operation. User: arn:aws:sts::486652066693:assumed-role/amplify-ec2manager-dev-191541-authRole/CognitoIdentityCredentials is not authorized to perform: ec2:DescribeInstances because no identity-based policy allows the ec2:DescribeInstances action"), requestID: Optional("a97a0f5a-7c3b-4819-a437-2a90da59abc3"), requestID2: nil, httpResponse: 
        }
```

### Expected Behavior

I expected an `UnauthorizedOperation` error to allow to provide a specific error message back to the caller

### Current Behavior

The `UnauthorizedOperation` is wrapped into a generic ````swift
        let request = AWSEC2.DescribeInstancesInput()
        do {
            let response = try await ec2Client().describeInstances(input: request)
            // do something with response 
        } catch let error as AWSServiceError {
            print("AWSServiceError")
            print(type(of:error)) // UnknownAWSHTTPServiceError
            print(error) // UnknownAWSHTTPServiceError(typeName: Optional("UnauthorizedOperation"), message: Optional("You are not authorized to perform this operation. User: arn:aws:sts::486652066693:assumed-role/amplify-ec2manager-dev-191541-authRole/CognitoIdentityCredentials is not authorized to perform: ec2:DescribeInstances because no identity-based policy allows the ec2:DescribeInstances action"), requestID: Optional("a97a0f5a-7c3b-4819-a437-2a90da59abc3"), requestID2: nil, httpResponse: 
        }
````__

### Reproduction Steps

Run this code with credentials that don't have `ec2:DescribeInstance' permission.

```swift
        let request = AWSEC2.DescribeInstancesInput()
        do {
            let response = try await ec2Client().describeInstances(input: request)
            // do something with response 
        } catch let error as AWSServiceError {
            print("AWSServiceError")
            print(type(of:error)) // UnknownAWSHTTPServiceError
            print(error) // UnknownAWSHTTPServiceError(typeName: Optional("UnauthorizedOperation"), message: Optional("You are not authorized to perform this operation. User: arn:aws:sts::486652066693:assumed-role/amplify-ec2manager-dev-191541-authRole/CognitoIdentityCredentials is not authorized to perform: ec2:DescribeInstances because no identity-based policy allows the ec2:DescribeInstances action"), requestID: Optional("a97a0f5a-7c3b-4819-a437-2a90da59abc3"), requestID2: nil, httpResponse: 
        }
```

### Possible Solution

Unwrap the `UnknownAWSHTTPServiceError` and write a `switch` case to handle the different error types

### Additional Information/Context

_No response_

### AWS SWIFT SDK version used

0.31.0

### Compiler and Version used

Xcode 15.1

### Operating System and version

macOS 14.2.1

**Comment by jbelkins** [comment]
Thanks for your report.

We don't recommend catching the `UnknownAWSHTTPServiceError` by type when you're catching an error that's not modeled by the SDK.  (In fact, we are considering making `UnknownAWSHTTPServiceError` private in a future release, to prevent catching that concrete type.)

The reason is that catching a concrete `UnknownAWSHTTPServiceError` will cause your code to break if the service converts an unmodeled error into a modeled one in the future.  We want services to be able to improve their APIs by modeling previously unmodeled errors, but also to be able to do so without breaking customers who already handle those errors.

A more future-proof method of error triage is to cast the error to `AWSServiceError` and handle errors based on their `errorCode`:
```swift
do {
    let output = try await client.performOperation(input: input)
} catch let error as AWSServiceError {
    switch error.errorCode {
    case "ExpiredToken":
        print("The security token for your AWS credentials expired, renew them")
    default:
        print("Unknown error: \(error)")
    }
}
```

Triaging unmodeled errors by their `errorCode` ensures that if an error is converted from unmodeled to modeled by the service in the future, it will still be caught, since all modeled service errors and `UnknownAWSHTTPServiceError` all conform to `AWSServiceError`.  The `errorCode` for an error will not change when it is modeled.

cc: @shepazon

**Comment by sebsto** [comment]
Thank you for the explanation @jbelkins 
So this is not a bug but a feature.  
@shepazon can you udate the doc? This page in particular 
https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/using-client-services.html

Thanks !

**Comment by deevus** [comment]
Sorry to bump this. 

I'm getting a `ValidationException` from DynamoDB when trying to use `BatchWriteItem` which is wrapped in an `UnknownAWSHttpServiceError`. 

I'd like to resolve it but I have no idea what the validation error is. I was hoping to snoop at the http response but I can't access it.

**Comment by sebsto** [comment]
@deevus this is not related to the original message posted.

ValidationError means your data do not match the schema.  You can probably get a more detailed message in the `error.message` property

**Comment by OctoJonP** [comment]
@dayaffe This is what was in the error http response body:
```
{"__type":"com.amazon.coral.validate#ValidationException","message":"One or more parameter values were invalid: ReadCapacityUnits and WriteCapacityUnits must both be specified when BillingMode is PROVISIONED"}
```

This is the createTable function I have defined at the moment:
```
func createTable() async throws {
        do {
            guard let client = self.ddbClient else {
                throw DataWrapperTableError.uninitialisedClient
            }

            let input = CreateTableInput(
                attributeDefinitions: [
                    DynamoDBClientTypes.AttributeDefinition(
                        attributeName: "recordId",
                        attributeType: .s
                    ),
                    DynamoDBClientTypes.AttributeDefinition(
                        attributeName: "createdAtMillseconds",
                        attributeType: .n
                    ),
                    DynamoDBClientTypes.AttributeDefinition(
                        attributeName: "recordType",
                        attributeType: .s
                    ),
                    DynamoDBClientTypes.AttributeDefinition(
                        attributeName: "recordData",
                        attributeType: .s
                    ),
                ],
                keySchema: [
                    DynamoDBClientTypes.KeySchemaElement(
                        attributeName: "recordId",
                        keyType: .hash
                    ),
                    DynamoDBClientTypes.KeySchemaElement(
                        attributeName: "createdAtMilliseconds",
                        keyType: .range
                    ),
                ],
                tableName: self.tableName,
            )
            let output = try await client.createTable(input: input)
            if output.tableDescription == nil {
                throw DataWrapperTableError.tableNotFound
            }
        } catch {
            if let httpError = error as? UnknownAWSHTTPServiceError {
                let bodyData = try await Data(httpError.httpResponse.body.readData()!)
                print(String(data: bodyData, encoding: .utf8)!)
            }
            throw error
        }
    }
```
