### ISSUE TITLE
Test AWS SDK for Swift on physical tvOS device

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1289]
### Describe the feature

The AWS SDK for Swift has not yet been operationally tested on a physical tvOS device.

Test to ensure that AWS requests can be made successfully from a tvOS device.

### Use Case

To ensure that the SDK behaves correctly on tvOS devices.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2158
