### ISSUE TITLE
feat: Upgrade CRT version to include MD5 fix

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1292]
### Describe the feature

Upgrade CRT version to include MD5 fix

### Use Case

Will allow us to remove utf8 encoding before computing MD5 algorithm.

### Proposed Solution

- Remove [this line](https://github.com/smithy-lang/smithy-swift/blob/f9046ac56b88aa65531b2d01dc66cb2faf9c01d3/Sources/ClientRuntime/Networking/Http/Middlewares/ContentMD5Middleware.swift#L25)
- Add base64encoding call if appropriate [here](https://github.com/smithy-lang/smithy-swift/blob/f9046ac56b88aa65531b2d01dc66cb2faf9c01d3/Sources/ClientRuntime/Networking/Http/Middlewares/ContentMD5Middleware.swift#L29)

### Other Information

[#222](https://github.com/awslabs/aws-crt-swift/issues/222)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.34.0
