### ISSUE TITLE
Investigate application states in Mac desktop applications [research]

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1307]
### Describe the feature

Investigate the application lifecycle states that are used by Mac applications, to determine if CRT HTTP client event handling would need to be changed to Network.framework to support Mac desktop applications and/or desktop utilities.

### Use Case

To determine work needed to support the CRT HTTP client on the Mac platform.

### Proposed Solution

Research Apple documentation & Mac development community resources.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
cc: @waahm7

**Comment by sichanyoo** [comment]
Tested using a simple dummy macOS application that uploads a 5GB file to S3 using CRT HTTP client.
When app is unfocused or minimized, it uploads the file successfully as expected.
When mac is put to sleep, it fails to upload the file as expected.

However, for the scenario where mac is put to sleep, the application terminated unexpectedly. A follow-up ticket is created for this bug, and is getting worked on now. 

*Follow-up ticket for the bug found: https://github.com/awslabs/aws-sdk-swift/issues/1474
