### ISSUE TITLE
Enable the ECS Credential Provider test on CI

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1310]
### Describe the feature

Perform needed setup on CI to enable this test to pass, then re-enable the test.

### Use Case

To provide maximum integration test coverage on CI.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Tracked in https://github.com/awslabs/aws-sdk-swift/issues/1374
