### ISSUE TITLE
Swift SDK retries requests that should not be retried

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1314]
### Describe the bug

Swift SDK retries requests that should not be retried.

Example: HTTP/400 Error, `UserLambdaValidationException` gets retried in Swift SDK. Kotlin SDK does not retry this error. This error is not marked as retryable in the service model.

### Expected Behavior

Request gets executed 1 time and does not get retried before an error being thrown back to the user.

### Current Behavior

Request gets executed 3 times before an error is thrown back to the user.

### Reproduction Steps

See additional information/context

### Additional Information/Context

See `V1146187612`

### AWS SWIFT SDK version used

Amplify iOS SDK: 2.21.4

### Compiler and Version used

n/a

### Operating System and version

Lambda

**Comment by sichanyoo** [comment]
Released with:
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
