### ISSUE TITLE
Eliminate client protocols

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1321]
### Describe the feature

Eliminate the code-generated client protocol from services, since it is large and not needed by either developers or customers.

### Use Case

This change will result in:
- Simpler, smaller documentation bundles.
- Smaller binaries and faster compilation.
- No real loss of functionality for customers.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Released with: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
