### ISSUE TITLE
Project fails to build on macOS 12 / Xcode 14 / mac destination

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1334]
### Describe the bug

The project fails to build on the configuration identified in the title.  The problem occurs on both Github. Actions and the SDK build system.

The problem is apparently due to the recent release of swift-collections 1.1.0.

### Expected Behavior

Project should build successfully on all supported tools versions and platforms.

### Current Behavior

Project fails to build on the build configuration identified in the title.

Here is an example CI build with the failure in the logs:
https://github.com/awslabs/aws-sdk-swift/actions/runs/7832449011/job/21371164845

### Reproduction Steps

Build the project on the identified configuration, ensuring swift-collections 1.1.0 is the installed version.
Observe compile failure in the build logs

### Possible Solution

Remove swift-collections as a dependency of aws-crt-swift.  CRT indicates that swift-collections is required but unused.

### AWS SWIFT SDK version used

main

### Compiler and Version used

Xcode 14.0.1

### Operating System and version

macOS 12

**Comment by sichanyoo** [comment]
Released with: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
