### ISSUE TITLE
Run CI on Apple Silicon

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1339]
### Describe the feature

Run Apple-platform CI jobs on Apple Silicon.

### Use Case

To speed up the development cycle.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Released with: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
