### ISSUE TITLE
Update Swiftlint on both projects to 0.54.0

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1341]
### Describe the feature

Update to latest SwiftLint on CI.

### Use Case

To ensure latest linter features are used.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Released with: 
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
