### ISSUE TITLE
Add support for sigv4-s3express auth scheme to Endpoint 2.0

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1365]
### Describe the feature

Currently code generated auth scheme resolver for an endpoint resolves sigv4 and sigv4a and does not have support for sigv4-s3express. This new feature will add codegen for sigv4-s3express to endpoint resolver middleware & endpoint resolver, as well as additive changes to runtime library to support `.sigV4S3Express` enum case for `AWSClientRuntime.AuthSchemeResolver.AuthScheme`.

### Use Case

Authenticating with SigV4 S3 Express.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Discuss this with CRT to determine if sigv4-s3express signing requires CRT support.

**Comment by sichanyoo** [comment]
Moved to 2133
