### ISSUE TITLE
Make identity resolver integration tests run daily & programmatically

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1374]
Currently, identity resolver integration tests are not run as part of the Github CI for PRs, because they have more involved setup that use:
- manual UI interaction to set up AWS resources (e.g., IAM Identity Center for SSO identity resolver integration test)
- bash script that must be manually run before running the test to build docker image and push it up to ECR (e.g., test for ECSAWSCredentialIdentityResolver), etc.

In addition to requiring non-programmatic setup, these tests take a long time to run, going from 10 to 20 minutes each. 

We don't want to include these in CI given the amount of time it takes to run, but we still want to run these tests to ensure correct code behavior.

Task: Refactor where possible and integrate the tests into Github to be run every night, programmatically.

**Comment by jbelkins** [comment]
Include the following:
- IMDS
- ECS
- SSO
- Process

In the future, include other identity resolvers in this suite.

**Comment by sichanyoo** [comment]
Investigate & determine whether this daily runs might benefit from being selectively triggered based on files that were changed. E.g., only running IMDS test if IMDS related things were changed, etc.

**Comment by sichanyoo** [comment]
Moved to 2134
