### ISSUE TITLE
Add integration test for S3 404 w/o body

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1376]
### Describe the feature

S3 needs a customization where a HTTP/404 without a body should result in a `NotFound` error.  The customization is already provided, but it is untested.

Create an integration tests to verify this error is correctly handled.

### Use Case

To ensure S3 errors are correctly handled.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Released with https://github.com/awslabs/aws-sdk-swift/releases/tag/0.42.0.
