### ISSUE TITLE
Event streaming support for protocols that use XML (e.g., restXml)

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1379]
### Background 

Currently, the `DefaultMessageEncoderStream` in smithy-swift's ClientRuntime has `requestEncoder: RequestEncoder` property. In protocols that use JSON, this field is populated by the [encoder property of the client object](https://github.com/awslabs/aws-sdk-swift/blob/d67f71619ee30f04312fe4d7eb54da38bd355b62/Sources/Services/AWSTranscribeStreaming/TranscribeStreamingClient.swift#L13-L21).

Code path for an event streaming operation:
- The encoder (JSONEncoder) is saved to middleware context when the context is built ([example](https://github.com/awslabs/aws-sdk-swift/blob/d67f71619ee30f04312fe4d7eb54da38bd355b62/Sources/Services/AWSTranscribeStreaming/TranscribeStreamingClient.swift#L181))
- The saved encoder is fetched from middleware context in `EventStreamBodyMiddleware` [here](https://github.com/smithy-lang/smithy-swift/blob/189d48ccdb8167beee91db97b63a177c368e0152/Sources/ClientRuntime/Networking/Http/Middlewares/RequestBody/EventStreamBodyMiddleware.swift#L36).
- Then, that encoder is passed to `DefaultMessageEncoderStream` and is used to parse `Event` into `EventStream.Message` [here](https://github.com/smithy-lang/smithy-swift/blob/189d48ccdb8167beee91db97b63a177c368e0152/Sources/ClientRuntime/EventStream/DefaultMessageEncoderStream.swift#L70).

However, following the XML serde refactor that got rid of 3rd party XML library that uses Codable conformances, encoder and decoder are no longer properties of XML service clients, meaning event streaming operation for an XML protocol would fail due to missing request encoder.

### Why was this not caught?

For event stream input, it is because currently no AWS service uses XML & event stream input combo.

For event stream output, the reason why no warnings were thrown is because we do not have integration test for the one operation that uses XML AND event stream output, which is S3:SelectObjectContentEventStream. 

### Task

- Investigate if event streaming input and output behaves as it should for restXml protocol
- Implement support based on the findings.
- Create an integration test for S3:SelectObjectContentEventStream.

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.40.0
