### ISSUE TITLE
Assorted doc related Qs for the Swift dev team

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#1397]
### Describe the issue

This issue consolidates a number of questions and issues related to documentation. Some of them are things that just need answers, and others are changes that should probably be made.

# Questions about work on the Swift SDK Developer Guide

## Modeled vs. unmodeled errors

What if anything needs to be said about modeled vs. unmodeled errors? Are there differences in handling these that are important to be covered in the developer guide?

Related to this: based on past conversations, the goal is for `ClientRuntime` to become an implementation detail, essentially. Does this imply that the properties added to errors by the `ModeledError` protocol should not be used by customers?

### Links

This is more a request for new content than anything that already exists.

**Comment by sichanyoo** [comment]
I split the part about missing docs in generated SDK to issue #1401 to separate simple codegen addition work.

**Comment by sichanyoo** [comment]
Effort is for initial inquiry into more details. Follow-up tickets for additional work _may_ be written.

**Comment by sichanyoo** [comment]
Closing, as questions have mostly been answered by @jbelkins.
