### ISSUE TITLE
HTTP request body streaming fails intermittently with the URLSession-based HTTP client

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1399]
### Describe the bug

On infrequent occasions, the HTTP request body fails to stream to the server when a HTTP connection is initiated.  The connection then times out since the expected body data is not sent.

This only happens when using the URLSession-based HTTP client.

### Expected Behavior

After initiating a connection, the body should stream to the server immediately, and the connection should complete successfully.

### Current Behavior

On infrequent occasions, no data is sent to the server, and the connection times out.

### Reproduction Steps

Hard to consistently reproduce, but run integration tests repeatedly on a Mac and you should see this in the first few runs.
It happens more often on macOS 13 / Xcode 14 than with macOS 14 / Xcode 15, but will happen on every macOS and Xcode.

### Possible Solution

FoundationStreamBridge is not streaming data when the stream pair has room to receive.

### AWS SWIFT SDK version used

main / latest

### Compiler and Version used

Xcode 14.0.1, 15.2

### Operating System and version

macOS 13, 14

**Comment by sichanyoo** [comment]
Went out with release(s):
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.38.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.43.0
