### ISSUE TITLE
Comparative benchmarking with community AWS Swift library

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1411]

**Comment by jbelkins** [comment]
Will identify 5-10 services to measure

Measure time spent in the SDK, versus time spent on network requests - either exclude network from measurement or mock out network requests

**Comment by jbelkins** [comment]
Also measure binary size & compare.  See Kotlin SDK for their measurement tools, dashboard, etc.

**Comment by sichanyoo** [comment]
Finished & reviewed with team + principal.
/ml9bAXBKNCeK/Benchmarking-Soto-vs-AWS-Swift-SDK
