### ISSUE TITLE
Refactor TrimHostedZone customization

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1444]
### Describe the feature

Currently this customization is applied to 14 operations on AWS Route 53.  For each of these operations, a custom middleware is code-generated.  This is wasteful of resources and bloats binary size.

Refactor this customization to reuse a single middleware for all operations requiring the customization.

### Use Case

- Reduces compile time & binary size
- Enhances code maintainability & testability

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Released in 0.43
