### ISSUE TITLE
AWS Route 53 `InvalidBatchError` customization does not work

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1447]
### Describe the bug

There is a customization in place to accommodate a difference between the published format of the `InvalidBatchError` operation error and the format actually returned by Route 53, i.e.:
https://github.com/awslabs/aws-sdk-swift/blob/main/codegen/smithy-aws-swift-codegen/src/main/kotlin/software/amazon/smithy/aws/swift/codegen/customization/route53/Route53InvalidBatchErrorIntegration.kt

However, this customization does not actually deserialize the data returned by Route 53 when an `InvalidBatchError` occurs.

### Expected Behavior

The `InvalidBatchError` should be populated by error messages for the one or more errors that occur in a Route 53 batch update operation.

### Current Behavior

The `Message` and `Messages` fields in an `InvalidBatchError` are both empty.

### Reproduction Steps

Take the Route 53 integration test in this PR, and modify it to create an A record not in the hosted domain.
https://github.com/awslabs/aws-sdk-swift/pull/1445

Run the test.

### AWS SWIFT SDK version used

main

### Compiler and Version used

Xcode 15.3

### Operating System and version

macOS 14

**Comment by sichanyoo** [comment]
Tracked in https://github.com/orgs/awslabs/projects/61/views/3?pane=issue&itemId=60471658#:~:text=customization%20is%20incomplete-,%231446,-Edit

**Comment by sichanyoo** [comment]
Moved to 2163
