### ISSUE TITLE
Connection timeout issue in URLSessionHTTPClient

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1457]
Internal: /D123360092

**Comment by sichanyoo** [comment]
Waiting for correspondence from customer.

**Comment by jbelkins** [comment]
Unable to reproduce the customer's issue but a potential fix for this issue has been delivered to Amplify-swift in aws-sdk-swift 0.36.2.  Will follow up with affected customer & support engineer once this has been released by Amplify.

**Comment by jbelkins** [comment]
Potential fix for this issue released in Amplify 2.33.2
https://github.com/aws-amplify/amplify-swift/releases/tag/2.33.2

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.44.0
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.44.0
