### ISSUE TITLE
feat: preview builds need only build a single service

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1465]
### Describe the feature

- Add ability to modify sdk.properties file in aws-sdk-swift to match model file provided in a build request

### Use Case

- Should reduce the number of EC2 macs we need to pay for by greatly decrease the time needed to build the SDK

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2146
