### ISSUE TITLE
Implement Endpoints 2.0 OperationContextParams

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1517]
### Describe the feature

Smithy 1.49.0 added support for string array endpoint parameters and operation context endpoint parameters.
https://github.com/smithy-lang/smithy/releases/tag/1.49.0

These features are generally described here:
https://smithy.io/2.0/additional-specs/rules-engine/parameters.html

String array-typed endpoint parameters are being implemented with the update to Smithy 1.49.0, but `OperationContextParams` will require greater work plus a bugfix:
- `OperationContextParams` defines a JMESPath (restricted to a limited JMES feature set) that we must code-generate into a Swift expression to get the needed params at runtime.
- There is also a bug in Smithy validation that prevents `OperationContextParams` from being defined on an operation without some extra trickery.  Link to fix in main Smithy project: https://github.com/smithy-lang/smithy/pull/2295

Implement `OperationContextParams` once the validation bug has been resolved.

### Use Case

To support all parameter field types on AWS endpoints.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
We use CRT to take our endpoint params & evaluate them against the endpoint rules.

Filed this ticket to allow us to set the `Array<String>` data type on the `EndpointsRequestContext` that is used to pass endpoint params into CRT:
https://github.com/awslabs/aws-crt-swift/issues/266

**Comment by jbelkins** [comment]
Will investigate the plan for rolling this param out through services, so we can determine the appropriate priority for work.

**Comment by sichanyoo** [comment]
Note: check whether any change is needed in CRT.

**Comment by sichanyoo** [comment]
Tracked internally in SWIFT-1125
