### ISSUE TITLE
Investigate AWS SDK for Swift's compiled model binary size vs. community alternative

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1519]
### Describe the feature

A recent investigation into AWS SDK binary size revealed that AWS SDK models are substantially larger than those of community-supported solutions.
https://github.com/awslabs/aws-sdk-swift/issues/1510#issuecomment-2125020538

Investigate further to determine the exact reason for the size of AWS SDK binary models.

### Use Case

To ensure the AWS SDK for Swift is as compact as possible when compiled to binary.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2160
