### ISSUE TITLE
Sigv4a as trait - 2 CRs to SEP need to be included

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1599]

**Comment by smivij** [comment]
There were to CRs to the SEP post our implementation which need to be incorporated - Refer to SWIFT-575

**Comment by jbelkins** [comment]
We think these are already done; this ticket is to verify completion.

**Comment by sichanyoo** [comment]
- When I&A was done, smithy.api#noAuth was used correctly to begin with (as I referred to Smithy spec and not sep for the trait tag)
- Because Swift SDK currently supports SigV4/Sigv4A only, second ticket might not apply to us.
Will double check regardless before marking post-GA.

**Comment by sichanyoo** [comment]
Also in scope: find out status on cross-SDK decision on sigv4a trait exceptions given to services. Update list of services that rules based auth scheme resolver gets used for accordingly.

**Comment by sichanyoo** [comment]
Verified that there's no relevant change that requires action from us. Closing the ticket.
