### ISSUE TITLE
Fix redaction scope to include nested shapes

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1632]
### Background

Shapes with sensitive trait in Smithy models need to have custom implementation of `CustomDebugStringConvertible` generated for it, so the sensitive values don't get included in the logs.

Turns out the nested values in list and map shapes weren't being properly redacted (items in lists, and keys and values in maps). The redactions cope must be widened to include these as well.

**Comment by dayaffe** [comment]
Released in smithy-swift 0.52 alongside aws-sdk-swift 0.47
