### ISSUE TITLE
AWS ACM-PCA service crashes the update models script

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1635]
### Describe the bug

When attempting to update models with the `updatemodels.sh` script, the following error is encountered which crashes the script:
```
FAIL: /tmp/tmp.gVXEQl2rqD/aws-models/acm-pca/smithy/model.json does not have 1: 0
 ```

The apparent cause is that the acm-pca service was updated to not have a `version` property; apparently this was part of migrating the service's model from Coral to Smithy last week.

The problem was discovered when the nightly Model Integration build started to fail Saturday morning.

### Expected Behavior

The `updatemodels.sh` script should execute successfully.

### Current Behavior

The `updatemodels.sh` script fails as noted above.

### Reproduction Steps

Run the Model Integration workflow on main branch, or
Run the `updatemodels.sh` script on a development machine

### AWS SWIFT SDK version used

main

### Compiler and Version used

latest

### Operating System and version

latest

**Comment by dayaffe** [comment]
Released in 0.47
