### ISSUE TITLE
CredentialsProvider access in S3Client 

### ISSUE THREAD

**Issue by codtiger** [awslabs/aws-sdk-swift#1641]
### Describe the issue

As far as I know, an instance of an `S3Client` extends `AWSClientRuntime.AWSDefaultClientConfiguration` while `AWSS3ClientConfiguration` used to be a class with a variable `credentialsProvider` which could be used to specify different profiles to be used by the application. Skimming through the codebase has given me the impression that the class is gone and part of credentials has been relocated to `ProfileAWSCredentialIdentityResolver` which is used by `AWSClientConfigDefaultsProvider`? This has been a pretty confusing change that has me glossing over multiple files just to pass a profile name stored somewhere(~/.aws/credentials) to a client.

 The documentation also seem to not address any of this. Can anyone direct me with a working example or at least the classes I should be looking at?
 
 Also the link provided below shows the outdated paramters to S3Client.S3ClientConfiguration. Xcode cannot find `credentialsProvider` as an init argument.

### Links

https://awslabs.github.io/aws-sdk-swift/reference/0.x/AWSS3/S3Client_S3ClientConfiguration

**Comment by dayaffe** [comment]
@codtiger, thank you for your issue! We will look into the docs and make sure they are up-to-date. In the meantime, let me know if the following code example helps resolve any confusion:
```
import AWSSDKIdentity
import AWSS3

...

let profileAWSCredentialsIdentityResolver = try ProfileAWSCredentialIdentityResolver(
    profileName: "profile-name", // If not provided it will be resolved internally via the `AWS_PROFILE` environment variable or defaulted to `default` if not configured.
    configFilePath: "path", // defaults to ~/.aws/config
    credentialsFilePath: "path" // defaults to ~/.aws/credentials
)

let s3client = try await S3Client(
    config: .init(awsCredentialIdentityResolver: profileAWSCredentialsIdentityResolver)
)
```

**Comment by dayaffe** [comment]
The latest documentation can be found at the following links:
- https://sdk.amazonaws.com/swift/api/awssdkforswift/latest/documentation/awssdkforswift/stability
- https://sdk.amazonaws.com/swift/api/awsclientruntime/0.47.0/documentation/awsclientruntime

**Comment by codtiger** [comment]
> @codtiger, thank you for your issue! We will look into the docs and make sure they are up-to-date. In the meantime, let me know if the following code example helps resolve any confusion:
> 
> ```
> import AWSSDKIdentity
> import AWSS3
> 
> ...
> 
> let profileAWSCredentialsIdentityResolver = try ProfileAWSCredentialIdentityResolver(
>     profileName: "profile-name", // If not provided it will be resolved internally via the `AWS_PROFILE` environment variable or defaulted to `default` if not configured.
>     configFilePath: "path", // defaults to ~/.aws/config
>     credentialsFilePath: "path" // defaults to ~/.aws/credentials
> )
> 
> let s3client = try await S3Client(
>     config: .init(awsCredentialIdentityResolver: profileAWSCredentialsIdentityResolver)
> )
> ```

Thank you for this! I was wondering does this require you to have a `default` section in your credentials or config? It looks like the class wouldn't look for the specific profile name if you do not have a `default` in either `~/.aws/config` or `~/.aws/credentials`. I'm asking because I've worked with the Python `boto3`, and the code works fine without it as a  requirement. Is this intended behavior?

**Comment by codtiger** [comment]
@dayaffe Also since I saw you opened a separate issue for all the missing relative documents [here](https://github.com/awslabs/aws-sdk-swift/issues/1643)  feel free to close this. As a side-note, it'd definitely have a better reach and save a lot of time if some of these configuration classes could find their way to https://docs.aws.amazon.com/sdk-for-swift/

Appreciate the help!

**Comment by dayaffe** [comment]
@codtiger if you provide a profile name either as an argument or via environment variable it should look for that profile and not `default`! Yes I've opened issues for updating our documentation links and for making a better documentation landing page. Thank you again for pointing this out to us!
