### ISSUE TITLE
Documentation link is out of date

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1642]
### Describe the issue

Swift SDK documentation link is out of date on awslabs and docs site

### Links

Bad Link: https://awslabs.github.io/aws-sdk-swift/
Bad Link: https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/home.html, scroll down to AWS SDK for Swift Reference, goes to [(deprecated) AWS SDK for Swift Reference](https://awslabs.github.io/aws-sdk-swift/reference/0.x/)

**Comment by sichanyoo** [comment]
Checked and confirmed the API reference hyperlink is updated to new one from deprecated one.
