### ISSUE TITLE
endpoint rule support for complex request parameters

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1646]

**Comment by smivij** [comment]
Reference : SWIFT-1125

**Comment by sichanyoo** [comment]
Notes
- CRT needs to build this into their rules engine
- Then expose it through Swift binding
- Then Swift SDK team needs to use that binding to add support
To be done by end of September

**Comment by sichanyoo** [comment]
Effort for 1 week is assuming all prerequisite work from CRT is finished at time of starting the task.

**Comment by sichanyoo** [comment]
Tracked in https://github.com/awslabs/aws-sdk-swift/issues/1517.
