### ISSUE TITLE
Retest DDB endpoint rules

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#1647]

**Comment by smivij** [comment]
SWIFT-1250 has details

**Comment by sichanyoo** [comment]
Quip doc: `/Account-ID-Test-and-Delivery-Plan`

**Comment by sichanyoo** [comment]
Wrote the findings in a comment to SIM ticket. Our SDK generates, builds, and runs successfully for this endpoint feature in DDB.
