### ISSUE TITLE
Enable a broken protocol test when fix is released in Smithy v1.51.0 

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1706]
### Background

Smithy's protocol test definition for `RestJsonClientIgnoresDefaultValuesIfMemberValuesArePresentInResponse` had an error in the expected value which was fixed [here](https://github.com/smithy-lang/smithy/commit/26ff08f366a8556a6d69a83442f2efba19f9642b), but this won't be available until a new release of v1.51.0 that contains the fix is available.

For now this protocol test will stay disabled even after default value support work get merged ([smithy-swift PR](https://github.com/smithy-lang/smithy-swift/pull/803), [aws-sdk-swift PR](https://github.com/awslabs/aws-sdk-swift/pull/1696)).

Enable the test once Smithy releases v1.51.0 and we start using that version.

**Comment by jbelkins** [comment]
Blocked while waiting for the next Smithy release.

**Comment by jbelkins** [comment]
[Smithy 1.51 release](https://github.com/smithy-lang/smithy/releases/tag/1.51.0) is complete.  Moving back to Todo.
