### ISSUE TITLE
Add input validation for override endpoint / endpoint where helpful

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1707]
### Background

This is a follow-up action item for a comment from ORR.
Investigate whether we do input validation on endpoint path parameters and override endpoint and if so to what extent.
Then, add validation where it will help SDK customers.

**Comment by jbelkins** [comment]
Initial effort is timeboxed.

**Comment by sichanyoo** [comment]
The string value provided by user in service client config actually already has validation when it goes through endpoint resolver. It has to be parsable by CRT's endpoint resolver before it can be properly be used. Otherwise an error is thrown.
