### ISSUE TITLE
S3 Transfer Manager Design Doc

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1710]
### Background

S3 Transfer Manager is a hand-written high-level library for S3 that allows:
- Automatic multipart uploads / downloads for large files
- Recursive and non-recursive directory uploads / downloads
- Checking the transfer progress

### To-do

Write up a detailed design doc for the project & review with team.

Then, write up the project epic issue and subtask issues to start off the project.

**Comment by jbelkins** [comment]
Time-boxed.  "Tricky" parts of the design may be separated into a different task/doc if required.

**Comment by sichanyoo** [comment]
Design doc rough draft complete; S3 TM is put on backlog until customers demand it.
