### ISSUE TITLE
Crash when deinitialising S3Client inside AsyncParsableCommand

### ISSUE THREAD

**Issue by Aquilosion** [awslabs/aws-sdk-swift#1714]
### Describe the bug

If an `S3Client` is instantiated inside an `AsyncParsableCommand`'s `run` method (from [Swift Argument Parser](https://github.com/apple/swift-argument-parser)), it crashes when the `S3Client` is deinitialised. It works fine until that point.

I assume the problem isn't specific to `S3Client`.

### Expected Behavior

No crashes.

### Current Behavior

Crashes as shown:

<img width="1215" alt="Screenshot 2024-09-07 at 16 38 54" src="https://github.com/user-attachments/assets/d0c9a574-47e1-46fe-be7c-03aa9ca3beb0">

### Reproduction Steps

Create a new executable Swift package which depends on Swift Argument Parser and the Swift AWS SDK.

Add this as the only file:

```swift
import ArgumentParser
import AWSS3

@main
struct TestCommand: AsyncParsableCommand {
	func run() async throws {
		_ = try S3Client(region: "eu-west-1")
	}
}
```

It crashes every time.

### AWS SWIFT SDK version used

0.74.0

### Compiler and Version used

Xcode 15.4, Swift 5.10.0.13, Swift Argument Parser 1.5.0

### Operating System and version

macOS 14.6.1 on ARM64

**Comment by sichanyoo** [comment]
Thank you for submitting the issue! We'll take a look into the issue and triage it. 

But could you let us know how you've set up your AWS credentials for your project? The additional info may help locating the issue (in case a specific credentials provider is causing this issue). Thanks!

**Comment by Aquilosion** [comment]
Yes of course: the AWS credentials are configured via the `aws` command line tool, and I'm using an IAM role.

I'm not too familiar with AWS credentials, so in case I've left anything out, the config file looks something like this:

```
[default]
region = eu-west-1
source_profile = default
role_arn = arn:aws:iam::*****:role/*****
role_session_name = *****
```

And the credentials contains an access key ID and secret access key.

**Comment by jbelkins** [comment]
@Aquilosion Fix for this issue shipped today in https://github.com/awslabs/aws-sdk-swift/releases/tag/0.77.0

Please update, retest and let us know if you have further issues.  Thanks!
