### ISSUE TITLE
Run Xcode 16.0 on automated build system

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1716]
### Describe the feature

Once Xcode 16.0 has been released, use it for the "max" AMI on the automated build system.

Build AMI once the 16.0 stable version is released (i.e. when it is released to the Mac App Store.)

### Use Case

To continuously ensure support for the latest Xcode version.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Tracked in internal ticket 1776
