### ISSUE TITLE
Re-export retries related types from SmithyRetriesAPI and SmithyRetries

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#1718]
### Describe the feature

Like we did with the Smithy-related credentials providers, re-export the types associated with retries to remove the need to directly import the Smithy module.

SmithyRetriesAPI is the main API module for retries, but SmithyRetries defines standard retry strategies and the like. Both should be re-exported.

### Use Case

Reducing the need to directly engage with Smithy from code using the SDK for Swift.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
We'd like to discourage customers from directly changing the retry strategy option config option; instead, we want them to use the top-level config options `maxAttempts` and `awsRetryMode` that get pulled in when resolving the `retryStrategyOptions` automatically. For that reason, we'd like to stay away from exposing the retry types via typealias for easier access.
