### ISSUE TITLE
S3 deleteObjects access denied error

### ISSUE THREAD

**Issue by meyertst-aws** [awslabs/aws-sdk-swift#1719]
### Describe the bug

I am getting an access denied error calling `deleteObjects`.  `getObject` works correctly using the same bucket, key and client.

### Expected Behavior

The object should be deleted.

### Current Behavior

The following error is logged.
```
2024-09-10T14:06:16-0400 info URLSessionHTTPClient : [Logging] start URLRequest(https://sgm-test-swift-496.s3.us-east-1.amazonaws.com/?delete) called
2024-09-10T14:06:16-0400 info URLSessionHTTPClient : [Logging]   body is Data
2024-09-10T14:06:16-0400 info URLSessionHTTPClient : [Logging] Either TLSOptions not set or missing values! Using default trust store.
▿ Reading a file.: AWSClientRuntime.UnknownAWSHTTPServiceError
  ▿ typeName: Optional("AccessDenied")
    - some: "AccessDenied"
  ▿ message: Optional("There were headers present in the request which were not signed")
    - some: "There were headers present in the request which were not signed"
  ▿ requestID: Optional("ZVCDRZBTS5K50B93")
    - some: "ZVCDRZBTS5K50B93"
  - requestID2: nil
  ▿ httpResponse: 
Status Code: HTTP status code: 403 
 Connection: close, 
```

### Reproduction Steps

Run the example code:
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/swift/example_code/s3/DeleteObjects

### AWS SWIFT SDK version used

0.72.0

### Compiler and Version used

XCode Version 15.4 (15F31d)

### Operating System and version

MacOs 14.6.1

**Comment by sichanyoo** [comment]
Thank you for submitting the issue!
The fix has been released as of release [v0.77.0](https://github.com/awslabs/aws-sdk-swift/releases/tag/0.77.0).
Closing the issue as resolved.
