### ISSUE TITLE
Document the AWS SDK for Swift versioning policy

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1722]
### Describe the issue

The AWS SDK for Swift versioning policy should be documented in the SDK so that customers can understand & manage change in future SDK releases.

### Links

https://github.com/awslabs/aws-sdk-swift/blob/main/Sources/Core/AWSSDKForSwift/Documentation.docc/stability.md (Existing SDK policy)
https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html (SDK & Tools org policy)

**Comment by dayaffe** [comment]
Tracking in internal ticketing system
