### ISSUE TITLE
HTTP Client for SwiftNIO

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1745]
### Describe the feature

SwiftNIO is a popular option for high-throughput, non-blocking HTTP in the Swift community.
https://github.com/apple/swift-nio

SwiftNIO is an official Swift core project.  It is commonly used both client- and server-side, and forms the basis for most Swift community server frameworks.

SwiftNIO supports HTTP/2 so it can potentially support all current AWS services.

Build a SDK HTTP client that utilizes SwiftNIO for HTTP transport.

### Use Case

To support SDK integration with Swift apps based on SwiftNIO.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Time effort estimate of 2 is for design doc.

**Comment by sichanyoo** [comment]
Moved to 2161
