### ISSUE TITLE
Ensure ECS credential provider / HTTP Credential Provider works as expected

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1753]
### Describe the feature

The SDK currently provides a ECS credential provider:
https://github.com/awslabs/aws-sdk-swift/blob/main/Sources/Core/AWSSDKIdentity/Sources/AWSSDKIdentity/AWSCredentialIdentityResolvers/ECSAWSCredentialIdentityResolver.swift

Verify that this credential resolver provides all the features outlined in the relevant specification for "Container Credential Provider."
https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html

Internal reference: `SWIFT-166`

### Use Case

To ensure that the AWS SDK for Swift provides all expected features for container or HTTP identity resolution.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Tracking in internal ticketing system
