### ISSUE TITLE
Waiters support

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#176]
The following spec needs to be implemented appropriately:       
https://awslabs.github.io/smithy/1.0/spec/waiters.html

The design for this feature is complete and has been broken into the following tickets:
- [x] https://github.com/awslabs/smithy-swift/issues/447
- [x] https://github.com/awslabs/smithy-swift/issues/448
- [x] https://github.com/awslabs/smithy-swift/issues/449
- [x] https://github.com/awslabs/aws-sdk-swift/issues/640

**Comment by jbelkins** [comment]
Re-opening until released

**Comment by epau** [comment]
Released in 0.7.0
