### ISSUE TITLE
Make aws-sdk-swift manifest fully Swift 6 compatible

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1760]
### Describe the feature

The aws-sdk-swift `Package.swift` raises Swift 6 concurrency check warnings.

### Use Case

To build project warning-free on Swift 6.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Tracking in internal ticketing system
