### ISSUE TITLE
Design: Service client release notes

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1766]
### Describe the feature

Prepare a one-page design for providing release notes for changes to specific AWS services.

For example, see the following release notes for a Kotlin SDK release:
https://github.com/awslabs/aws-sdk-kotlin/releases/tag/v1.3.33

Practices of other SDKs should be investigated.

### Use Case

To raise SDK customer awareness of changes included in new SDK versions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Tracking in internal ticketing system
