### ISSUE TITLE
Github pulled visionOS sims from its mac CI images

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1773]
### Describe the bug

On 9/23/2024 Github pulled the visionOS simulators from its macOS 14 runners.
https://github.com/actions/runner-images/issues/10559

This is causing failure of out CI jobs that test against visionOS.

### Expected Behavior

All CI jobs should pass.

### Current Behavior

The macOS 14 / Xcode 16 / visionOS sim 2.0 CI job fails due to not locating the required simulator.

### Reproduction Steps

Run CI on an aws-sdk-swift PR
Observe the macOS 14 / Xcode 16 / visionOS sim 2.0 build fail.

### Possible Solution

The GH issue linked above includes code that can be used to re-install the simulator.

### AWS SWIFT SDK version used

latest / main

### Compiler and Version used

Xcode 16

### Operating System and version

macOS 14 on Github CI

**Comment by dayaffe** [comment]
Tracking in internal ticketing system
