### ISSUE TITLE
RekognitionClient doesn't accept credentials

### ISSUE THREAD

**Issue by oanav21** [awslabs/aws-sdk-swift#1813]
### Describe the issue

To create the RekognitionClient, in an older documentation, this was the way to do it:
```swift
  let rekognitionClient = RekognitionClient(
        credentialsProvider: credentialsProvider,
        region: REGION
    )
```
But now, it only accepts the region as a parameter and I don't know how to pass the credentials to it. 
Please, redirect me to the proper documentation.

Example of usage:

How we get the credentials:
```swift
@MainActor
    func authenticateWithCognito(idToken: String?) async throws -> Bool {
        
        guard let idToken = idToken else {
            print("ID Token is null")
            throw AuthenticationError.idTokenNull
        }
        
        let cognitoClient = try CognitoIdentityClient(region: REGION)
        
        let getIdRequest = GetIdInput(
            identityPoolId: IDENTITY_POOL_ID,
            logins: [PROVIDER_NAME: idToken]
        )
        
        do {
            
            let identityResponse = try await cognitoClient.getId(input: getIdRequest)
            guard let identityId = identityResponse.identityId else {
                throw AuthenticationError.failedToRetrieveIdentityId
            }
            
            awsCredentials = try await getAwsCredentials(identityPoolId: IDENTITY_POOL_ID, idToken: idToken, region: REGION)
            
            return true

        } catch {
            
            let errorMessage = error.localizedDescription.lowercased()
            if !errorMessage.isEmpty,
               errorMessage.contains("notauthorizedexception") {
                print("Token expired or invalid, refreshing Firebase token")
                let newToken = try await refreshFirebaseTokenAndAuthenticate()
                return try await authenticateWithCognito(idToken: newToken)
            } else {
                print("Error during Cognito authentication: \(error.localizedDescription)")
                throw AuthenticationError.cognitoAuthenticationFailed(error.localizedDescription)
            }
        }
        
    }
```

How we tried to use rekognition based on aws-sdk-kotlin, which we've managed to implement on android already:
```swift
@MainActor
    func startPhotoRekognition(isImageFromGallery: Bool, sourceImage: UIImage) async throws -> Bool {
        
        guard let imageData = sourceImage.jpegData(compressionQuality: 0.8) else {
            throw PhotoRekognitionError.imageProcessingFailed
        }
        
        let rekognitionClient = RekognitionClient(
        credentialsProvider: credentialsProvider,
        region: REGION
    )
        let detectModerationLabelsRequest = DetectModerationLabelsInput(
            image: RekognitionClientTypes.Image(bytes: imageData),
            minConfidence: 90
        )
        
        let response = try await rekognitionClient.detectModerationLabels(input: detectModerationLabelsRequest)
        
        if let labels = response.moderationLabels, !labels.isEmpty {
           return false
        } else {
            return true
        }
    }
```
Thank you!

### Links

[Sources/Services/AWSRekognition/Sources/AWSRekognition/RekognitionClient.swift](https://github.com/awslabs/aws-sdk-swift/blob/main/Sources/Services/AWSRekognition/Sources/AWSRekognition/RekognitionClient.swift)

**Comment by sichanyoo** [comment]
Hello! Thank you for submitting the ticket.

The API for providing crednetials provider to the client has changed.
The parameter name is now `awsCredentialIdentityResolver` instead of `credentialsProvider`, as you can see [here](https://github.com/awslabs/aws-sdk-swift/blob/6e0d1ff0ebdefbc53a36125b4fa1a96362c93fe2/Sources/Services/AWSRekognition/Sources/AWSRekognition/RekognitionClient.swift#L97).

Please let me know if that helped, thanks!

**Comment by oanav21** [comment]
I cannot find a way to use that. I should initialise the RekognitionClientConfiguration, am I right? And then I should put the credentials there and after that, call the RekognitionClient(config: ). But what information should I pass to all the parameters from its constructor?

**Comment by dayaffe** [comment]
@oanav21 let me know if this example helps:
```
let config = try await RekognitionClient.RekognitionClientConfiguration(
    awsCredentialIdentityResolver: credentialsProvider,
    region: region
)
let client = AWSRekognition.RekognitionClient(config: config)
```

All the fields in the `RekognitionClientConfiguration` are optional so you only need to specify what you want to customize. This example assumes that you have a particular or custom credential identity resolver. If you don't you can also omit that line and use the standard methods of resolving AWS credentials (see [here](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain) for more info).

**Comment by oanav21** [comment]
It worked. Thank you so much!
