### ISSUE TITLE
Epic: Make smithy-swift a stand alone product

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#186]
Description located here:
https://github.com/awslabs/smithy-swift/pull/243#discussion_r647018793

By making smithy-swift a stand alone product, the following classes need to get moved over:
xml, json, ec2, aws query classes to aws-sdk-swift
(however, -- i suspect there are more classes that also need to get moved over)

*internal id*: 178442037

**Comment by wooj2** [comment]
Moved aws query over here:
https://github.com/awslabs/smithy-swift/pull/334
https://github.com/awslabs/aws-sdk-swift/pull/384/files

**Comment by wooj2** [comment]
Lets do this when we are required to use smithy-swift as a stand alone product -- however, i suspect there are more classes than just these that need to be moved over, so this will eventually get converted into a larger task (which contains multiple tickets).

**Comment by sichanyoo** [comment]
Closing this ticket now because concrete work defined for moving AWS protocol things to aws-sdk-swift is complete, and because making smithy-swift a standalone project will be revisited based on customer demand.
