### ISSUE TITLE
usability enhancements for all optional inputs

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#192]
This task would be to look into improving usability of operations where we generate a synthetic input with all optional fields such that we could go from:
```
func foo(input: FooRequest, completion: (Result<FooResponse, FooError>) -> Void) ```

to either:
```
func foo(input: FooRequest? = nil, , completion: (Result<FooResponse, FooError>) -> Void)

OR

func foo(input: FooRequest = FooRequest(), completion: (Result<FooResponse, FooError>) -> Void)
```

which would allow customers to call it as:
```
client.foo() // instead of client.foo(input: FooRequest())
```

We need to understand how safe this actually is and if there are any "gotchas". Would we do this for all requests that have all optional fields? Is it _really_ guaranteed that a service team never adds `@required` somewhere down the road?

see also: https://quip-amazon.com/7C7jARMeOD6H/AWS-Kotlin-SDK-Service-Client-Design#AMY9CAN4eab


*internal id*: 177196246

**Comment by kneekey23** [comment]
This would be a breaking change if an input ever added a member so closing this for now.
