### ISSUE TITLE
Specify locale for case conversions 

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#193]
case conversion without specifying locale can vary based on the locale of the machine executing the code.  Conversion functions should specify the proper locale such that behavior is consistent regardless of locale.

See https://github.com/Kotlin/KEEP/blob/master/proposals/stdlib/locale-agnostic-string-conversions.md

A quick check to Smithy's source code yields that locale is always specified, so the scope of this is specific to SDKs that call case conversions explicitly, not those that call Smithy-based methods.

*internal id*: 176991541

**Comment by sichanyoo** [comment]
Moved to 2170
