### ISSUE TITLE
EC2 Custom Retry Delays

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#204]
ModifyNetworkInterfaceAttribute and AssignPrivateIpAddresses both require custom retry configuration: aws/aws-sdk-go@a25e309

*internal id*: 176722183

**Comment by jbelkins** [comment]
I spoke to the Smithy team about this.  Here is their take on this customization:

> We already provide this customization in other SDKs. For consistency I think we should provide it in Swift as well if possible even though it is not ideal. Im not sure we have a great way to model this in smithy currently.

**Comment by jbelkins** [comment]
https://github.com/awslabs/smithy-rs/issues/132

Rust team previously determined that this customization is superseded by Smithy standard retry.  Further, I could find no evidence that any SDK other than Go has implemented it.

@smivij Closing this ticket accordingly.
