### ISSUE TITLE
Route53 Sanitize URL's for all requests

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#213]
replace all \/%2F\w+%2F with / for all requests:
aws/aws-sdk-go@072d128

*internal id*: 176722144

**Comment by jbelkins** [comment]
Besides the Go commit linked in the description, here are more recent implementations of this mod:

- https://github.com/awslabs/aws-sdk-kotlin/pull/655 (Kotlin SDK)
- https://github.com/awslabs/smithy-rs/pull/999 (Rust SDK)

Here's a ticket from a different SDK which sorta discusses the reason for this fix:
- https://github.com/awslabs/aws-sdk-rust/issues/344

**Comment by jbelkins** [comment]
This PR was already merged in aws-sdk-swift:

https://github.com/awslabs/aws-sdk-swift/pull/521

Closing this issue as done.
