### ISSUE TITLE
DDB crc32 checksum

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#219]
Customization required for DDB which has crc32 checksum validation as an option.

TODO - link to spec/sep/?. Russell has more info I think. 

*internal id*: 176722107

**Comment by ganeshnj** [comment]
Rust decided not do this. Confirmed with @rcoh. Removing GA milestone.

**Comment by sichanyoo** [comment]
Checksum validation behavior is outlined in flexible checksum V2 SEP + DynamoDB model does not have CRC32 or checksum mentioned anywhere. This is most likely an outdated ticket. Closing it now.
