### ISSUE TITLE
Triage FIXME and TODO comments in smithy-swift and aws-sdk-swift

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#234]
The existing sources should be grepped for remaining FIXME and TODOs in code.  For actual issues that should be addressed before GA: specific tickets should be created and the work should get done.  For comments that no longer seem valid or were asperational, they should be removed.

*internal id*: 176321785

**Comment by sichanyoo** [comment]
Most of TODO has been addressed in this related ticket https://github.com/awslabs/aws-sdk-swift/issues/710. FIXME portion is moved to 2172.
