### ISSUE TITLE
SSO Credential Provider

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#236]
/seps/accepted/shared/sso-provider/
/seps/accepted/shared/sso-login-flow/

*internal id*: 174915617

**Comment by benkehoe** [comment]
What's the meaning of the paths in the comment above? Can I find them somewhere?

**Comment by richardhboyd** [comment]
You can't find them. They're a mechanism we use to align feedback we get from multiple places.

**Comment by benkehoe** [comment]
So how am I supposed to have any idea what this or any other ticket on this repo means?

**Comment by ganeshnj** [comment]
CRT bindings won't be available mid feb, we have to re-prioritize it.

**Comment by smivij** [comment]
Changing priority to 2 as per discussion with Rust and Kotlin

**Comment by smivij** [comment]
CRT changes in [SSO Credential Provider#95](https://github.com/awslabs/aws-crt-swift/issues/95)

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.24.0
