### ISSUE TITLE
RDS Auth Token

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#242]
SEP: /seps/accepted/shared/rds-sdk-1574/

*internal id*: 174915587

**Comment by smivij** [comment]
Changing priority based on feature matrix, this sep is marked as "may" for GA importance for new SDKs .

**Comment by alteredtech** [comment]
Is there somewhere I could track the progress of this? Currently building out an internal tool at my company where this is needed. I tried to look at SOTO but it does not seem like they have the feature either.

**Comment by sichanyoo** [comment]
Moved to internal ticket 2173. 

Hello @alteredtech, when work for this gets picked up and is completed, we'll let you know, thank you.

**Comment by sichanyoo** [comment]
@alteredtech This feature has been shipped with [v1.0.70](https://github.com/awslabs/aws-sdk-swift/releases/tag/1.0.70) of the AWS Swift SDK!
