### ISSUE TITLE
Shareable HTTP Client - Swift

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#246]
Consider support for the ability to share HTTP client across service clients. The V2 Java SDK has this capability and is something we should consider.

Needs a bit of design on how to expose it and deal with any differences between the two modes.

*internal id*: 173408455

**Comment by sichanyoo** [comment]
Multiple services can share a single HTTP client by setting [`config.httpClientEngine`](https://github.com/awslabs/aws-sdk-swift/blob/9c9eb62b02496502150c5647d21540f48a7cad29/Sources/Services/AWSS3/Sources/AWSS3/S3Client.swift#L146) with a single instance of client engine for multiple services, which is the underlying handler for [`client: SdkHttpClient`](https://github.com/awslabs/aws-sdk-swift/blob/9c9eb62b02496502150c5647d21540f48a7cad29/Sources/Services/AWSS3/Sources/AWSS3/S3Client.swift#L84).

Closing ticket now.
