### ISSUE TITLE
[ECD 4/5] Private Feature Repo Strategy

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#282]
Create a strategy to work on confidential feature customizations from services or anything that is not public information. We need a solution that meets the following requirements:
1. Prevents accidental code publishing
2. Prevents anyone from being able to merge to main
3. Able to develop in private branches for feature customization
4. Able to remove access from a contributor to that private branch if person leaves before it's merged to main.

**Comment by smivij** [comment]
Reference - zE0aAB0hyuDQ/Private-Feature-Repo-Strategy
