### ISSUE TITLE
Update CRT CI to build up downstream consumers.

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#289]
aws-crt-swift CI needs to build downstream consumers before merging in order to avoid breaking CI in aws-sdk-swift and smithy-swift.

**Comment by ganeshnj** [comment]
Should look into owning the CI end to end than using CRT version of CI.

**Comment by jbelkins** [comment]
Closing since aws-crt-swift is now managed separately from the SDK projects (i.e by CRT team).
