### ISSUE TITLE
Execution Interceptors

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#307]
We need to design how to offer the ability for a customer to add middlewares to the stack to do things like append to the User Agent or add a header to the request. Go SDK has examples of this.

**Acceptance criteria**
* Build a hello world app that adds a unique piece of middleware to each step, and verify proper execution of each of the custom middlewares owned by the hello world app.

**Comment by ganeshnj** [comment]
This is part of reference arch and once the design is approved. We can implement this.

**Comment by smivij** [comment]
https://quip-amazon.com/g3DoAzTyXlo6/Smithy-Interceptors

**Comment by sichanyoo** [comment]
Related issue: https://github.com/awslabs/aws-sdk-swift/issues/1130
The temporary fix for Amplify team should be scrapped as part of SRA interceptor implementation.

**Comment by dayaffe** [comment]
PR [#593](https://github.com/smithy-lang/smithy-swift/pull/593) in smithy-swift should be reverted when SRA Interceptors is implemented.
