### ISSUE TITLE
detect aws region from system properties 

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#318]
Detect region from `aws.region` system property.
1.  Determine interface for customers to use an xcconfig file (and/or plist) within a bundle 
2.  Support for like alpha/beta/gamma/prod environments 
3.  Setup dev environment w/ region resolver

**Comment by wooj2** [comment]
This should add the ability to grab a key of AWS_REGION from a bundle - or overridable if someone decides to use a different bundle (or key)

https://github.com/awslabs/aws-sdk-swift/pull/479
