### ISSUE TITLE
AssumeRoleWithWebIdentity should specify no auth in model 

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#335]
## Description

See quip (df7bAHHjCZBf/AssumeRoleWithWebIdentity-investigation) but in essence AssumeRoleWithWebIdentity is incorrectly modeled by specifying that auth is optional. In reality this operation requires/uses no authentication so the model should be updated to specify this.

## Observed Behavior

auth is used when calling AssumeRoleWithWebIdentity
## Expected Behavior

no auth is used when calling AssumeRoleWithWebIdentity

**Comment by kneekey23** [comment]
Consider implementing a customization in the meantime to work around this: https://github.com/awslabs/smithy-rs/blob/7b451c573d1f6d781f6cfa3b731a241eb1b15295/aws/sdk-codegen/src/main/kotlin/software/amazon/smithy/rustsdk/customize/auth/DisabledAuthDecorator.kt#L18

**Comment by wooj2** [comment]
https://github.com/awslabs/aws-sdk-swift/pull/490
