### ISSUE TITLE
EC2 Error Modeling

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#336]
## Description

The Ec2 smithy model does not specify errors for operations, however the service does return error codes. These error codes do not map to defined shapes. As it stands, errors returned from Ec2 throw UnknownServiceErrorException. There is a page https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors which defines errors that may apply to an given operation. We may want to do a model mutation to model these errors or perhaps model one specific error to prevent customers having to deal with UnknownServiceErrorException.

Reference from Kotlin: https://github.com/awslabs/aws-sdk-kotlin/issues/278

**Comment by jbelkins** [comment]
This is an excellent one to take on now that the error overhaul is complete.

**Comment by jbelkins** [comment]
From Smithy team on this customization:

> I am not sure we should pursue this. We have a good way to model errors in smithy and while we do customize some models upstream Im not sure SDKs should be in the business of defining these errors based on informal specs. It seems like a way to get a mismatch later on. I think in this case it is much better if the EC2 model just be fixed to model the errors they already throw.

They also pointed out that our "unknown error" type can still be used to catch these errors.

**Comment by smivij** [comment]
Lets check how new SDKs have handled this and keep it consistent.

**Comment by sichanyoo** [comment]
Closing ticket now, as responsibility lies with EC2 service team, and customizing error behavior in SDK side is not a durable solution.
