### ISSUE TITLE
SDK user agent should vary depending on internal/external origin of artifacts

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#337]
## Description

For tracking purposes SDKs vary their user agents depending on if the SDK was consumed from a public source (like MavenCentral) or from an internal build system. We'll need to follow suit in order to provide uniform metrics data.

Reference: https://github.com/awslabs/aws-sdk-kotlin/issues/260

**Comment by ganeshnj** [comment]
Currently we have only one way to distribute ie GitHub. Once we have more ways to distribute the SDK, we will check.
