### ISSUE TITLE
S3 Private Link Customization

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

SEP: /seps/accepted/shared/s3-privatelink.md

**Comment by ganeshnj** [comment]
endpoints 2.0 is out in 0.4.0
