### ISSUE TITLE
S3 Outposts / S3 Control Outposts customization 

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#344]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

S3 Control SEP: /seps/accepted/shared/s3-outposts-control.md
S3 SEP: /seps/accepted/shared/s3-outposts.md

**Comment by ganeshnj** [comment]
0.4.0 out with endpoints 2.0. Closing.
