### ISSUE TITLE
AWS ARN Parser

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Implement an ARN parser and supporting classes.

Consider how this will integrate with the various endpoint customizations (e.g. S3 virtual host, Westeros, MRAP) etc which is the primary use case for this.

**Comment by ganeshnj** [comment]
This is covered with by endpoints 2.0 https://github.com/awslabs/aws-sdk-swift/issues/624

**Comment by sichanyoo** [comment]
Closing ticket, as it's done in endpoints 2.0.
