### ISSUE TITLE
AWS Configuration File Support

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

The CRT has this implemented the work according to the configuration sep already here: https://github.com/awslabs/aws-c-auth/blob/main/include/aws/auth/private/aws_profile.h#L59

They need to expose this which they said they would and we need to bind it and expose it up the stack. However its unclear if more work is required here or what else is needed to get full compliance with the configuration file sep.
SEP: seps/accepted/shared/configuration-file.md

**Comment by wooj2** [comment]
Dependent on:
https://github.com/awslabs/aws-c-io/pull/429
https://github.com/awslabs/aws-c-common/pull/841
