### ISSUE TITLE
extend user agent metadata

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

#141 implemented most of the SEP but we left a few things todo including:

feat-metadata        = "ft/" name ["/" version] *(RWS additional-metadata)
config-metadata      = "cfg/" config "/" name
framework-metadata   = "lib/" name ["/" version] *(RWS additional-metadata)
appId                = "app/" name
We need to provide a way that customers can extend this metadata (e.g. so someone like amplify can set lib/amplify/VERSION) and we need to finish the implementation by detecting features and configuration settings (SEP calls out examples of these).

**Comment by wooj2** [comment]
https://github.com/awslabs/aws-sdk-swift/pull/494

**Comment by smivij** [comment]
SEP - /seps/accepted/shared/sdk-user-agent-header.md

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.24.0
