### ISSUE TITLE
S3: SSECustomerKey and CopySourceSSECustomerKey should be blob shapes

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Customization to make sure they are generated as blob shapes

**Comment by ganeshnj** [comment]
models states both are string.

https://github.com/awslabs/aws-sdk-swift/blob/3d9ec92fc8d1c29f0fb76fac6220212a869ecb76/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L29002-L29011

need more context here. Closing.
