### ISSUE TITLE
Extensible Credential Providers

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

See /seps/accepted/shared/extensible-creds.md
 May be provided by CRT

**Comment by ganeshnj** [comment]
There is reference arch spec for creds providers which must be followed.

**Comment by smivij** [comment]
Changed to priority 2 based on feature matrix

**Comment by epau** [comment]
Most of the work is in CRT https://github.com/awslabs/aws-crt-swift/issues/177

**Comment by jbelkins** [comment]
Duplicate of #1073
