### ISSUE TITLE
SigV4a Signer

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Investigate the sigv4a work done by the CRT team and bind any necessary new calls that they implemented. Expose the signer upwards and make some determination about when to use sigv4 vs sigv4a because sigv4a takes longer and will have performance effects.

Acceptance criteria:
* Expose CRT implemented sigv4a signer to swift
* Investigate whether or not smithy denotes when to use sigv4a or not.
  * implement code generators appropriately

**Comment by ganeshnj** [comment]
Adding more to acceptance criteria
- MRAP must work (https://github.com/awslabs/aws-sdk-swift/blob/f296069d1b3910c196bb6b7a55903cb18af577a9/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L11219-L11236)
