### ISSUE TITLE
Chunk encoding support

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#356]
## Describe the Feature

SEP: `seps/accepted/shared/requires-length-trait.md`
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/aws-sdk-swift/issues/1177
```

**Comment by smivij** [comment]
Need to review priority as this is marked as "must" for GA in feature matrix

**Comment by smivij** [comment]
Priority 3 seems fine as discussed with Rust.

**Comment by smivij** [comment]
SEP : dynamic-payload-trait.md
Updated priority as this needs to be implemented fully to support flexible checksums for streaming scenarios.

**Comment by dayaffe** [comment]
Will review the related SEPs during Friday review meeting. After reviewing the SEPs we will fill out this issue with relevant details. 

SEP : dynamic-payload-trait.md (Not Accepted)
SEP: seps/accepted/shared/requires-length-trait.md (Accepted)
