### ISSUE TITLE
S3 PutObject Content Type Issue

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#364]
## Description

Documented by Kotlin here: https://github.com/awslabs/aws-sdk-kotlin/issues/193

**Comment by wooj2** [comment]
We've added two changes to address this.
1.  ContentTypeMiddleware is now changed to:
```
   if !input.builder.headers.exists(name: "Content-Type") {
            input.builder.withHeader(name: "Content-Type", value: contentType)
        }
```
2. We are applying `.after` to `ContentTypeMiddlware` in the chain of middlewares

The above approach is somewhat brittle in that a previous value must not have been set in order for this code to execute.  This is something in code generation that is not yet strongly modeled, and we'll need to revisit this when we go to figure out how middlewares should play nicely with each other.

Closing for now, with the intent of opening another ticket to address this broader issue.
