### ISSUE TITLE
S3 Size Member should be a long

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#380]
## Description

more info here: https://github.com/awslabs/aws-sdk-kotlin/issues/309

**Comment by kneekey23** [comment]
This has been fixed in the model. In order to close this ticket, run the update models script and merge in the new models.

**Comment by wooj2** [comment]
Looking at the model:
https://raw.githubusercontent.com/awslabs/aws-sdk-swift/main/codegen/sdk-codegen/aws-models/s3.2006-03-01.json

On line 12119, it shows:
```
 12118	        "com.amazonaws.s3#Size": {
 12119	            "type": "long"
 12120	        },
```

I'm pretty sure this ticket is good to go, but don't have any way to verify that this is the intent of the ticket.  Assigning back to @kneekey23 to verify fix.

**Comment by kneekey23** [comment]
Seems like we already updated these models then and took in the new changes here. This is fixed.
