### ISSUE TITLE
Expose sigv4 signer

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#388]
## Describe the Feature
Given a URL, method (potentially more inputs/config parameters pending investigation), expose a function in the AWSClientRuntime to allow users to use the Sigv4 signer, to generate a presigned request (or perhaps a presigned URL, pending design/discussion/investigation)

Additional requirements:
* Give option to double URI encode and additional, tunable configuration parameters

Essentially, we need a replacement and improvements on providing functionality for:
https://github.com/aws-amplify/aws-sdk-ios/blob/e5c21d5b8b042e55e51f8f184a4e06915648d285/AWSCore/Authentication/AWSSignature.m#L407

## Proposed Solution
* Pending investigation/examples

- [x] I may be able to implement this feature request

**Comment by ameter** [comment]
Example use-cases...

As part of a fix to improve SigV4Signer support for non-s3 use cases in aws-sdk-ios, I wrote a couple of additional [test cases](https://github.com/aws-amplify/aws-sdk-ios/blob/fix/signatureV4Encoding/AWSCoreUnitTests/SigV4Tests/SigV4TestCases.swift) to validate the signature with special characters (single encoding the path before signing for s3 and double encoding for everything else).

Specifically, that last two test cases ("get-s3-specialchars" and "get-specialchars") address handling of special characters.
