### ISSUE TITLE
README.md needs updating after changes in 0.0.9

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#405]
## Description

Due to "AWS" being prepended to the names of things in the update, the code example in the readme is out of date and needs to be updated to work again.

## Context

Following the readme currently will result in a broken test program, which is not a good introduction to the SDK.

## Environment

swift-driver version: 1.26 Apple Swift version 5.5 (swiftlang-1300.0.20.104 clang-1300.0.21.1)
Target: x86_64-apple-macosx11.0
macOS 11.5.2

## Reproduction Steps
Type the example from the readme into your favorite editor. Save and build. Errors will ensue.

## Observed Behavior

Errors instead of a working example.

## Expected Behavior

A correctly functional test program should be generated.

## Possible Solution

No idea. I've been trying to get my project updated to build again without luck.

**Comment by kneekey23** [comment]
hi @shepazon it would be great if you could submit a PR updating it! otherwise I will try to get to this later in the week.
