### ISSUE TITLE
async functions should check they can import Concurrency

### ISSUE THREAD

**Issue by 0xTim** [awslabs/aws-sdk-swift#441]
Currently anyone trying to build the SDK on Xcode 13 release for macOS cannot because there's no Concurrency runtime provided. The check `#if swift(>=5.5)` should be changed to

```swift
#if compiler(>=5.5) && canImport(_Concurrency)
```

This will ensure everyone can build no matter their Swift version or OS

**Comment by kneekey23** [comment]
hi @0xTim thanks for reporting this issue! PR open already for it and will be merged/released soon!
