### ISSUE TITLE
Eliminate warnings in generated code (if needed)

### ISSUE THREAD

**Issue by wooj2** [awslabs/aws-sdk-swift#484]
We should prioritize most popular services over less popular ones:
* S3
* cognito
* rekognition
* Apigateway
* dynamodb
* lambda
* sns
* sqs

Task:
1.  Create a test project and add in one of the a-forementioned modules
2. Figure out what warnings there are (hopefully no errors)
3. Update code generation to avoid warnings (if any)

Success critiera:
Zero warnings in the aforementioned services -- that being said ,this task can be broken up into many pieces if needed depending on how invasive the changes are.

**Comment by kneekey23** [comment]
Zero warnings ignoring any warnings triggered by the deprecated attribute :)

**Comment by wooj2** [comment]
S3:
![Screen Shot 2021-11-05 at 1 30 35 PM](https://user-images.githubusercontent.com/1911939/140574676-336f5fd6-2da5-4f57-a9ec-1824df8c471a.png)

**Comment by wooj2** [comment]
CognitoIdentity:
lgtm!

**Comment by wooj2** [comment]
lambda
![Screen Shot 2021-11-05 at 1 44 29 PM](https://user-images.githubusercontent.com/1911939/140576283-dac6fc52-467a-4c2b-8da8-2457cda908c9.png)
:

**Comment by wooj2** [comment]
Other than deprecated warnings, looks like we are good to go.  resolving!
