### ISSUE TITLE
API reference documentation is missing all the async functions

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#498]
## Description
The generated API reference for the Swift SDK is missing all the async functions; that is, the functions found in the `foo+async.swift` files.

## Context
For example, open the [documentation for IAM](https://awslabs.github.io/aws-sdk-swift/reference/0.x/AWSIAM). First, the Async file isn't separately listed here, which is a good thing since you'd want it to all be together. But if you then go into the `IamClient`  class and look for, say, getUser(), you find that it's only listed once, and only for the completion handler implementation.

## Environment

* AWS Swift SDK version used: 0.0.16
* Operating System and version (iOS/macOS/Linux): macOS
* Xcode version (if applicable): 13.2 beta 2

## Reproduction Steps
See above.

## Observed Behavior
See above.

## Expected Behavior
Every function that has both completion handler and async versions available should be listed twice across the SDK reference; once for the completion handler version and once for the async version.

## Possible Solution
See above.

**Comment by wooj2** [comment]
We will need to re-generate the documentation after the following PRs get pushed in:
https://github.com/awslabs/smithy-swift/pull/389
https://github.com/awslabs/aws-sdk-swift/pull/497

**Comment by bdruth** [comment]
> We will need to re-generate the documentation after the following PRs get pushed in:
> [awslabs/smithy-swift#389](https://github.com/awslabs/smithy-swift/pull/389)
> #497

It looks like these were merged, is this ready now? From what I can see, the docs are still showing completion handlers, but I may be mistaken as I'm new to using the AWS SDK from Swift and to Swift in general.

**Comment by ganeshnj** [comment]
https://awslabs.github.io/aws-sdk-swift/reference/0.x/AWSIAM/IamClient still shows methods with completion handler. We must update/regenerated the docs website.

**Comment by shepazon** [comment]
Yes, that would be useful. If y'all could try to find time to push up an update to the reference, it would be very helpful. I'm still in the middle of a revamp of the guide content and trying to find a good spot to break off and push a guide update, which is badly needed.

**Comment by epau** [comment]
Blocked until we figure out our next steps regarding generating docs.

**Comment by smivij** [comment]
Fixed now
