### ISSUE TITLE
Enum `SQS.QueueAttributeName` is missing the case `SqsManagedSseEnabled`

### ISSUE THREAD

**Issue by adam-fowler** [awslabs/aws-sdk-swift#500]
## Description
The enum `SQS.QueueAttributeName` is missing the undocumented case `SqsManagedSseEnabled`. 

## Context

Hi Nicki,

Another Smithy model issue. I'll keep putting them up here if you want. This time it is an enum case missing. If the case doesn't exist then decoding of the enum fails.

This is the equivalent Soto code that causes the decode fail. I imagine aws-sdk-swift code would be similar
```swift
let request = SQS.GetQueueAttributesRequest(attributeNames: [.all], queueUrl: queueUrl)
let response = try await sqs.getQueueAttributes(request)
```

**Comment by kneekey23** [comment]
hi @adam-fowler thanks for reporting this! please continue to do so! Will pass this on the smithy folks, service team to see if we can correct it at the model level and if not we'll add a codegen customization.

**Comment by adam-fowler** [comment]
@kneekey23 they've already fixed it

**Comment by kneekey23** [comment]
yep I just found the fix, need to update our models and do another release @adam-fowler. we'll update our models today and then do another release sometime next week most likely.
