### ISSUE TITLE
Can it be used in the ObjC project

### ISSUE THREAD

**Issue by SUWW** [awslabs/aws-sdk-swift#517]
Can it support ObjC? Is there any mention of how to use ObjC in the document? Or is there a demo to explain. thanks

**Comment by kneekey23** [comment]
No sorry we don't plan to support objc as of now. There is an objc sdk that already exists, you can find it here: https://github.com/aws-amplify/aws-sdk-ios

**Comment by kneekey23** [comment]
Closing issue, feel free to re-open if needed
