### ISSUE TITLE
SDK interferes with application logging

### ISSUE THREAD

**Issue by tachyonics** [awslabs/aws-sdk-swift#518]
## Description
So far I have seen two scenarios-
1. Where an application depends on the sdk but doesn't instantiate any clients: The application's already configured `LogHandler` will be used but all log statements will be recorded as occurring at Logging/SwiftLog+LogAgent.swift:36 (due to this statement not passing the source, function and line - https://github.com/awslabs/smithy-swift/blob/main/Packages/ClientRuntime/Sources/Logging/SwiftLog%2BLogAgent.swift#L36-L39).
2. Where an application instantiates at least one client: Application logging uses `StreamLogHandler` rather than any application configured `LogHandler`. This has the potential of changing the formatting of all application logs and/or not passing logs to the correct backend. (I assume issue 1 also happens here but `StreamLogHandler` doesn't emit the location so I can't confirm)

## Context
As specified in the README of swift-log (https://github.com/apple/swift-log/blob/main/README.md), applications should be free to select the `LogHandler` implementation that meets their requirements. Currently the SDK appears to hard-code using `StreamLogHandler` for its clients which means all application logging is using this handler regardless of what the application has configured.  

## Environment

* AWS Swift SDK version used: 0.1.0
* Operating System and version (iOS/macOS/Linux): Amazon Linux 2
* Xcode version (if applicable): 
* Swift compiler version (if applicable): 5.5.2
* Swift Tools version (if applicable): 5.5

## Reproduction Steps
1. Create an application that bootstraps the LoggingSystem with a custom `LogHandler`
2. Initialise a client from the SDK
3. Emit a log from the application

## Observed Behavior
The log will be emitted using the `StreamLogHandler`

## Expected Behavior
The log should be emitted using the application-configured LogHandler and reporting the correct code location.

**Comment by wooj2** [comment]
I was able to reproduce this.  Consider the following example:
```
let log = Logger(label:"test logger")
log.info("something")

LoggingSystem.bootstrap { label in
    return MyTestStandardErrorLogger(minimumLogLevel: .info)
}

let log2 = Logger(label:"test logger2")
log2.info("something2")
```

Expected behavior is:
```
2022-01-13T10:25:04-0800 info test logger : something
/Users/wooj/workspaces/testLogging/Sources/testLogging/main.swift:102:testLogging [INFO] something2
```

Observed behavior is:
```
2022-01-13T10:25:33-0800 info test logger : something
/Users/wooj/Projects/Amplify/SwiftSDK_Releases/smithy-swift/Packages/ClientRuntime/Sources/Logging/SwiftLog+LogAgent.swift:36:log(level:message:metadata:source:file:function:line:) [INFO] something2
```

Notice that the second log statement is incorrectly printing the file attached to `SwiftLog+LogAgent.swift` thereby loosing the line where where the caller called the `log` statement from.
