### ISSUE TITLE
Failed to get authorization token without provide a repositoryId

### ISSUE THREAD

**Issue by portellaa** [awslabs/aws-sdk-swift#524]
## Description
I found that when i try to use the method to get an authorization token to access an ECR, it doesn't accept empty values for the `repositoryIDs`, although the method signature allows it, since the parameter is optional.

Also the documentation says that this is deprecated, that there is no need to specify this value.
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_GetAuthorizationToken.html

Another thing, if i provide a random 12-digit value, it works.

It probably is not a bug from the SDK, but the cli works properly, so...

## Context
I'm trying to use the method `getAuthorizationToken(input: GetAuthorizationTokenInput)` in the `ECRClient`. 
I already manage to make it working, by specifying a random value, although i think either the documentation or the implementation should be fixed.

I was doing the following code and it was not working:

```swift
let tokenResponse = try await ecrClient.getAuthorizationToken(input: .init())

// or basically

let tokenResponse = try await EcrClient().getAuthorizationToken(input: .init())
```

and the error i'm getting:

```
2022-01-12 20:48:27.766617+0000 Run[59084:2812195] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=59084
2022-01-12 20:48:27.766967+0000 Run[59084:2812195] SecTaskCopyDebugDescription: Run[59084]/0#-1 LF=0
[ WARNING ] service(AWSECR.GetAuthorizationTokenOutputError.unknown(AWSClientRuntime.UnknownAWSHttpServiceError(_isThrottling: false, _statusCode: Optional(http_status_400), _headers: Optional(Content-Type: application/x-amz-json-1.1, 
x-amzn-RequestId: 4834ee34-444a-42b1-a12e-588a97986fb4, 
Date: Wed, 12 Jan 2022 20:48:27 GMT, 
Content-Length: 35), _message: nil, _requestID: Optional("4834ee34-444a-42b1-a12e-588a97986fb4"), _retryable: false, _type: ClientRuntime.ErrorType.unknown)), 
Status Code: http_status_400 
 Content-Type: application/x-amz-json-1.1, 
Date: Wed, 12 Jan 2022 20:48:27 GMT, 
Content-Length: 35, 
x-amzn-RequestId: 4834ee34-444a-42b1-a12e-588a97986fb4) [request-id: 5CC0E3BD-A5E6-4D8F-8BD3-BE4E425223D5]
```

Instead, if i do:

```swift
private extension GetAuthorizationTokenInput {
  static let empty = Self(registryIds: ["000000000000"])
}

let tokenResponse = try await ecrClient.getAuthorizationToken(input: .empty)
// OR
let tokenResponse = try await EcrClient().getAuthorizationToken(input: .empty)
```

it works as intended.

## Environment

* AWS Swift SDK version used: 0.1.1
* Operating System and version (iOS/macOS/Linux): macOS 12 and Linux
* Xcode version (if applicable):
* Swift compiler version (if applicable): 5.5
* Swift Tools version (if applicable): 5.5

## Reproduction Steps
```swift
let tokenResponse = try await ecrClient.getAuthorizationToken(input: .init())
```

## Observed Behavior
Receive an error instead of the result

## Expected Behavior
Receive a AuthorizationTokenResponse

## Possible Solution
Use a random 12-digit value

**Comment by kneekey23** [comment]
This will be fixed by https://github.com/awslabs/aws-sdk-swift/pull/550
