### ISSUE TITLE
macOS target can't compile AWSS3

### ISSUE THREAD

**Issue by divan84** [awslabs/aws-sdk-swift#527]
## Description
I tried to build the AWSS3 module for a macOS target but can't compile it

## Environment
* AWS Swift SDK version used: 0.1.1
* Operating System and version (iOS/macOS/Linux): macOS 12.1
* Xcode version (if applicable):  13.2.1
* Swift compiler version (if applicable): default in XCode 13.2.1

## Reproduction Steps
I added the AWSS3 Module to my target and wanted to compile the project and the following error occurs in AWSS3/models/Models.swift at Line 21479 and Line 21484 - Initializer for conditional binding must have Optional type, not 'Int'

**Comment by bharatn161** [comment]
I also get the same issue!

**Comment by kneekey23** [comment]
Fixed this in 0.1.2 :)
