### ISSUE TITLE
S3Client().putObject() never returns or throws when fed a stream over about 5k of data.

### ISSUE THREAD

**Issue by tetraoxygen** [awslabs/aws-sdk-swift#531]
## Description
If I pass in a ByteStream generated from a Data object over about 5k in size to S3Client().putObject(), both the `async`/`await` and the completion-handler-based versions of the function never complete (the completion handler is never called, so the async/await continuation also never returns). 

## Context
I need to put files over 5K in S3. I can't currently do that with this SDK. 

## Environment

* AWS Swift SDK version used: 0.1.2
* Operating System and version (iOS/macOS/Linux): macOS 12.1
* Xcode version (if applicable): 13.2.1
* Swift compiler version (if applicable): 5.5.2
* Swift Tools version (if applicable): swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.2 clang-1300.0.29.30)

## Reproduction Steps
```
let defaultConfig = try DefaultSDKRuntimeConfiguration("S3Client", clientLogMode: .requestAndResponse)
let s3Config = try S3Client.S3ClientConfiguration(runtimeConfig: defaultConfig)
s3Config.region = "us-west-2"
let s3 = S3Client(config: s3Config)

let body = ByteStream.from(data: dataOver5KInSize)

let result = try await s3.putObject(input: PutObjectInput(body: body, bucket: "allotrope-test-3", contentType: "raw", key: "testing2", metadata: ["foo": "bar"]))

print(result)
```

## Observed Behavior
The function just never returns, and the task never hits any breakpoint set beyond the putObject call.

## Expected Behavior
The function should either throw an error or return.

**Comment by thbaja** [comment]
I'm experiencing the same thing when trying to upload an image. To me it seems the limit is around **4k** though.

The app hangs with CPU going to 100%. If I pause execution it seems it gets stuck when attempting to sign the request. More specifically in `commoncrypto_sha256.c` line 55, that calls MacOS's `CC_SHA256_Update`

I'm doing something along the lines of:
```swift
if let tiffData =  image.tiffRepresentation,
   let rep = NSBitmapImageRep(data: tiffData),
   let imgData = rep.representation(using: .png, properties: [:]) {

    let body = ByteStream.from(data: imgData)
    let objectInput = PutObjectInput(body: body, bucket: bucketNAme, key: imageName)
    _ = try await s3.putObject(input: objectInput)
}
```

**Comment by kneekey23** [comment]
can you guys now try this again with version 0.2.0? we had some threading issues with the previous versions and I am wondering if this is now fixed with those being gone.

**Comment by thbaja** [comment]
It doesn't block the rest of the app anymore, but CPU still goes to 100% and it doesn't upload the image. It seems stuck at the same place as previously described.
Around 4k seems to be the limit still.

**Comment by kneekey23** [comment]
Well some progress! okay investigating this now @thbaja

**Comment by kneekey23** [comment]
FYI got a fix for this. Will do a patch release with it tomorrow

**Comment by thbaja** [comment]
Wow, great! Looking forward to it.
Thanks for the quick turnaround (less than 24 hours since I joined in). Much appreciated! :)

**Comment by kneekey23** [comment]
@thbaja and @tetraoxygen patch release 0.2.1 was just released with the fix for this.
