### ISSUE TITLE
Unable to use AWS Amplify package and AWS SDK Swift package together in project

### ISSUE THREAD

**Issue by matthewchong44** [awslabs/aws-sdk-swift#547]
## Description
I am trying to utilize both the AWS Amplify package and the AWS SDK Swift package together in one project. However, when I try to add both these packages, I get errors along the lines of "multiple products named "Package Name" in :'aws-sdk-ios-spm', 'aws-sdk-swift'. 

## Context
I am trying to use both packages because I want my amplify application to communicate directly to DynamoDB rather than deploying through the Amplify Console. I ran into issues trying to deploy my data model and this is a possible alternative solution to the problem.

## Environment
* AWS Swift SDK version used: 0.2.0
* Operating System and version (iOS/macOS/Linux): macOS
* Xcode version (if applicable): 13.2.1

## Reproduction Steps

- Add Package "AWS Amplify" (https://github.com/aws-amplify/amplify-ios)
- Add Package "AWS SDK Swift" (https://github.com/awslabs/aws-sdk-swift)

## Observed Behavior
- I get errors along the lines of "multiple products named "Package Name" in :'aws-sdk-ios-spm', 'aws-sdk-swift'. 

## Expected Behavior
- Able to add both packages into one project.

**Comment by kneekey23** [comment]
@royjit have you seen this before also?

**Comment by royjit** [comment]
Yes, this is a known issue because Amplify internally uses the Objc AWS SDK. It has the same names for different packages as AWS Swift SDK. So using Amplify along with AWS Swift SDK causes naming conflicts.

**Comment by matthewchong44** [comment]
@royjit Is there a solution to this problem? If not, what steps should I take to still be able to communicate with DynamoDB through my Amplify project?

**Comment by royjit** [comment]
We are actively working on adding support for AWS Swift SDK in Amplify, will post an update here when I have more details to share.

For now, will you be able to use the `AWSDynamoDB` provided by [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios/tree/main/AWSDynamoDB)

**Comment by Janeha0825** [comment]
Hi,

I import the AWSDynamoDB provided by [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios/tree/main/AWSDynamoDB)  but it gave me an error  because that package doesn't have `ClientRuntime` and AWSClientRuntime. 
I was follow this [tutorial](https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/examples-ddb-tables.html
):
And it says it cannot find  `ClientRuntime` and `AWSClientRuntime`
If I comment out 
```
import ClientRuntime
import AWSClientRuntime
```
then I can not create an instance of `DynamoDbClient`

**Comment by kneekey23** [comment]
@Janeha0825 the `ClientRuntime` and `AWSClientRuntime` are used by the Swift SDK. the SDK you linked is the Objc SDK. are you trying to use both in the same project because that is what @royjit was explaining is not possible right now.

**Comment by kneekey23** [comment]
Closing this issue for the time being, please reopen if you are in fact using the AWS SDK for Swift and not the AWS SDK for iOS.
