### ISSUE TITLE
Docs built from package should merge extensions into base type

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#551]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Currently, when you build the documentation for a project using the SDK, the docs for classes and structures in the Swift SDK are missing all of the things defined in extensions. The extensions should be merged into the main class or struct, so that `SomeType` includes everything declared as `extension SomeType` when looked up in the documentation

- [ ] I may be able to implement this feature request

**Comment by jbelkins** [comment]
Fixed but pending publication of updated docs

**Comment by jbelkins** [comment]
Related to #757

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.32.0
