### ISSUE TITLE
Xcode 13.3 / Swift 5.6 build error

### ISSUE THREAD

**Issue by bryansum** [awslabs/aws-sdk-swift#557]
## Description

Xcode 13.3 can't build `aws-sdk-swift` correctly due to a predefined `error`:

<img width="1034" alt="Screen Shot 2022-03-15 at 10 55 42" src="https://user-images.githubusercontent.com/49369/158441376-4e0e65ff-1597-4652-9538-a869a982889e.png">

I'm assuming this just needs to be bumped to work.

## Environment

* AWS Swift SDK version used: 0.2.2
* Operating System and version (iOS/macOS/Linux): 12.2.1
* Xcode version (if applicable): Xcode 13.3
* Swift compiler version (if applicable): `swift 5.6`
* Swift Tools version (if applicable):

**Comment by atierian** [comment]
Thanks for opening this @bryansum.
This has been fixed in `0.2.3`. Let me know if you encounter any issues.
