### ISSUE TITLE
GetCallerIdentityInput missing public initialiser 

### ISSUE THREAD

**Issue by carltongibson** [awslabs/aws-sdk-swift#568]
## Description

Trying to initialise `GetCallerIdentityInput` raises an error: 

In schema-form: 

```
import AWSSTS

let inputObject = GetCallerIdentityInput()
```

The error: 

> 'GetCallerIdentityInput' initializer is inaccessible due to 'internal' protection level

This is the definition: 

```
public struct GetCallerIdentityInput: Swift.Equatable {

}
```

Contrast to (e.g.) IAM ListUsersInput:

```
public struct ListUsersInput: Swift.Equatable {
    ...

    public init (
        marker: Swift.String? = nil,
        maxItems: Swift.Int? = nil,
        pathPrefix: Swift.String? = nil
    )
    {
        self.marker = marker
        self.maxItems = maxItems
        self.pathPrefix = pathPrefix
    }
}

```

## Environment

* AWS Swift SDK version used: AWSSwiftSDK 0.2.3
* Operating System and version (iOS/macOS/Linux): macOS latest. 
* Xcode version (if applicable):
* Swift compiler version (if applicable):
* Swift Tools version (if applicable):

## Possible Solution

Add the empty initialiser? 🤔

```
public init () {}
```

**Comment by lukezsmith** [comment]
Hi, I'm also getting this error when trying to initialise `ListBucketsInput()` which has the definition: 
`public struct ListBucketsInput: Swift.Equatable {

}`
I'm using AWS Swift SDK v0.2.5 and macOS 12.4
