### ISSUE TITLE
Fix Xcode support by removing Packages.swift from AWSClientRuntime folder

### ISSUE THREAD

**Issue by brennanMKE** [awslabs/aws-sdk-swift#591]
When working in Xcode the contents of AWSClientRuntime are hidden because it contains `Package.swift`. The purpose of it is not known yet it does cause difficulties when working with this package.

**Comment by ganeshnj** [comment]
This is particularly annoying when trying to debug code from target application. Navigation and step through becomes harder.

**Comment by jbelkins** [comment]
This is fixed in release [0.3.0](https://github.com/awslabs/aws-sdk-swift/releases/tag/0.3.0).  Closing.
