### ISSUE TITLE
Throwing ClientRuntime.SdkError<AWSSQS.ReceiveMessageOutputError> error when there is no message in the queue. 

### ISSUE THREAD

**Issue by sadaf-behbahani** [awslabs/aws-sdk-swift#594]
## Description
I am trying to get SQS messages from a queue using `func receiveMessage(input: ReceiveMessageInput) async throws -> ReceiveMessageOutputResponse` from AWSSQS API. Whenever I have no message in the queue an error is thrown by the SDK instead of having an empty array of messages in the `ReceiveMessageOutputResponse` object. 

## Context
Trying to call sqs receiveMessage and each time there is no messages in the queue I catch an error which is inconvenient and confusing. 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/23311093/179774129-0617a3b2-6686-472b-b3c9-0fc5c475eb57.png">

more detailed error: 
`client(ClientRuntime.ClientError.retryError(Swift.DecodingError.typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Dictionary<String, Any> but found SingleKeyedBox instead.", underlyingError: nil))), nil)`

## Environment
* AWS Swift SDK version used: 0.2.5
* Operating System and version (iOS/macOS/Linux): macOS
* Xcode version (if applicable): 13.4.1 
* Swift-driver version: 1.45.2 Apple 
* Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
* Target: arm64-apple-macosx12.0

## Reproduction Steps
- Remove all the messages from your SQS queue 
- Call `receiveMessage(input: ReceiveMessageInput) async throws` from `AWSSQS` SDK 

## Observed Behavior
An error is thrown : 

`client(ClientRuntime.ClientError.retryError(Swift.DecodingError.typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Dictionary<String, Any> but found SingleKeyedBox instead.", underlyingError: nil))), nil)`

`ClientRuntime.SdkError<AWSSQS.ReceiveMessageOutputError> error 1.`

## Expected Behavior
No errors are thrown and the response contains an empty list of messages. 

## Possible Solution
I ll leave this to you ;)

**Comment by ChristopheBougere** [comment]
@atierian @ganeshnj any idea what's happening here?

**Comment by ganeshnj** [comment]
Thanks for reporting @sadaf-behbahani 

Any empty response  looks like 
```xml
<?xml version="1.0"?>
<ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
    <ReceiveMessageResult/>
    <ResponseMetadata>
        <RequestId>696fb008-b2ed-51d7-9824-eb84cb48ac18</RequestId>
    </ResponseMetadata>
</ReceiveMessageResponse>
```
[deserilization](https://github.com/awslabs/aws-sdk-swift/blob/0.2.6/release/AWSSQS/models/Models.swift#L3380-L3386) code always expect there exists message

```swift
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case messages = "Message"
    }

    public init (from decoder: Swift.Decoder) throws {
        let topLevelContainer = try decoder.container(keyedBy: ClientRuntime.Key.self)
        let containerValues = try topLevelContainer.nestedContainer(keyedBy: CodingKeys.self, forKey: ClientRuntime.Key("ReceiveMessageResult"))
...
```
this needs to be update to
```swift
        let containerValues = topLevelContainer.nestedContainerNonThrowable(keyedBy: CodingKeys2.self, forKey: Key("ReceiveMessageResult"))
        if let containerValues = containerValues {
...
```

**Comment by sichanyoo** [comment]
Closing ticket as we've seen no response from customer in 2 years since the fix.
