### ISSUE TITLE
S3 deleteObjects() throws exception in verbose mode when successful

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#602]
## Description
When calling S3's `deleteObjects()` method with the default value of the `quiet` flag (`false`), a successful deletion operation throws an exception as follows:

```
<EXPR>:0: error: BasicsTests.testDeleteObjects : threw error "client(ClientRuntime.ClientError.retryError(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "DeleteMarker", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "Deleted", intValue: nil), XMLKey(stringValue: "0", intValue: 0), XMLKey(stringValue: "0", intValue: 0), CodingKeys(stringValue: "DeleteMarker", intValue: nil)], debugDescription: "No attribute or element found for key CodingKeys(stringValue: \"DeleteMarker\", intValue: nil) (\"DeleteMarker\").", underlyingError: nil))), nil)"
```

In verbose mode (that's when `quiet` is `false`) like this, the S3 DeleteObjects operation returns a list of all files with their status after completing the operation. In quiet mode (`quiet` is `true`), only files which encountered an error during deletion are listed.  So something about the list of successfully deleted files is causing the SDK to throw this exception.

## Context

Writing an example for the `deleteObjects()` function for the code examples library and the Swift SDK developer guide.

## Environment

* AWS Swift SDK version used: 0.2.5
* Operating System and version (iOS/macOS/Linux): Amazon Linux 2
* Swift version 5.6.2 (swift-5.6.2-RELEASE)

## Reproduction Steps
This function is to be called with the name of a bucket and the names of one or more objects in that bucket.

```
    public func deleteObjects(bucket: String, keys: [String]) async throws {
        var objectList: [S3ClientTypes.ObjectIdentifier] = []
        for key in keys {
            let objId = S3ClientTypes.ObjectIdentifier(
                key: key
            )
            objectList.append(objId)
        }

        let deleteObjectList: S3ClientTypes.Delete = S3ClientTypes.Delete(objects: objectList, quiet: true)
        let input = DeleteObjectsInput(
            bucket: bucket,
            delete: deleteObjectList
        )
        do {
            _ = try await client.deleteObjects(input: input)
        } catch {
            throw error
        }
    }
```

Here, the `deleteObjectList` is created with `quiet` set to `true`, so the exception isn't thrown. If you remove `, quiet: true` from that line of code, the exception shown above will occur when `client.deleteObjects()` is called.

## Observed Behavior
In verbose mode, an exception is thrown but shouldn't be. Quiet mode works as expected.

## Expected Behavior
The files should be deleted with no exception thrown, regardless of whether quiet mode is used or not.

## Possible Solution
??

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.23.0
