### ISSUE TITLE
S3 Transfer Acceleration

### ISSUE THREAD

**Issue by ChristopheBougere** [awslabs/aws-sdk-swift#610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

I've been able to set up the S3 endpoint like this in order to use S3 transfer acceleration:
```swift
private class S3AcceleratedEndpointResolver: AWSClientRuntime.EndpointResolver {
    let bucketName: String
    init(bucketName: String) {
        self.bucketName = bucketName
    }
    func resolve(serviceId: String, region: String) throws -> AWSClientRuntime.AWSEndpoint {
        return AWSEndpoint(endpoint: .init(host: "\(bucketName).s3-accelerate.amazonaws.com",
                                           port: 443,
                                           protocolType: .https),
                           isHostnameImmutable: true)
    }
}

let s3Client = try S3Client(config: S3Client.S3ClientConfiguration(endpointResolver: S3AcceleratedEndpointResolver(bucketName: "my-bucket-name")))
```

However, I then have the following error: `The specified key does not exist.`.

I think this is because virtual-hosted style request is required in order to enable Transfer Acceleration (see [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html#transfer-acceleration-requirements)), and it looks like it's not supported in the SDK (see #237).

## Is your Feature Request related to a problem?

Feature not supported.

## Proposed Solution

Need to implement Transfer Acceleration or virtual-hosted style request.

## Describe alternatives you've considered

Defining the endpoint by myself with an endpointResolver, but I face the virtual-hosted style request issue.

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by ganeshnj** [comment]
This will be fixed by https://github.com/awslabs/aws-sdk-swift/issues/624

**Comment by ganeshnj** [comment]
It a quick test on `main` branch, you can access accelerate endpoint directly via a config.
```
let config = try S3Client.S3ClientConfiguration(accelerate: true, region: "us-west-2")
let client = S3Client(config: config)
let input = GetObjectInput(bucket: "jangirg-testing", key: "helloworld")
let output = try await client.getObject(input: input)
if let data = output.body?.toBytes().toData(), let s = String(data: data, encoding: .utf8) {
    print(s)
}
```

FYI, this change has not been released yet. We are doing final round of testing and it will be available soon.

**Comment by ganeshnj** [comment]
0.4.0 is out with feature.
