### ISSUE TITLE
Add streaming support for TranscribeStreaming

### ISSUE THREAD

**Issue by royjit** [awslabs/aws-sdk-swift#618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

If I am not wrong the SDK does not provide functionality for streaming. The existing Transcribe Streaming SDK just works as regular request/response api. 

## Proposed Solution

Support streaming - https://github.com/awslabs/aws-sdk-swift/issues/177

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by smivij** [comment]
This has a dependency on https://github.com/awslabs/aws-crt-swift/issues/99
