### ISSUE TITLE
SDK unable to source credentials in profile file or environment variables 

### ISSUE THREAD

**Issue by harr1424** [awslabs/aws-sdk-swift#623]
## Description
I first created a file `~/.aws/credentials` and input valid IAM credentials as described: 
```
[default]
aws_access_key_id = your_access_key_id
aws_secret_access_key = your_secret_access_key
```
Thereafter I attempted listing all objects in a public bucket as described in  the `List objects in a bucket`[example](https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/examples-s3-objects.html). I received the error: 
```
crtError(AwsCommonRuntimeKit.AWSError(errorCode: 6153, errorMessage: Optional("Valid credentials could not be sourced by the IMDS provider")))
```
Next, I defined these credentials as environment variables, restarted Xcode, and the error continued to appear when I ran the example code. Finally, I installed deleted the file `~/.aws/credentials` and installed the AWS CLI for the very first time. Once again I restarted Xcode and attempted to run the example code and still received the error. 

## Context
It may be relevant that at the time I added the package to my project, no `~/.aws/credentials` file existed and no environment variables had been set. I also only added the `AWSS3` and `AWSClientRunTime` libraries as I only require S3 functionality in my application. 

I encountered this error when running the following code: 
```
import Foundation
import AWSS3
import ClientRuntime
import AWSClientRuntime

public class S3manager : ObservableObject {
    private var client: S3Client?
    public var files: [String]?
    
    init() {
        Task(priority: .high) {
            do {
                client = try S3Client(region: "us-west-2")
                files = try await listBucketFiles(bucket: "harr1424.air.quality")
            } catch {
                print(error) // error is output here
            }
        }
    }
    
    // from https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/examples-s3-objects.html
    public func listBucketFiles(bucket: String) async throws -> [String] {
        
        if let clientInstance = client {
            let input = ListObjectsV2Input(
                bucket: bucket
            )
            let output = try await clientInstance.listObjectsV2(input: input)
            var names: [String] = []
            
            guard let objList = output.contents else {
                return []
            }
            
            for obj in objList {
                if let objName = obj.key {
                    names.append(objName)
                }
            }
            
            return names
            
        } else {
            print("Client has not been initialized!")
            return [String]()
        }
    }
}
```

## Environment
* AWS Swift SDK version used: `0.2.6`
* Operating System and version (iOS/macOS/Linux): `Mac OS Monterey 12.6`
* Xcode version (if applicable): `Version 14.0 (14A309)`
* Swift compiler version (if applicable): `Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)`
* Swift Tools version (if applicable):  `swift-tools-version:5.5`

## Reproduction Steps
See code snippet above, paste this code snippet into a `S3manager.swift` file inside a SwiftUI project. Inside `ContentView.swift` past the following: 
```
import SwiftUI

struct ContentView: View {
    @StateObject private var s3 = S3manager()
    
    var body: some View {
        VStack {
            List(s3.files ?? ["Content Loading..."], id: \.self) {
                Text($0)
            }
        }
    }
}
```

## Observed Behavior
Console output: 
```
crtError(AwsCommonRuntimeKit.AWSError(errorCode: 6153, errorMessage: Optional("Valid credentials could not be sourced by the IMDS provider")))
```
## Expected Behavior
List should display several string representations of .csv filenames.

**Comment by ganeshnj** [comment]
macOS and iOS apps run in sandbox that's probably the case you don't have access to host system and eventually credentials. If you would run the same code in a Console app, it will work.

The recommended way to use obtain AWS creds in such apps is through AWS Cognito.

**Comment by YoavGro** [comment]
@ganeshnj We are having the same issue, how would you use Cognito? (I don't see any guide/tutorial/explanation to describe the relevant object)

**Comment by jbelkins** [comment]
Closing, since Cognito support is a future planned feature and is tracked separately:
#324
