### ISSUE TITLE
Follow semver for preview releases

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#638]
### Describe the feature

Preview release don't follow semver which is common way to define version.

### Use Case

Customer are not conveyed with breaking change intent with current version scheme where major version is bumped for breaking change. This applies to service package as well as client runtimes.

### Proposed Solution

Follow semver
Use prereleaseidentifiers to convey preview SDK https://developer.apple.com/documentation/packagedescription/version/prereleaseidentifiers

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by epau** [comment]
Let's make sure we announce this when it goes live

**Comment by sichanyoo** [comment]
Closing ticket as we release daily with no preview releases, using automatic release system.
