### ISSUE TITLE
Endpoint Discovery

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#641]
### Describe the feature

--/seps/accepted/shared/endpoint-discovery.md

### Use Case

Client side solution to route traffic to a cell.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
More notes : https://quip-amazon.com/acgmAnpssS8u/Endpoint-discovery-summary

Kotlin has this on their GA roadmap.

**Comment by ganeshnj** [comment]
Smithy trait: https://github.com/awslabs/aws-sdk-swift/blob/main/codegen/sdk-codegen/aws-models/timestream-query.2018-11-01.json#L1211-L1213

**Comment by jbelkins** [comment]
https://t.corp.amazon.com/V795116669/overview

SIM ticket where an AWS service failed to operate because Endpoint Discovery is not yet implemented on the Swift SDK.  Updated with sample code to work around the lack of automatic endpoint discovery.

**Comment by smivij** [comment]
As per cross SDK feature matrix, this should not be implemented, below doc for reference.
bhbMAhPkHJh9/Endpoint-Discovery-and-why-we-should-deprecate-it

Instead we should use client side rules for endpoint construction
