### ISSUE TITLE
SDK Default Configuration

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#642]
### Describe the feature

--/seps/accepted/shared/default-configuration.md

### Use Case

SDK default configuration by vending predefined recommended defaults tailored to common usage patterns. Determines how the defaults should be resolved. A timeout trait is also introduced to model API level timeout.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
Lowering priority as this moved to "should do" for new SDK for GA from "must do"

**Comment by sichanyoo** [comment]
Moved to 2175
