### ISSUE TITLE
SSO Login Flow

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#646]
### Describe the feature

--/seps/accepted/shared/sso-login-flow.md

### Use Case

Completing the AWS SSO Login flow via the SSO-OIDC service.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
Based on discussion with other new SDKs and cross-referencing this feature in feature matrix, decided to move the priority down relative to other GA must-have features.

**Comment by sichanyoo** [comment]
Moved to 2174
