### ISSUE TITLE
Custom Request Header

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#655]
### Describe the feature

Support ability for customers to add headers to requests. See here for an example of a service that provides functionality via custom (unmodeled) headers: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_PutLogEvents.html

### Use Case

None

### Other Information

https://github.com/awslabs/aws-sdk-kotlin/issues/255

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
Removing the GA requirement based on cross-SDK feature matrix

**Comment by sichanyoo** [comment]
This can now be done with interceptors. Closing ticket now.
