### ISSUE TITLE
Provides a switch to turn on/off sigv4 body-signing

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#656]
### Describe the feature

By default, payload is singed using SigV4 which acts a data integrity check.

When enabled, the request will be signed with an `UNSIGNED-PAYLOAD` value. The request must be sent over a HTTPS connection.

### Use Case

Advanced use case.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
Lowered priority based on cross-SDK feature matrix

**Comment by sichanyoo** [comment]
Work complete in PR: https://github.com/awslabs/aws-sdk-swift/pull/1822

Closing ticket now.
