### ISSUE TITLE
Defaults to unsigned bodies with sigv4 over HTTPS

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#657]
### Describe the feature

Defaults to unsigned bodies with sigv4 over HTTPS.

seps/accepted/shared/unsigned-payload-trait.md

### Use Case

Reduce overhead.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
As per feature matrix this is marked as "should" instead of "must" for GA, lowering priority to 3

**Comment by smivij** [comment]
Notes from Kotlin : from Aaron: "IIRC there are operations that require unsigned payload (and there is a corresponding smithy trait (https://smithy.io/2.0/aws/aws-auth.html#aws-auth-unsignedpayload-trait) for this). You can basically ignore the SEP and implement the smithy trait as they are the same thing."

**Comment by sichanyoo** [comment]
Smithy's unsigned payload trait has been implemented. During codegen the existence of unsigned payload trait on the operation is checked, and signing config flag for it is set accordingly. This is then handled by CRT. CRT handles adding the header `x-amz-content-sha256: UNSIGNED-PAYLOAD` to the request. Closing the issue as resolved.
