### ISSUE TITLE
Review Swift  user-agent Strings

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#661]
### Describe the bug

Amplify Team (Harshita Daddala) reported issue with UserAgent String. There are duplicate strings in UserAgent and need to explore if they can be removed, the underlying issue is that Amplify's useragent string is getting truncated due to 255 char length limit. See exact communication below

********************************

I am writing in regards to some questions on the user-agent strings for Swift and Android/Kotlin logs.
 
Example User Agents
 
Amplify Library for Android | AWS SDK for Kotlin –
“AWS-SDK-KOTLIN/0.17.7-BETA AWS-SDK-KOTLIN/0.17.7-BETA OS/ANDROID/4.19.81-19350423 LANG/KOTLIN/1.7.10 LIB/AMPLIFY-ANDROID/1.36.6-DEV-PREVIEW.0 MD/SAMSUNG/SM-G988U1 MD/LOCALE/EN_US”
 
Amplify Library for Swift | AWS SDK for Swift –
“AWS-SDK-SWIFT/1.0 AWS-SDK-SWIFT/1.0 API/COGNITO-IDENTITY/1.0 OS/IOS/16.0.0 LANG/SWIFT/5.7 LIB/AMPLIFY-IOS/1.27.1-SWIFT-SDK-DEV-PREVIEW.0”
 
“AWS-SDK-SWIFT” and “AWS-SDK-KOTLIN” strings show up twice, since we have a character limit for this field, can this be fixed to show only one instance of “AWS-SDK-SWIFT/KOTLIN”?
“OS/ANDROID/4.19.81-19350423” <- what version is this referring to? Is it the OS version or Kernel version? We prefer the Android OS version for tracking.
Since we already have the API information as part of the entry under “service_id” and “operation_name”, can we remove the api info in the user-agent string for AWS-SDK-SWIFT please? i.e. “API/COGNITO-IDENTITY/1.0 OS/IOS/16.0.0”
 
Please let me know if you need further clarification.
 

### Expected Behavior

Not have any truncation in UserAgent 

### Current Behavior

Duplicate strings observed

### Reproduction Steps

Pull UserAgent from Metrics DB

### AWS SWIFT SDK version used

1.0

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by ganeshnj** [comment]
From the logs it seems we are sending
```
aws-sdk-swift/1.0 api/s3-control/1.0 os/macOS/12.6.2 lang/swift/5.7
```
which doesn't repeat `aws-sdk-swift` like shown in the description.

My hunch, either this is already fixed or we have some other place this append happens.

**Comment by ganeshnj** [comment]
@smivij could you verify if this issue still persists?

**Comment by ganeshnj** [comment]
Double checked with @aajtodd. This doesn't seem like an issue on SDK side. Kotlin team did adjust their user-agent string because it was getting truncated but for Swift I have not seen any truncation.

I'm going to close this issue and if we ever have truncation, we can revisit.
