### ISSUE TITLE
Run Swift linter on CI using a Docker container

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#677]
### Describe the feature

We are currently running Swiftlint on a Github Mac runner because the SwiftLint action that we previously used (`norio-nomura/action-swiftlint`) seems to be no longer supported, and does not run latest SwiftLint.

Running the linter on a Mac is not preferable because Mac minutes are more expensive, and requiring a Mac to lint limits our flexibility on where we can run CI.

### Use Case

To provide for economical, flexible linting of the project code.

### Proposed Solution

Create a `Dockerfile` or other configuration to install SwiftLint into a container, then use the container to perform linting on CI.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Thinking rationally, we might just not do it. Run CI on all platforms but linter can keep running on macOS.

**Comment by jbelkins** [comment]
Completed using "official" SwiftLint Docker containers provided by the SwiftLint project.
