### ISSUE TITLE
S3 PutObjectInput.presignURL metadata not included

### ISSUE THREAD

**Issue by nikola-mladenovic** [awslabs/aws-sdk-swift#683]
### Describe the bug

When using 

```
PutObjectInput(bucket: "bucket", contentType: "image/png", key: "key", metadata: ["metadata-key":"metadata-value"]).presignURL(config: s3Config, expiration: 600)
```

to create a presigned URL to upload objects to S3, metadata is not included in the presigned URL.

### Expected Behavior

When using PutObjectInput.presignURL with metadata, **the metadata should be included in the presigned URL** (e.g in URL params).

### Current Behavior

When using PutObjectInput.presignURL with metadata to create a presigned URL to upload objects to S3, metadata is not included in the presigned URL.

### Reproduction Steps

Use the following to generate a presigned URL:

```
PutObjectInput(bucket: "bucket", contentType: "image/png", key: "key", metadata: ["metadata-key":"metadata-value"]).presignURL(config: s3Config, expiration: 600)
```

### AWS SWIFT SDK version used

0.3.1

### Compiler and Version used

Xcode 14.1, swiftlang-5.7.1.135.3

### Operating System and version

macOS 12.6

**Comment by jbelkins** [comment]
S3 PutObject metadata support was added in https://github.com/awslabs/aws-sdk-swift/pull/1139

Closing as Done.
