### ISSUE TITLE
SRA Observability

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#696]
### Describe the feature

Standardize on the use of tracing for logging and debugging.

### Use Case

Use case varies from simple logging to debugging the issues in production.

### Proposed Solution

~~Standard guide: DHC8AvgUJcUi~~
~~Swift version: 1yHUAd867GxZ/Tracing#temp:C:Obf291b6d42186e7d8bbb6886a80~~

Standard guide: BbKeALtIAOEA
Swift version: 0oAmApp4MKrz

- [ ] include design in the repo
- [ ] Implement the design

### Acknowledgements

- [ ] I may be able to implement this feature request
- [x] This feature might incur a breaking change

**Comment by jbelkins** [comment]
This PR with tracing / observability interfaces (plus a default implementation with logging only) has merged:
https://github.com/smithy-lang/smithy-swift/pull/674

**Comment by syall** [comment]
Next step: add telemetry into the operation orchestrator (pending PRs: https://github.com/smithy-lang/smithy-swift/pull/694, https://github.com/awslabs/aws-sdk-swift/pull/1435).
