### ISSUE TITLE
Identity and Authentication

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#700]
### Describe the feature

Consistent interfaces for identity and authentication. We will need quite a bit of work and also help from CRT for implementations.

### Use Case

Consistent interfaces.

### Proposed Solution

- [ ] Design document in repo inspired from  GFGdAiHwv1Pu quip
- [ ] Implementation 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Tracked in https://github.com/awslabs/aws-sdk-swift/issues/1119

**Comment by sichanyoo** [comment]
Released with https://github.com/awslabs/aws-sdk-swift/releases/tag/0.37.0.
