### ISSUE TITLE
Recursion Detection

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#704]
### Describe the feature

seps/accepted/shared/recursion-detection.md

### Use Case

seps/accepted/shared/recursion-detection.md

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
This does not appear in the cross sdk feature matrix, its a lambda only feature, will change priority in future based on upvotes

**Comment by sichanyoo** [comment]
Moved to 2176
