### ISSUE TITLE
Automatically detect api breaking changes on PRs

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#705]
### Describe the feature

A github action that runs on every PR and comments on the PR if the PR breaks an api or if there are no api breakages.

### Use Case

In order to better identify api breaking changes and prevent accidental breakages.

### Proposed Solution

It would be great to use swift's first part tools such as `swift package diagnose-api-breaking-changes` but this currently isn't working as expected in neither the aws-sdk-swift nor the smithy-swift repos. 

An issue has been filed with the swift package manager team 
https://github.com/apple/swift-package-manager/issues/5890

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2178
