### ISSUE TITLE
Build Amplify main branch with AWS SDK main branch as downstream

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#706]
### Describe the feature

Construct a CI workflow that builds the Amplify Swift SDK from its `main` branch, and integrates it with this repo's `main` branch.

Run the workflow with triggers / schedule sufficiently often to identify issues early in the release cycle.

### Use Case

Failed builds of this workflow will serve as a "canary" that indicates potential breakage for Amplify on the next release.

### Proposed Solution

Create a CI workflow as described & place it in service.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
Closing as won't do
