### ISSUE TITLE
Add test for recursive enum code gen

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#712]
### Describe the feature

Currently, it's possible for code gen to create recursive enums (enums that have associated values that reference themselves). 
We should verify the `indirect` keyword is added to these enum definitions as prescribed by the swift language https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Released in https://github.com/awslabs/aws-sdk-swift/releases/tag/0.6.0, closing as completed.
