### ISSUE TITLE
[Analysis] Don't model everything as optional

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#715]
### Describe the feature

Currently, we will model every member as optional, regardless of the member's traits. 
This makes things hard to reason about and provides clunky development experience as it moves issues to runtime which normally could be caught by the compiler. 

Let's model optionality according to https://smithy.io/2.0/spec/aggregate-types.html#structure-member-optionality
while also accounting for customer experience. 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment]
The first step is to identify what the changes are - effort 1 week

**Comment by sichanyoo** [comment]
Service-specific client versioning is a dependency for implementing Smithy's required trait.

**Comment by dayaffe** [comment]
Proposal was reviewed by team: `/g5MBAlZ3M8vR/Proposal-Dont-Model-Everything-as-Optional`
