### ISSUE TITLE
Add handling for Int Enum smithy shape

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#722]
### Describe the feature

https://smithy.io/2.0/spec/simple-types.html#intenum

### Use Case

To unblock upgrading smithy https://github.com/awslabs/aws-sdk-swift/issues/721

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Released in https://github.com/awslabs/aws-sdk-swift/releases/tag/0.6.0, closing as completed.
