### ISSUE TITLE
Add presigned URL method for S3 UploadPart

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#723]
### Describe the feature

Add a `presignURL` method for S3 `UploadPart`, similar to the existing ones for `GetObject` and `PutObject`.
Also, add an integration test for the new API.

### Use Case

To allow multipart upload to be performed by HTTP clients other than the AWS SDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by trastoan** [comment]
Hi everyone,

What's the current workaround to be able to use other HTTP clients for Multipart Upload? Since AWS SDK doesn't support multipart in background?

**Comment by plu** [comment]
I started looking into this in #1809. Not sure how good/correct my approach is there, but I can tell that it's working already. If somebody familiar with the code base can give a 👍 or 👎, would be great. After getting the code into the correct shape I'll be happy to add tests on top.

**Comment by sichanyoo** [comment]
@plu Hi there, I've put a review on the PR; please let me know what you think by replying to my comments, thanks!

**Comment by sichanyoo** [comment]
Support for this feature has went out with https://github.com/awslabs/aws-sdk-swift/releases/tag/1.0.52 last week, closing ticket now.
