### ISSUE TITLE
Swift support for Timestream SDK

### ISSUE THREAD

**Issue by atdang-amazon** [awslabs/aws-sdk-swift#725]
### Describe the feature

Add a Swift SDK for Timestream.

### Use Case

Some customers would like to use Timestream operations within the Swift mobile apps they are building but cannot because there is neither a Swift SDK or REST API for Timestream.

### Proposed Solution

Add support for a Swift SDK for Timestream alongside Go, Java, Python, etc.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
There are two Timestream-related clients in the latest SDK: `AWSTimestreamWrite` and `AWSTimestreamQuery`.  Do these not include the operations you need?

**Comment by atdang-amazon** [comment]
Did not notice that the first time around. Thank you!
