### ISSUE TITLE
[ECD 11/21] Use DocC to produce documentation

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#730]
### Describe the feature

Previously we had used [swift-doc](https://github.com/SwiftDocOrg/swift-doc) for producing documentation. That project has since been archived and no longer maintained. We should use [DocC](https://www.swift.org/documentation/docc/documenting-a-swift-framework-or-package) to generate our docs.

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
Verify documentation for public code in all extensions is also generated and co-located with the extended type
https://github.com/awslabs/aws-sdk-swift/issues/551

**Comment by epau** [comment]
Blocked until we figure out next steps regarding generating docs.

**Comment by aalviggi** [comment]
Hi - Please ensure the 6 Swift violations mentioned in https://quip-amazon.com/DaSJAa0p2BkC/SDK-Accessibility-Audit-2022#temp:C:YYV04ab72c49696447c82cfc8235 are addressed by this

**Comment by ganeshnj** [comment]
For reference https://github.com/awslabs/aws-sdk-swift/issues/757

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.32.0
