### ISSUE TITLE
feat: Add facility to smithy-swift for testing generated Swift code

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#734]
### Describe the feature

There are Smithy-specific protocol tests and features which need to be code-generated and tested.  Currently all of the logic & configuration for these sorts of tests resides in this project (aws-sdk-swift).

As an example, Smithy waiters is a non-AWS specific Smithy feature.  Its implementation is 100% in the smithy-swift repo.  But tests for certain components, such as matchers generated from JMESPath expressions, have to be located in aws-sdk-swift because there is no current way to code-generate then test Swift code in smithy-swift. 

Providing this test facility in smithy-swift would reduce the amount of coupling between the SDK and smithy-swift, and simplify development since only one project will be involved in building and testing a Smithy feature.  Having a feature in one project and its tests in another is a form of circular dependency that predictably complicates development.   It will also reduce complexity because each project will be focused on supporting only its own features.

### Use Case

Build a Smithy feature which generates Swift code containing nontrivial logic.

Now you need facilities so that you can easily add high-quality tests that actually exercise your generated code.

### Proposed Solution

Add a code generation Gradle task and a Swift test target that can be used to code-generate Swift, then to build & test it, respectively.

Move all tests that are currently in `aws-sdk-swift` but not specific to the AWS SDK for Swift over to the new facilities in the Smithy project.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
We already have WeatherSDK which builds entirely within smithy-swift.  We should be able to follow the same pattern to set up our waiters tests and anything else that we want to generate then unit-test.

**Comment by sichanyoo** [comment]
Moved to 2150
