### ISSUE TITLE
Cognito Unauthenticated Access

### ISSUE THREAD

**Issue by duncangroenewald** [awslabs/aws-sdk-swift#739]
### Describe the bug

Can someone provide and example of how to use Cognito to provide an application with unauthenticated access.

Client application needs to be able to access certain AWS services by default.

The API examples appear to be focussed on API calls to create identity pools rather than actual application authentication.

### Expected Behavior

There does not appear to be the equivalent 

// Initialize the Amazon Cognito credentials provider
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
    getApplicationContext(),
    "ap-southeast-2:xxxxxxx", // Identity pool ID
    Regions.AP_SOUTHEAST_2 // Region
);

or ability to set the defaultServiceConfiguration

AWSServiceManager.default().defaultServiceConfiguration = USEast1ServiceConfiguration

### Current Behavior

Unclear how to authenticate with Cognito using Swift SDK

### Reproduction Steps

Unclear how to authenticate with Cognito using Swift SDK

### AWS SWIFT SDK version used

0.5.0

### Compiler and Version used

Xcode 14.1

### Operating System and version

macOS 13.0.1

**Comment by ganeshnj** [comment]
@shepazon this is something we should document in the tutorials.

**Comment by naingminoo99** [comment]
can we have any update on this. still cannot find a proper example or doc regarding credential configuration for this sdk.

**Comment by sichanyoo** [comment]
Credential providers section in developer guide gives some context on how to use credential providers in Swift SDK [here](https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/using-identity.html).

As for how to use Cognito to handle authentication and authorization, see [`AWS Cognito Developer Guide`](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html).
