### ISSUE TITLE
Reorganize smithy-swift Swift code to standard Swift package layout

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#741]
### Describe the feature

The smithy-swift repo is not laid out like a normal Swift package, which causes developer confusion, requires extra configuration, and prevents some Swift tooling from working properly with this package.  To remedy:
- Move code out of the `Packages/` subdirectory & into `Sources/` and `Tests/` per standard SPM layout
- Remove path specifications from `Package.swift`
- Move `.swiftlint.yml` to root of project, adjust paths and verify proper operation desktop & CI

### Use Case

To conform to Swift standard package layout & enhance compatibility with various Swift tools

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2151
