### ISSUE TITLE
Add error code to Swift SDK errors

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#742]
### Describe the feature

When decoding an error, every AWS serde protocol extracts a string `errorCode` from the error response.  This code indicates the general nature & cause of the error, i.e. `invalidParameters`, `resourceNotAvailable`, etc.

When an error converted to a Swift type by the SDK, the specific Swift type to be created is determined by matching the error's `errorCode` to a set of Swift error types that are predefined for that operation.  It is possible, though, that an error may be returned that is not defined on the service; in that case, an `UnknownAWSHttpServiceError` is created & returned to hold the error's parameters.

Typically, when a Smithy waiter matches an error by `errorType`, the string `errorType` specified in the Smithy waiter will match the `errorCode` in the received error.  This method may be used whether or not the error is defined for the operation since any error should have an `errorCode`.

In general, Swift SDK errors currently do not preserve or make their `errorCode` available once they are created.  This functionality will have to be added so that waiter error matching can be performed.

### Use Case

Errors received by the AWS Swift SDK must be able to provide their error code so that they may be matched by Smithy waiters.

### Proposed Solution

1. Implement a `CodedError` protocol in `smithy-swift` as follows:

```swift
public protocol CodedError {
    var errorCode: String?
}
```
that can be used to extract the error code from any conforming error type.

2. Make `SdkError` conform to `CodedError`.  This will require all generated operation output errors and `UnknownAWSHttpServiceError` to conform as well.

3. Update the waiter error matcher to match when the expected error type defined in the waiter matches the error code of the returned error.  (The error matcher will fail to match when the returned error does not conform to `CodedError`.)

### Other Information

This work will enable completion of PR #483.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
No longer necessary. We can handle error "code" (type) as we see fit when tackling #692
