### ISSUE TITLE
SDK throws deprecation warnings for internal use of deprecated properties

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#745]
### Describe the bug

The AWS SDK contains many models with deprecated properties.  Much of our generated code for initialization, encoding, decoding, etc. accesses these properties, triggering compile warnings.  Continued internal support for deprecated properties should not trigger a warning; only access to these properties by public API should trigger it.

### Expected Behavior

When you compile the Swift SDK, warnings should not be raised for internal access to deprecated properties.  Warnings should only be raised when SDK consumers access the deprecated properties.

### Current Behavior

When you compile the Swift SDK, warnings are being raised for internal access to deprecated properties.

### Reproduction Steps

Compile Swift SDK, observe warnings.  Here is a typical warning, thrown by a model initializer:
```
/Users/jbelkins/Code/aws-sdk-swift/release/AWSEC2/models/Models.swift:15058:17: warning: 'associatedTargetNetworks' is deprecated: This property is deprecated. To view the target networks associated with a Client VPN endpoint, call DescribeClientVpnTargetNetworks and inspect the clientVpnTargetNetworks response element.
                associatedTargetNetworks = []
                ^
```

### Possible Solution

Warnings should either be suppressed with Swift compiler configuration / suppression directives (not sure this is currently possible) or code should be generated in a manner such that deprecation warnings are not triggered by internal access to deprecated properties (i.e. public deprecated properties are backed by a private var that does not bear the deprecated annotation.)

### AWS SWIFT SDK version used

Latest

### Compiler and Version used

Latest

### Operating System and version

Latest

**Comment by sichanyoo** [comment]
Moved to 2152
