### ISSUE TITLE
Streamline API Reference Docs for Swift

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#757]

**Comment by smivij** [comment]
We need to identify what needs to be done to host API reference docs on 

https://awslabs.github.io/aws-sdk-swift/reference/0.x/index.html

like other SDKs (example :https://sdk.amazonaws.com/java/api/latest/). 

- Look and feel needs to be analyzed and fixed
- We need to fix accessibility issues that were raised and sized (later 2022)
- Identify what it takes to move to Unified Docs (create separate issue if effort is huge)

**Comment by smivij** [comment]
@smivij to find out what needs to be done to move to unified docs

**Comment by ganeshnj** [comment]
https://github.com/awslabs/aws-sdk-swift/pull/780

We have a working solution. I would like to work with @kstich to see how this can fit with unified docs.

**Comment by ganeshnj** [comment]
We must target with catapult releases.

**Comment by smivij** [comment]
Closing as duplicate of #730
