### ISSUE TITLE
S3 404 errors not parsing

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#761]
### Describe the bug

When a 404 error is received for AWS S3 HeadObject or HeadBucket, the error fails to parse.

### Expected Behavior

Expect to receive a NotFound SDK error parsed from the response.

### Current Behavior

A client-side XML deserialization error is returned.
From inspecting the response, the HTTP code is 404 but the body appears to be empty.

### Reproduction Steps

Using the S3Client, perform a `headBucket` operation for a bucket that doesn't exist; observe the error thrown by the client.

### AWS SWIFT SDK version used

main branch

### Compiler and Version used

Xcode 14.2

### Operating System and version

macOS 12.6.1

**Comment by epau** [comment]
Possibly same issue as https://github.com/awslabs/aws-sdk-swift/issues/759
