### ISSUE TITLE
SQS change from AWSQuery to AWSJSON

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#763]
Details of the issue is in SIM...
*[SQS change from AWS Query to AWS JSON](https://issues.amazon.com/issues/SDK-82857)* 

SQS created a https://quip-amazon.com/qBbbArTLikRM/Future-proofing-AwsQueryCompatible-supportto support AwsQueryCompatible support in non-GA SDKs, with a call out that while backwards compatibility is not required for their service, any other services that will eventually migrate to AWS JSON would need this trait. SDK team reviewed and agreed. We will add this to the GA checklist for non-GA SDKs by 12/23

**Comment by smivij** [comment]
The expectation is that we only need to support AWSJson for new SDKs and if we already support AWSQuery we need to change that

**Comment by jbelkins** [comment]
Released in AWS SDK for Swift 0.32.0
