### ISSUE TITLE
Add Waiters design doc to smithy-swift project

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#766]
### Describe the feature

Have the team make one more pass through the Waiters design doc in Quip.

Export the Waiters design doc from Quip to a markdown document in the `smithy-swift` project's `design/` subfolder.

### Use Case

To document the design rationale along with the implementation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Work is already done with https://github.com/smithy-lang/smithy-swift/pull/498; closing ticket.
