### ISSUE TITLE
Support hand written integration tests

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#769]
### Describe the feature

We want to be able to hand write integration tests that depend on specific service(s). 
We need to develop some system that 

- [ ] defines where tests are located
- [ ] defines how test packages are generated and tied to specific service(s)
- [ ] Run in an AWS account that Swift team owns

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Something to think about testing components that need AWS resources. This doesn't need to solved as part of this ticket.

**Comment by smivij** [comment]
We now have hand written integration tests, the pending work is to integrate them with our CI, nightly jobs and release builds.
