### ISSUE TITLE
chore: Add CI task to build generated SDK

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#773]
### Describe the feature

The `aws-sdk-swift` main branch should build a working SDK, without compile errors, at all times.

However, there is currently no CI task that verifies this on PRs before they merge to main.

On the `aws-sdk-swift` repo, add a CI task (or modify an existing task) to build the generated SDK, with dependencies as specified in `Package.swift`.  The task should pass if the entire SDK (all services) compiles without errors.

PRs that do not build a valid SDK should include regenerated code and/or changes to `Package.swift` as needed prior to merging.

### Use Case

Needed to ensure that the main branch builds a SDK at all times.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Curious if we need a another task or if current CI tasks do
- Run codegen
- Update `release` dir
- Update Package.swift
- swift build
- swift test
This must ensure a PR is fine to merge.

**Comment by jbelkins** [comment]
Our current CI task for `aws-sdk-swift` performs the following on iOS, macOS, and two Linux flavors (see `builder.json`):
- Build & test AWS SDK-specific codegen (`smithy-aws-swift-codegen`)
- Build & codegen protocol tests (`protocol-test-codegen` and `protocol-test-codegen-local`)
- Build & test Swift: `AWSClientRuntimeTests`
- Build & test Swift protocol tests that were generated above

**Comment by jbelkins** [comment]
Code generating, then building the entire SDK is a lengthy process... the release task takes one hour plus to finish this on a Mac runner (which is higher-specced than a standard Linux runner.). If we are going to do this on PRs, it should be a dedicated task, AND we should investigate what faster runners are available to us for performing it.
