### ISSUE TITLE
Some errors thrown by waiter operations aren't retried when they should be 

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#781]
### Describe the bug

It is expected that waiter operations will retry the request if specific errors are returned. 
Currently, there are some errors that are expected to, but don't result, in a retry. 

For example, on the S3 service `waitUntilBucketExists` is expected to retry if the response returns a 404 (NotFound) error. Currently, this operation is not retried in this case.

I think the core issue is that [this case](https://github.com/awslabs/smithy-swift/blob/main/Sources/ClientRuntime/Networking/SdkError.swift#L26-L27) will always return `nil` since the underlying [ClientError](https://github.com/awslabs/smithy-swift/blob/main/Sources/ClientRuntime/Networking/ClientError.swift) does not conform to [WaiterTypedError](https://github.com/awslabs/smithy-swift/blob/main/Sources/ClientRuntime/Waiters/WaiterTypedError.swift). The SDK's absurd nesting error modelling also contributes to this issue. So we'll need to make sure that all possible nested error types conform to `WaiterTypedError` accordingly.

### Expected Behavior

N/A

### Current Behavior

N/A

### Reproduction Steps

```swift
let config = try DefaultSDKRuntimeConfiguration("S3 Client", clientLogMode: .requestAndResponseWithBody)
let clietnConfig = try await S3Client.S3ClientConfiguration(runtimeConfig: config)
let client = S3Client(config: clietnConfig)

do {
   let result = try await client.headBucket(input: .init(bucket: "non-existant-bucket"))
   let waiterResult = try await client.waitUntilBucketExists(
        options: .init(maxWaitTime: 120),
        input: .init(bucket: "non-existant-bucket")
    )
} catch {
    print(error)
}
```

### AWS SWIFT SDK version used

0.7.0

### Compiler and Version used

14.2.0

### Operating System and version

12.6.1

**Comment by jbelkins** [comment]
This should be worked after #759 and #761 have been addressed, since certain waiters depend on properly decoding errors on those services.
