### ISSUE TITLE
Replace rogue encoder and decoder instances

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#786]
### Describe the bug

There are a few instances where one-off encoders and decoders are being created by models. We should be using the encoder/decoder from the client instead of creating new instances. 

There are a few benefits to this 
- we get any configuration that was performed on the encoder/decoder
- we remove coupling and follow proper dependency injection pattern

One example: https://github.com/awslabs/aws-sdk-swift/blob/39db4f1c33ef04169540849af496d1747f7b26f4/AWSClientRuntime/Sources/Protocols/Ec2Query/Ec2QueryError.swift#L18

### Expected Behavior

N/A

### Current Behavior

N/A

### Reproduction Steps

N/A

### AWS SWIFT SDK version used

N/A

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by jbelkins** [comment]
Closed due to new closure-based serde.
