### ISSUE TITLE
Investigate a mechanism to hand write service specific customizations

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#789]
### Describe the feature

There are times where we need to make service specific customizations. One example is #214. Currently, we need to implement the customization via codegen, even if all the code is static (does not depend on smithy models). 

It would be much simpler if we could implement these customizations directly as swift code (without needing to go through the code generation process). We still would only want these files to be included in their corresponding service module, which makes this tricky. 

Investigate a way that we can write service specific swift files (and tests). 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
not adding to GA as we are not blocked for any feature that needs this.

**Comment by sichanyoo** [comment]
Moved to 2168
