### ISSUE TITLE
Regenerate models and build the full SDK as part of PR checks

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#808]
### Describe the feature

We are currently prone to build issues slipping into `main` since we don't currently regenerate the models and build the full SDK on PRs. This leaves this test up to the developer to perform manually. 

Let's add this as part of the CI workflow that is run on every PR but work will need to be done to make this as efficient as possible so we don't negatively impact productivity too much. Perhaps we should define some SLA that CI needs to execute under, such as 30 minutes.

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Resolving in favor of catapult integration.

**Comment by epau** [comment]
Re-opening since this deals with catching issues during development which is unrelated to catapult.

**Comment by sichanyoo** [comment]
There exists `codegen-build-test` CI job now that does this. Closing ticket now.
