### ISSUE TITLE
Create CI workflow to rengerate and update models on main

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#810]
### Describe the feature

Currently, as part of the release workflow, we regenerate the models and push a commit to the branch. 
Sometimes, outside of the release cycle, we want to regenerate models on main. We usually want to do this after merging in code that will make the previously generated models no longer build successfully with the dependencies (AWSClientRuntime, ClientRuntime, CRT etc).

It'd be awesome to have a workflow that we can trigger manually that will do the following
- create a new branch based off main
- regenerate the models
- test the full sdk
- commit the changes
- push the branch
- open a PR 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Resolving in favor of catapult integration.
