### ISSUE TITLE
Enable generated service test targets

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#814]
### Describe the bug

Currently we have disabled the test targets because swift CLI fails to run them and errors out.

### Expected Behavior

`swift test` must run service test targets.

### Current Behavior

Fatal fail.

### Reproduction Steps

- in Package.swift, uncomment testTargets for services
- swift test  

### AWS SWIFT SDK version used

man

### Compiler and Version used

5.7.2

### Operating System and version

macOS 12.6.1

**Comment by ganeshnj** [comment]
We can try using xcodebuild for just on macs to atleast run on one OS. But we would like to stick to swift cli.

**Comment by smivij** [comment]
This is done now.
