### ISSUE TITLE
Add canary job to build and test the full sdk on all platforms

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#831]
### Describe the feature

We want to codegenerate, build, and test the full SDK on all platforms (macOS, linux, windows, iOS) to catch any issues that may arise during development. This is currently not feasible to do on every PR due to the time cost so let's do this on some regular cadence. Additionally we want to allow folks to manually trigger this job on any branch.

Potential options:
- run on every commit to main
- run at some fixed time, such as every night @ 12am PT. 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
- make it not required but still part of PR checks and developers make sure final merge has it passed

**Comment by epau** [comment]
I briefly looked into github actions controls for triggering workflows on PRs and it looks like this will be very doable. 
We can configure the job to by triggered when a comment is added to a PR and it contains specific keyword(s).

**Comment by jbelkins** [comment]
CI and integration tests now run on oldest & newest Xcode / Swift for all supported platforms.

Closing as Done.
