### ISSUE TITLE
[ECD 11/21] Do not add the account id prefix when generating endpoints for S3Control

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#832]
### Describe the bug

The endpoints for the S3 Control service should not contain the account id prefix. 
We must add a customization that does one of the two:
1.) Ignore the {AccountId}. hostPrefix specifications in the model for s3control clients
2.) Circumvent the standard hostPrefix appending functionality for s3control

### Expected Behavior

The URL for the operation does not have an account id prefix
if account id is 123456, then an example of a URL that would be produced currently is below:

`https://s3-control.us-east-1.amazonaws.com/v20180820/bucket/some_bucket/versioning?`

### Current Behavior

The URL for the operation currently has the account id prefix 
if account id is 123456, then an example of a URL that would be produced currently is below:

`https://123456.s3-control.us-east-1.amazonaws.com/v20180820/bucket/some_bucket/versioning?`

### Reproduction Steps

```swift
let client = S3ControlClient(config: ...)

let result = try await client.putBucketVersioning(input: .init(
    accountId: <some_account_id>,
    bucket: <some_bucket>,
    versioningConfiguration: .init(status: .enabled)
))
```

### AWS SWIFT SDK version used

0.8.0

### Compiler and Version used

swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

### Operating System and version

12.6.2

**Comment by ganeshnj** [comment]
This should be done via model preprocessing, for S3 Control we can remove the hostPrefix trait from model and let the codegen do its job.

**Comment by ganeshnj** [comment]
Even with removing the accountId from hostname doesn't work. There seems to be more underlying issue here.

**Comment by ganeshnj** [comment]
https://github.com/awslabs/aws-sdk-swift/issues/216 is related.

**Comment by dayaffe** [comment]
I've confirmed the behavior of Swift SDK is consistent with Rust SDK and the AWS CLI. Across all 3 when issuing an s3 control request on a method meant for outpost, if an outpost id (optional) is not included the endpoint will be prefixed with an account id such as `000123456789.s3-control.us-west-2.amazonaws.com/v20180820/bucket` and the server will return an invalid URI error but when any outpost id is included the endpoint hit will not be prefixed with the account id such as `s3-outposts.us-west-2.amazonaws.com`.

Additionally, according to [s3-control-customizations SEP](https://code.amazon.com/packages/AwsDrSeps/blobs/main/--/seps/accepted/shared/s3-control-customization.md): `The S3 Control service also requires the AccountId API input parameter to be serialized into the request endpoint's host`. Prefixing the endpoint when it hits s3-control is consistent.
