### ISSUE TITLE
Feature request: Allow using Swift dictionaries directly when using DynamoDB

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#833]
### Describe the feature

Let developers skip the step of converting their Swift dictionaries into `WriteRequest` lists and vice versa. This should be an optional way of building requests, added on top of existing functionality. It can obviously wait until a post-GA release of the SDK.

### Use Case

This would simplify code quite a lot, especially for batch writes where the data is a lengthy list of objects.

### Proposed Solution

As an example of one way to do this, to write a bunch of dictionary objects called `myDataToWrite` and delete objects from a dictionary named `myDataToDelete`, let the developer just write:

```
let input = BatchWriteInputX(putRequests: myDataToWrite, deleteRequests: myDataToDelete)
```

or if only writing data and not deleting any:

```
let input = BatchWriteInputX(putRequests: myDataToWrite)
```

(Where `BatchWriteInputX` is some appropriately named feature-added name for the dict-ready constructor). Something like this, or at least allowing similar functionality, would be helpful.

### Other Information

Note that Boto3 offers a similar functionality already in its `batch_write()` function for DynamoDB. Take a look at [this code](https://github.com/awsdocs/aws-doc-sdk-examples/blob/f783854e17ed09f8620a66323e097a47d409e789/python/example_code/dynamodb/GettingStarted/scenario_getting_started_movies.py#L127), for instance. It’s batch writing into DynamoDB an array of Python objects that was [previously loaded](https://github.com/awsdocs/aws-doc-sdk-examples/blob/f783854e17ed09f8620a66323e097a47d409e789/python/example_code/dynamodb/GettingStarted/scenario_getting_started_movies.py#L381) from JSON, without having to do any conversion beforehand. That would be pretty nice to have.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
This is something for future, doesn't align with GA items.

**Comment by sebsto** [comment]
Providing a custom DynamoDB encoder and decoder would significantly simply DynamoDB code
See [this implementation](https://github.com/soto-project/soto/tree/main/Sources/Soto/Extensions/DynamoDB) and its related [documentation](https://soto.codes/user-guides/dynamodb-and-codable.html) as an example

**Comment by shepazon** [comment]
This is exactly what we need to have here, eventually.

Eric Shepherd
Senior Developer Writer
Amazon Web Services

On Feb 3, 2023, at 7:32 AM, Sébastien Stormacq ***@***.***> wrote:



Providing a custom DynamoDB encoder and decoder would significantly simply DynamoDB code
See this implementation<https://github.com/soto-project/soto/tree/main/Sources/Soto/Extensions/DynamoDB> and its related documentation<https://soto.codes/user-guides/dynamodb-and-codable.html> as an example

**Comment by sichanyoo** [comment]
Moved to 2169

**Comment by sebsto** [comment]
@sichanyoo can you add the link to the new issue to track this ? 2169 does not exit (404 error)
