### ISSUE TITLE
S3 : preSignedURL is not documented / not on the correct class

### ISSUE THREAD

**Issue by sebsto** [awslabs/aws-sdk-swift#837]
### Describe the feature

- The S3 `presignURL` should be on the `S3Client` class instead on the `GetObjectInput` class
- This method should be part of the top level documentation for the usage of S3 

### Use Case

I came accros a use case where developer want to use `AsyncImage` to download and display a picture from S3. I could not find a S3 “presignedUrl()” API in the S3 client like there is on other platforms (Java, .Net, JS, and  — I think — Python)) - I even thought it was part of the S3 API but looks like it is not, it is a SDK-level addition.

Finally, Ganesh pointed to me to

```
extension GetObjectInput {
    public func presignURL(config: S3ClientConfigurationProtocol, expiration: Foundation.TimeInterval) async throws -> ClientRuntime.URL? {
```

### Proposed Solution

Move the method to `S3Client` and write a section in the documentation about it.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Few things
**- what other SDKs are doing**  we should be consistent
- no difference between in underlying impl except Http call
- it will be a breaking change

**Comment by sebsto** [comment]
**Java, JavaScript**
The S3Signer class is a wrapper around GetObject and PutObject requests 
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3-presign.html#generate-presignedurl
https://aws.amazon.com/blogs/developer/generate-presigned-url-modular-aws-sdk-javascript/

**Python**  It is an fun on the S3 client object.

You can see code sample for multiple AWS SDK here 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_Scenario_PresignedUrl_section.html

**Comment by sichanyoo** [comment]
PR: https://github.com/awslabs/aws-sdk-swift/pull/1198

**Comment by sebsto** [comment]
Fixed in https://github.com/awslabs/aws-sdk-swift/releases/tag/0.31.0

Thank you !
