### ISSUE TITLE
rafactor: extract EndpointResolverMiddleware from Service clients to AWSClientRuntime

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#840]
### Describe the feature

Currently EndpointResolverMiddleware is part of service client which as good amount of duplication. This was intentional due to EndpointResolver and EndpointParams being service specific. I couldn't able to generalize the middleware due to limitations with Swift type system.

### Use Case

Reduce code

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Completed with https://github.com/awslabs/aws-sdk-swift/pull/1537.
