### ISSUE TITLE
Configure awslabs/aws-sdk-swift and awslabs/smithy-swift to use dev branch strategy

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#847]
In order to better facilitate daily releases, we want to move towards develop branch strategy. This strategy involves using the `dev` branch as the branch PRs are merged to. The `main` branch will only be updated during the a release. 

- [ ] Create a `dev` branch
- [ ] Set `dev` branch as default branch
- [ ] Update runbooks and CI accordingly

**Comment by smivij** [comment]
Link with the release automation workflow issue

**Comment by smivij** [comment]
This is done
