### ISSUE TITLE
Create strategy to bump Swift versions

### ISSUE THREAD

**Issue by ganeshnj** [awslabs/aws-sdk-swift#861]
### Describe the feature

Currently we don't have a strategy to decide which version the Swift SDK must target. Moving forward, we would like to use the latest and greatest but at the same time supporting majority of our customers. Hence we need some formal process to decide what Swift version makes most sense for the SDK.

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2166
