### ISSUE TITLE
OSMetadata doesn't differentiate between Simulator versus Real device

### ISSUE THREAD

**Issue by phantumcode** [awslabs/aws-sdk-swift#874]
### Describe the feature

[OSMetadata](https://github.com/awslabs/aws-sdk-swift/blob/6d7c4a1ce4038149fc13b77aa648d33e9048a9c8/Sources/Core/AWSClientRuntime/Http/OSMetadata.swift) used to calculate the [AWSUserAgentMetadata](https://github.com/awslabs/aws-sdk-swift/blob/6d7c4a1ce4038149fc13b77aa648d33e9048a9c8/Sources/Core/AWSClientRuntime/Http/OSMetadata.swift) does not differentiate when the AWS Swift SDK is being executed in an iOS/MacOS Simulator versus a real device.

As a result, the AWS UserAgent header on request has inaccurate OS information and does include detail that the environment is on a simulator.

i.e.
```
User-Agent: aws-sdk-swift/1.0 api/cognito-identity-provider/1.0 os/iOS/16.2.0 lang/swift/5.7 lib/amplify-ios/2.2.0
```

### Use Case

Amplify Swift library would like the User Agent to differentiate when running on iOS simulator and macOS simulator to differentiate between developer debug/simulation versus when running in real device for more accurate and improved granularity for calculating Amplify Swift library and Swift SDK usage metrics.

### Proposed Solution

**Option 1**: Update [PlatformOperatingSystem](https://github.com/awslabs/smithy-swift/blob/1fbd5f7bebd024e29c577240a960cd011ce71ac4/Sources/ClientRuntime/Util/PlatformOperatingSystem.swift) in smithy-swift repo with new enum cases of iOSSimulator, watchOSSimulator, tvOS Simulator, and macOSSImulator

```swift
public enum PlatformOperatingSystem: String {
    case windows
    case linux
    case iOS
    case macOS
    case watchOS
    case tvOS
    case iOSSimulator
    case macOSSimulator
    case watchOSSimulator
    case tvOSSimulator
    case unknown
}

public var currentOS: PlatformOperatingSystem {
    #if os(Linux)
    return .linux
    #elseif os(macOS)
         #if targetEnvironment(simulator)
         return .macOSSimulator
         #else
         return .macOS
         #endif
    #elseif os(iOS)
          #if targetEnvironment(simulator)
          return .iOSSimulator
          #else
          return .iOS
          #endif
    #elseif os(watchOS)
         #if targetEnvironment(simulator)
         return .watchOSSimulator
         #else
         return .watchOS
         #endif
    #elseif os(Windows)
    return .windows
    #elseif os(tvOS)
          #if targetEnvironment(simulator)
          return .tvOSSimulator
          #else
          return .tvOS
          #endif
    #else
     #error("Cannot use a an operating system we do not support")
    #endif
}
```

**Option 2:**  Update [OSMetadata](https://github.com/awslabs/aws-sdk-swift/blob/6d7c4a1ce4038149fc13b77aa648d33e9048a9c8/Sources/Core/AWSClientRuntime/Http/OSMetadata.swift#L19) description field

```swift
extension OSMetadata: CustomStringConvertible {
    public var description: String {
        guard let version = version else {
           #if targetEnvironment(simulator)
           return "os/\(family)/Simulator"
           #else
           return "os/\(family)"
           #endif 
        }
        let versionSanitized = version.sanitizeForUserAgentToken()
        guard !versionSanitized.isEmpty else {
           #if targetEnvironment(simulator)
           return return "os/\(family)/Simulator"
           #else
           return "os/\(family)"
           #endif 
        }
        
         #if targetEnvironment(simulator)
         return "os/\(family)/\(versionSanitized)/Simulator"
         #else
         return "os/\(family)/\(versionSanitized)"
         #endif   
    }
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
@phantumcode 

Whether the request was sent from within a simulator or not will now be included in the user agent header in the following format:
```
User-Agent: aws-sdk-swift/1.0 ua/2.0 api/s3#1.0 os/ios#17.4.0 md/simulator lang/swift#5.10 cfg/retry-mode#legacy
```
Notice the addition of `md/simulator` metadata segment after the OS metadata.
This change will be live in the next release of the AWS Swift SDK.
Thank you for the constructive idea and the ticket!
