### ISSUE TITLE
SDK errors when run on pre-release Swift versions

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#884]
### Describe the bug

The SDK currently errors when it is compiled on an "unsupported" swift version. 
This error is explicitly raised if the compiler's swift version is greater than a predefined version here https://github.com/awslabs/smithy-swift/blob/main/Sources/ClientRuntime/Util/SwiftVersion.swift#L9

### Expected Behavior

Current and past SDK releases should compile successfully on future swift versions (unless the swift version contains a breaking change).

### Compiler and Version used

Swift 5.8

**Comment by ganeshnj** [comment]
0.6.1 release is out with fix 

https://github.com/awslabs/aws-sdk-swift/releases/tag/0.6.1
