### ISSUE TITLE
Add tests for S3 errors

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#886]
### Describe the feature

Add a test to verify the S3 error customizations. 
Specifically we want a test that verifies an error with status code 404 and an empty response body decodes successfully.

It might make sense to wrap this functionality in a "S3Error" type and add a single test for that. Otherwise, we can add a test for all S3 error types or hand pick a couple.

Related Issue: #761 
Related PR: #787 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
It must be done after #307

**Comment by jbelkins** [comment]
We have a test for the S3 "empty body 404 error" case already.  Closing.
