### ISSUE TITLE
Add tests for Route53 trimming hosted zone

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#888]
### Describe the feature

Add tests to verify the behavior of trimming the hosted zone id https://github.com/awslabs/aws-sdk-swift/issues/213

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
We must first do #307

**Comment by sichanyoo** [comment]
Tracked in https://github.com/orgs/awslabs/projects/61/views/3?pane=issue&itemId=60471658#:~:text=customization%20is%20incomplete-,%231446,-Edit
