### ISSUE TITLE
Error compiling a Swift Lambda if contains the aws-sdk-swift as dependency

### ISSUE THREAD

**Issue by fitomad** [awslabs/aws-sdk-swift#890]
### Describe the bug

An error during the swift package archive command execution related to an aws-sdk-swift header file.

This issue is related with [issue 288](https://github.com/swift-server/swift-aws-lambda-runtime/issues/288) opened at the [swift-aws-lambda-runtime](https://github.com/swift-server/swift-aws-lambda-runtime/issues/288) project

### Expected Behavior

Using the `archive` command plugin included in the [swift-aws-lambda-runtime](https://github.com/swift-server/swift-aws-lambda-runtime) project **build the package using an Amazon Linux 2 docker image** and then generates a ZIP file ready to deploy with the AWS Lambda console

### Current Behavior

The build process throws an error related to an umbrella header file `S2N`

```zsh
error: 'aws-crt-swift': target 'S2N' has invalid header layout: umbrella header found at '/workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/S2N.h', but directories exist next to it: /workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/unstable; consider removing them
```

Below this line you will find the whole command output

```zsh
-------------------------------------------------------------------------
configuration
-------------------------------------------------------------------------
{
  outputDirectory: /Users/adolfo/Desktop
  products: ["Favorites"]
  buildConfiguration: release
  baseDockerImage: swift:amazonlinux2
}
-------------------------------------------------------------------------
building "awslambdabackend" in docker
-------------------------------------------------------------------------
updating "swift:amazonlinux2" docker image
  amazonlinux2: Pulling from library/swift
  Digest: sha256:2d18edce3138194b7783aa75afb2d43712c536697cb7326a9fa2af43c91873df
  Status: Image is up to date for swift:amazonlinux2
  docker.io/library/swift:amazonlinux2
/usr/local/bin/docker run --rm -v /Users/adolfo/Documents/Globant/AWS Lambda Tech Talk/Lambdas/AWSLambdaBackend:/workspace -w /workspace swift:amazonlinux2 bash -cl swift build -c release --show-bin-path
  /workspace/.build/aarch64-unknown-linux-gnu/release
building "Favorites"
/usr/local/bin/docker run --rm -v /Users/adolfo/Documents/Globant/AWS Lambda Tech Talk/Lambdas/AWSLambdaBackend:/workspace -w /workspace swift:amazonlinux2 bash -cl swift build -c release --product Favorites --static-swift-stdlib
  error: 'aws-crt-swift': target 'S2N' has invalid header layout: umbrella header found at '/workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/S2N.h', but directories exist next to it: /workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/unstable; consider removing them
  [0/1] Planning build
error: ExitCode(rawValue: 1)
error: /usr/local/bin/docker run --rm -v /Users/adolfo/Documents/Globant/AWS Lambda Tech Talk/Lambdas/AWSLambdaBackend:/workspace -w /workspace swift:amazonlinux2 bash -cl swift build -c release --product Favorites --static-swift-stdlib failed with code 1
```

### Reproduction Steps

1. Create a Swift package with the command `swift package init --type executable`
2. Add the dependencies showed in the code snippet below this list
3. Create a Swift Lambda that inherits from LambdaHandler
4. Open a Terminal and go to the package folder
5. Run swift build command. Results OK 👍
6. Run `swift package --disable-sandbox archive --output-path /Users/adolfo/Desktop --verbose 2`

`Package.swift` file used in this package:

```swift
// swift-tools-version: 5.7

import PackageDescription

let package = Package(
    name: "AWSLambdaTracking",
    platforms: [
        .macOS(.v12)
    ],
    dependencies: [
        .package(url: "https://github.com/swift-server/swift-aws-lambda-runtime.git", from: "1.0.0-alpha.1"),
        .package(url: "https://github.com/swift-server/swift-aws-lambda-events.git", branch: "main"),
        .package(url: "https://github.com/awslabs/aws-sdk-swift.git", from: "0.10.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .executableTarget(
            name: "AWSLambdaTracking",
            dependencies: [
                .product(name: "AWSLambdaRuntime", package: "swift-aws-lambda-runtime"),
                .product(name: "AWSLambdaEvents", package: "swift-aws-lambda-events"),
                .product(name: "AWSDynamoDB", package: "aws-sdk-swift")
            ]),
        .testTarget(
            name: "AWSLambdaTrackingTests",
            dependencies: ["AWSLambdaTracking"]),
    ]
)
```

### Possible Solution

Check folder hierarchy mentioned in the error details

```zsh
error: 'aws-crt-swift': target 'S2N' has invalid header layout: umbrella header found at '/workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/S2N.h', but directories exist next to it: /workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/unstable; consider removing them
  
```

### Additional Information/Context

The *archiving* process has been tested with the current Swift Amazon Linux 2 docker image and with Swift 5.6 and Swift 5.7.2 docker image versions

### AWS SWIFT SDK version used

0.10.0

### Compiler and Version used

Xcode 14, Swift 5.7.2, Swift Tools version 5.7

### Operating System and version

macOS Ventura 13.2.1

**Comment by ugocottin** [comment]
Hi,
Does your file system is case-insensitive (by default on macOS) ?
If yes, please look a this issue: https://github.com/awslabs/aws-crt-swift/issues/163

**Comment by fitomad** [comment]
Hi @ugocottin!

Yes, my APFS installation is case-insensitive. I'll keep an eye over https://github.com/awslabs/aws-crt-swift/issues/163 issue to wait for a solution.

Thanks

**Comment by ugocottin** [comment]
I you can, create a APFS case sensitive volume and move you project to it

**Comment by fitomad** [comment]
Until a fix will be released it seems the only solution right now 😀

**Comment by ganeshnj** [comment]
It is not an issue in the Swift SDK directly, but in CRT layer.

Closing in favor of https://github.com/awslabs/aws-crt-swift/issues/163
