### ISSUE TITLE
Finalize minimum platform versions

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#893]
### Describe the feature

At the time of creating this issue, the Package.swift defines  a minimum version of mac os 10.15 and iOS 13. 
The SDK should not be using any APIs that require these minimum versions and therefore the SDK should rely on the default platform minimums that are determined by the swift version at build time. 

- [ ] Investigate why these minimum versions are specified
- [ ] Either remove these minimum versions OR document why they are needed

(we must also update the Package.swift files in smithy-swift and aws-crt-swift as well)

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Supported platforms, as set, match those supported by amplify-swift.

Minimum platform updates, going forward, will be announced & potentially coordinated with major customers & stakeholders.

Closing since platforms will not be revisited before GA.
