### ISSUE TITLE
Building all tests fails on linux platforms

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#894]
### Describe the bug

Building all tests results in an error on linux platforms.
If you reduce the amount of tests to ~200 of a random subset, then both building tests completes successfully.

Running either `swift build --build-tests` or `swift test` will fail and results in the following error message: 
`error: link command failed with exit code 254`. 
I've tested and reproduced this behavior on  the following platforms: 
- Amazon Linux 2 - Swift 5.7.3
- Amazon Linux 2 - Swift 5.5.3
- Ubuntu Focal - Swift 5.5.3

### Expected Behavior

N/A

### Current Behavior

N/A

### Reproduction Steps

In a docker container using one of the following images
- [amazon linux 2 - swift 5.7.3](https://hub.docker.com/layers/library/swift/5.7.3-amazonlinux2/images/sha256-188d622c0f8d7f5e8c5e284856685b2fdc1667f11a08fb916e9fe20b050e87d0?context=explore)
- [amazon linux 2 - swift 5.5.3](https://hub.docker.com/layers/library/swift/5.5.3-amazonlinux2/images/sha256-48f6683553d52aa5b36e948c69546624a4324e80dd7d09b6911a4e4087865f60?context=explore)
- [ubuntu focal - swift 5.5.3](https://hub.docker.com/layers/library/swift/5.5.3-focal/images/sha256-71bca37d2a50070a0c85439d5ab82e16cb5ce77d377dbc2baea90d75009be5dc?context=explore)

Clone the the `aws-sdk-swift` repo

Run either of the following commands
- `swift build --build-tests` 
- `swift test`

### Possible Solution

This might be a swift bug, in which case we should open an issue with Swift. 

Additionally, if we are blocked on this then we can implement a work around that executes the tests in batches on CI. This will allow us to execute every test without hitting this limitation.

### AWS SWIFT SDK version used

N/A

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by smivij** [comment]
We have workaround to split the tests into smaller batches, lowering priority

**Comment by sichanyoo** [comment]
Closing this ticket as workaround is being used with no issues.
