### ISSUE TITLE
Create Windows images for release automation

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#900]
### Describe the feature

We want to be able to build and test on Windows platforms. 
We need to create docker images for Windows and supported swift versions. 
Windows images can only be created from Windows machines. 

Ideally the work here will also result in a process/automation that will enable team members to easily create additional Windows images in the future.

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
Not a priority for GA as of now.

We don't have customers asking to run Swift SDK on Windows. If we get enough requests, we will re-prioritize it.

**Comment by sichanyoo** [comment]
We currently have no plans to support Windows.
