### ISSUE TITLE
Review, estimate, and approve the Smithy RPCv2 CBOR SEP

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#904]
[Smithy RPCv2 CBOR support](https://sim.amazon.com/issues/SDK-117437) (https://sim.amazon.com/issues/SDK-117437)

This SEP introduces a new wire protocol to the AWS SDKs, Smithy RPC v2. Smithy RPC v2 currently only supports the CBOR data serialization format, but allows for expansion to other formats later. This SEP also adds a new “protocols” C2J metadata field to specify a list of service supported wire protocols and defines the rules by which a service’s wire protocol is resolved by a client. Our goal is to implement Smithy RPCv2 into n SDKs in 2023 with support from the Code Foundations team.
*Working Backwards Quarterly Milestones:*

    * [Q1/2023]- Create the SEP
    * [Q2/2023]- Review and Approve the SEP
    * [Q3/2023]- Implement Smithy RPCv2 CBOR support in n languages. (Builder Tools / Code Foundations Dev support to be determined)

*Q2 Asks To Achieve Q2 Milestones:*

    * [4/28] *All SDKs* - Review, estimate, and approve the Smithy RPCv2 CBOR SEP.

**Comment by sichanyoo** [comment]
Implementation tracked in internal ticket 729
