### ISSUE TITLE
Automated Release System Workflow - Preview Builds

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#906]

**Comment by ganeshnj** [comment]
@smivij could you add some description in the issue?

**Comment by smivij** [comment]
Reference tasks on [#Automated release system do](https://github.com/awslabs/aws-sdk-swift/issues/243) for any dependent task

**Comment by smivij** [comment]
bbzlA30FcPiH/Client-namenamespace-service-team-approvals - We need to send the same of the built client back to release automation system so service teams can review and confirm.

**Comment by dayaffe** [comment]
FOOB has been approved for delivery of 80 mac2-m2.metal hosts on 5/3 (V1349194815)

**Comment by dayaffe** [comment]
Capacity delivery has been delayed by EC2 Mac team until ~mid june

**Comment by dayaffe** [comment]
See 104107652 -- SDK is now fully onboarded to automated release system.
