### ISSUE TITLE
Endpoints 2.0 refactoring - Assessment

### ISSUE THREAD

**Issue by smivij** [awslabs/aws-sdk-swift#907]
[Endpoints 2.0 Refactor Risk Assessment](https://quip-amazon.com/QTykAjk3dUZh/Endpoints-20-Refactor-Risk-Assessment) for [Smithy-based ](https://sim.amazon.com/issues/SMITHY-1355) SDKs (JS v3, Rust, Kotlin, Swift  **Endpoints 2.0 for Go not implemented yet)

*Goal Description:* The [Endpoints 2.0 implementation](https://github.com/awslabs/smithy/pull/1356) (https://github.com/awslabs/smithy/pull/1356) requires significant refactoring in Smithy. This refactoring will impact Smithy-based SDKs and require modification to the endpoints implementation in JS v3 and Go v2 as well as the non-GA SDKs including Rust, Swift, and Kotlin. The Smithy team is actively working on a proposed refactoring in Smithy and possible breaking changes will be require changes to the impacted SDKs.

**Comment by ganeshnj** [comment]
This is marked as Q2 but we don't have the finalized spec yet.

Marking as blocked for now.

**Comment by jbelkins** [comment]
Moving to Blocked while awaiting a description of related Smithy changes.

**Comment by smivij** [comment]
Closing as the implementation is tracked with #1037
