### ISSUE TITLE
Cognito API AssociateSoftwareToken not working

### ISSUE THREAD

**Issue by harsh62** [awslabs/aws-sdk-swift#913]
### Describe the bug

While calling Cognito API `associateSoftwareToken`, we get an exception `Valid credentials could not be sourced by the IMDS provider`.

### Expected Behavior

The Cognito API should return a valid result.

### Current Behavior

Throws an exception
```
crtError(AwsCommonRuntimeKit.AWSError(errorCode: 6153, errorMessage: Optional("Valid credentials could not be sourced by the IMDS provider")))
    ▿ unknown: (2 elements)
      - .0: "Unable to execute auth task"
      ▿ .1: Optional(AwsCommonRuntimeKit.CRTError.crtError(AwsCommonRuntimeKit.AWSError(errorCode: 6153, errorMessage: Optional("Valid credentials could not be sourced by the IMDS provider"))))
        ▿ some: AwsCommonRuntimeKit.CRTError.crtError
          ▿ crtError: AwsCommonRuntimeKit.AWSError
            - errorCode: 6153
            ▿ errorMessage: Optional("Valid credentials could not be sourced by the IMDS provider")
              - some: "Valid credentials could not be sourced by the IMDS provider"

```

### Reproduction Steps

Call the API with an `accessToken`
```
        let input = AssociateSoftwareTokenInput(accessToken: accessToken)
        let result = try await client.associateSoftwareToken(input: input)
```

### Additional Information/Context

Similar issue is also present in the Kotlin SDK.
https://github.com/awslabs/aws-sdk-kotlin/issues/874

### AWS SWIFT SDK version used

0.6.1

### Compiler and Version used

Xcode 14.2

### Operating System and version

iOS 16.2

**Comment by lucix-aws** [comment]
This operation is missing the `optionalAuth` trait in the model.

I've fixed it in Kotlin by [backfilling the trait](https://github.com/awslabs/aws-sdk-kotlin/pull/875) (we have an existing customization for this, but this method was missing).

**Comment by harsh62** [comment]
Please make sure the fix is applied to other API's too. Especially [VerifySoftwareToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_VerifySoftwareToken.html) and [SetUserMFAPreference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserMFAPreference.html).. 

Reference: [How Cognito works with IAM](https://docs.aws.amazon.com/cognito/latest/developerguide/security_iam_service-with-iam.html)

**Comment by epau** [comment]
The swift sdk may not support this feature currently. Will need to investigate
