### ISSUE TITLE
Test compatibility with AL2023

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#918]
### Describe the feature

Now that AL2023 is GA, let's verify the sdk builds and runs as expected on AL2023. 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
AWS Swift SDK is compatible with AL2; build image for AL2 is used in the automatic build system. Closing ticket now.
