### ISSUE TITLE
Add support for tvOS and watchOS

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#919]
### Describe the feature

Currently tvOS and watchOS fail because the package files (here and in smithy-swift) don't specify min versions. 
Update the package manifest to match the min version defined in crt. 
Additionally, verify all services build successfully and all tests pass

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
Not a requirement for GA, but might be low-hanging fruit and with enough requests we will reconsider priority.

**Comment by smivij** [comment]
Closing as this is done already
