### ISSUE TITLE
Service errors masked by JSON decoding error

### ISSUE THREAD

**Issue by jcjimenez** [awslabs/aws-sdk-swift#927]
### Describe the bug

Service bad request responses (400) resulting from bad client input get masked by a `ClientRuntime.SdkError<T>` error.

### Expected Behavior

The error reaching the caller should be one representing the invalid request, such as:

```swift
CreateLogStreamOutputError.invalidParameterException(InvalidParameterException)
```

### Current Behavior

The caller, instead, gets something like:

```swift
ClientRuntime.SdkError<AWSCloudWatchLogs.CreateLogStreamOutputError>.client
```

<img width="1072" alt="Screenshot 2023-03-22 at 10 10 45 AM" src="https://user-images.githubusercontent.com/1117904/226955438-7b1c378e-e293-4e1f-a39f-5790a2826298.png">

### Reproduction Steps

Create a simple SPM executable that uses the AWS SDK and makes a call to any API with invalid input, such as missing values. For example, sending the `CloudWatchLogsClient` a `createLogStream` with `nil` values for `logGroupName` and `logStreamName` will result in an invalid request:

```
import AWSCloudWatchLogs

@main
public struct CompoundError {
    public static func main() async throws {
        let configuration = try await CloudWatchLogsClient.CloudWatchLogsClientConfiguration()
        configuration.clientLogMode = .response
        let client = CloudWatchLogsClient(config: configuration)
        do {
            let response = try await client.createLogStream(input: .init(
                logGroupName: nil,
                logStreamName: nil
            ))
            dump(response)
        } catch {
            dump(error)
        }
    }
}
```

### Additional Information/Context

It appears to be because the stream associated to `ClientRuntime.HttpResponse.body` becomes invalid after it is read the first time in `RESTJsonError.init(httpResponse: HttpResponse)`

<img width="1072" alt="Screenshot 2023-03-22 at 10 24 09 AM" src="https://user-images.githubusercontent.com/1117904/226956269-7cba92da-9966-4cd3-bdf3-a6455c33f38a.png">

`ClientRuntime.HttpResponse.body` is then attempted to be read agin from other domain-specific errors (e.g. `InvalidParameterException.init(httpResponse: ClientRuntime.HttpResponse, decoder:
ClientRuntime.ResponseDecoder? = nil, message: Swift.String? =
nil, requestID: Swift.String? = nil)` but by then, the stream is corrupted:

<img width="1072" alt="Screenshot 2023-03-22 at 10 24 56 AM" src="https://user-images.githubusercontent.com/1117904/226956772-6673a41b-823d-4ebd-a034-3d1c54bf4733.png">

### AWS SWIFT SDK version used

0.12.0

### Compiler and Version used

Version 14.1 (14B47b)

### Operating System and version

13.2.1 (22D68)

**Comment by jcjimenez** [comment]
I just learned about this exact same issue (I think) which was happened to be filed by a colleague of mine a little earlier: https://github.com/awslabs/aws-sdk-swift/issues/926

**Comment by epau** [comment]
Closing in favor of https://github.com/awslabs/aws-sdk-swift/issues/865
