### ISSUE TITLE
Configure ALPN based on the values provided by the service's protocol

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#948]
### Describe the feature

AWS protocols define properties (`http` and `eventStreamHttp`) that contain the priority ordered list of supported HTTP protocol versions,
The SDK must configure the http client of the service to use the values defined by the service's protocol.

Consult with smithy folks to understand if/how this should be exposed via SRA. Currently a http client just defines a single function `send(request: HTTPRequest)`. How does configuring the ALPN list and other low-level connection settings fit into this? (such as configuring ALPN and minimum TLS version etc)

For example, below are the rules for the [AWS restJson1 protocol](https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html):
> Each entry in http and eventStreamHttp SHOULD be a valid [Application-Layer Protocol Negotiation (ALPN) Protocol ID](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids) (for example, http/1.1, h2, etc). Clients SHOULD pick the first protocol in the list they understand when connecting to a service. A client SHOULD assume that a service supports http/1.1 when no http or eventStreamHttp values are provided.

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
Related: https://github.com/awslabs/aws-sdk-swift/issues/702

**Comment by AndrewFossAWS** [comment]
The aws-swift-sdk uses Apple's `URLSession` for ios platforms and [CRTEngline](https://github.com/awslabs/aws-c-http/tree/98ec73ad0c18b78ba08d40b4e60d97abf794f24d) for linux platform. Hence the supported protocol versions (and their priorities) are dictated by these clients, and not by Smithy protocol traits.

For `URLSession`, it supports HTTP/1.1, HTTP/2, and HTTP/3 protocols.
For `CRTEngine`, it supports HTTP/1.1 and HTTP/2 only.

The only thing we can add/include is to validate at least one of the protocols specified in the Smithy protocol trait is also supported by the above http clients.

**Comment by jbelkins** [comment]
Clients are negotiating HTTP version with the server directly, and should throw an appropriate error when an agreement can't be made.

**Comment by sichanyoo** [comment]
Closing ticket as work for this seems to be voided.
