### ISSUE TITLE
Clean up Region Resolver/Provider APIs

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#954]
### Describe the feature

The APIs to resolve/provide a region are inconsistent with other similar constructs such as CredentialsProvider. We must clean up this API before going to GA to make it consistent with others. 

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
- Look at SEPs to verify structure and API design
- Make API consistent with other SDKs

**Comment by sichanyoo** [comment]
There does not exist any SEP or SRA section outlining the region resolver API as of 1/9/2024. There's nothing to verify against other than other SDKs. Checked Kotlin and Rust SDKs and there does not exist a consistency among region resolving APIs.

However, SRA does outline credentials provider (identity resolver) API, which uses method name `getIdentity`. Following this, region provider / resolver API will be changed from `resolveRegion` to `getRegion` for consistency.

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.34.0
