### ISSUE TITLE
Cannot build on linux via docker from mac, due to S2N

### ISSUE THREAD

**Issue by tadelv** [awslabs/aws-sdk-swift#961]
### Describe the bug

When trying to build aws-sdk-swift on Linux (docker Amazon Linux 2) from a Mac, an unexpected error occurs when trying to build S2N from aws-crt-swift.

```
error: 'aws-crt-swift': target 'S2N' has invalid header layout: umbrella header found at '/workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/S2N.h', but directories exist next to it: /workspace/.build/checkouts/aws-crt-swift/aws-common-runtime/s2n/api/unstable; consider removing them
error: ExitCode(rawValue: 1)
```

I'm just adding this report in order to track when the aws-crt-swift changes will be merged into the sdk.

### Expected Behavior

build should not fail

### Current Behavior

Error pasted above

### Reproduction Steps

Create a Swift package, add aws-sdk-swift as a dependency, build on Mac using Docker and amazonlinux2. 

Or use my repo: https://github.com/tadelv/stars-and-planets.git, switch to branch `feature/lambda` , enter `StarsAndPlanetsLambda` folder and type (in terminal) `$Scripts/build-and-package.sh`

### Possible Solution

Probably update dependencies when this is fixed/merged:

https://github.com/awslabs/aws-crt-swift/pull/179

### Additional Information/Context

It seems that this issue also happens because the default macOS volume is not case-sensitive:

https://github.com/awslabs/aws-crt-swift/issues/163#issuecomment-1444176255

Creating another Volume, that is case-sensitive and building the project there seems to work around this issue.

### AWS SWIFT SDK version used

0.14.0

### Compiler and Version used

Swift 5.7

### Operating System and version

MacOs 13, swift:amazonlinux2

**Comment by jbelkins** [comment]
This will be fixed in the next release of AWS SDK for Swift.
