### ISSUE TITLE
[ECD 2/13] Replace the XMLCoder library

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#964]
### Describe the feature

AWS SDK policy is to not include third-party runtime dependencies that are not officially part of the target language when it can be at all avoided.
> The vigilance required when including 3P software means that you should not do so unless required for the AWS software to function.

The `smithy-swift` project currently uses the third-party [XMLCoder](https://github.com/MaxDesiatov/XMLCoder) Swift package at runtime for parsing data on service protocols that use XML.  The rationale for relying on this package versus our own solution is not known, but it is suspected that it was used to quickly add XML-based protocols early in the Swift SDK's development preview stage.

While we have no complaints with this package or its maintainers, a first party and/or official Swift solution for XML parsing is sought for use in `smithy-swift` and the AWS SDK for Swift so that we can maintain better control over our runtime dependencies.

### Use Case

To comply with SDK & Tools policy on third-party software usage, and to control more closely the software that ships with the Swift SDK.

### Proposed Solution

Create a Swift XML parser based on Foundation `XMLDocument` for use with `smithy-swift` and the SDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jbelkins** [comment]
Version 0.17.1 of `XMLCoder` caused several XML-related protocol tests to break on Swift 5.5.

In https://github.com/awslabs/smithy-swift/pull/556 , `XMLCoder` was pinned to version 0.17.0.  I do not plan to file a bug with the `XMLCoder` maintainers because we plan to drop it in the future.

**Comment by sichanyoo** [comment]
Released with:
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.35.0
https://github.com/smithy-lang/smithy-swift/releases/tag/0.40.0
