### ISSUE TITLE
Script for building & pushing Catapult docker images

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#968]
### Describe the feature

An automated script for building and pushing Docker images would be beneficial.  The current, manual process is described here:
https://w.amazon.com/bin/view/AWS/DeveloperResources/AWSSDKsAndTools/SwiftSDK/RunBooks/DockerImages/

### Use Case

Will make the Docker update process easier, faster, and less error prone when Docker images require update, or when a new member is added to the team (the ECR replication process requires a new push for Docker images to get shared to a new account.)

### Proposed Solution

Write a Bash script to perform the actions laid out in the wiki page linked above.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by sichanyoo** [comment]
Moved to 2153
