### ISSUE TITLE
Create test targets & automation plan for integration / "smoke" tests

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#969]
### Describe the feature

Perform the following for integration tests:
- Create test targets as needed to host integration tests
- Determine what external resources are needed to run these tests, document them, and determine how to ensure their availability & reliability for testing
- Determine what schedule and on what platform(s) these tests should run

### Use Case

To help detect regressions as early as possible in the development cycle

### Proposed Solution

Create a plan and reach a consensus with the rest of the team.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
Similar to #814 
- create a manual trigger for these tests

**Comment by jbelkins** [comment]
`aws-sdk-swift` integration tests are now run on PRs by commenting `/test` on the PR, and are required to pass prior to merge.

Closing.
