### ISSUE TITLE
CodeArtifact's product/target name capitalization different from official product name

### ISSUE THREAD

**Issue by jcjimenez** [awslabs/aws-sdk-swift#970]
### Describe the bug

The name of the [CodeArtifact](https://github.com/awslabs/aws-sdk-swift/tree/main/Sources/Services/AWSCodeartifact) target and product under [aws-sdk-swift](https://github.com/awslabs/aws-sdk-swift) is spelled with a lower-case 'A' (Code**a**rtifact) which is different from the [official name of the AWS Service](https://docs.aws.amazon.com/codeartifact/latest/ug/welcome.html)

### Expected Behavior

Users would import as:

```
import AWSCodeArtifact
```

### Current Behavior

Users current import as:

```
import AWSCodeartifact
```

### Reproduction Steps

Not applicable

### AWS SWIFT SDK version used

0.15.0

### Compiler and Version used

Version 14.1 (14B47b)

### Operating System and version

13.2.1 (22D68)

**Comment by jbelkins** [comment]
The symbols used for AWS services and their components in the AWS SDK for Swift are based on metadata provided by the service team.  Having CodeArtifact change the metadata would break a wide-ranging array of software and services, and the extra complexity required to override & customize the name of a service in the Swift SDK is not worth the benefit of properly capitalizing the service name.

Closing this issue, we do not plan to pursue this change.
