### ISSUE TITLE
CPU pegs to 100% while event streaming

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#974]
### Describe the bug

One CPU core pegs to 100% utilization while streaming events, even if nothing is being sent at the moment.

### Expected Behavior

CPU utilization should remain low when idle while streaming.

### Current Behavior

One CPU core pegs to 100% until streaming concludes.

### Reproduction Steps

Run the `AWSKinesis` integration tests in the `aws-sdk-swift` project.
Observe CPU once the `subscribeToShard` streaming operation connects.

### AWS SWIFT SDK version used

Latest / main branch

### Compiler and Version used

Xcode 13.3

### Operating System and version

macOS 13.3.1

**Comment by epau** [comment]
Determine if the cause of the CPU spike is in Swift or C (crt)
