### ISSUE TITLE
Create test targets & automation plan for generated AWS service tests

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#977]
### Describe the feature

Perform the following for per-service, generated tests:
- Determine what schedule and on what platform(s) these tests should run

### Use Case

To help detect regressions as early as possible in the development cycle

### Proposed Solution

Create a plan and reach a consensus with the rest of the team.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by epau** [comment]
- Need a manual trigger for these on PR (perhaps via a comment)
- Do not want these run on every commit as they take ~2 hours

**Comment by sichanyoo** [comment]
Unsure exactly what "generated AWS service tests" is referring to, but only tests we generate for each service is endpoint resolver unit tests which already get run when unit tests are run. Aside from this we have a couple S3 tests, and real end-to-end integration tests for dozen or so services. 

Closing ticket as resolved, as content seems outdated.
