### ISSUE TITLE
Initial steps given seem to be broken (or obsolete)

### ISSUE THREAD

**Issue by Eumag** [awslabs/aws-sdk-swift#979]
### Describe the issue

Hello aws-sdk-swift Team, 

I followed the steps given in doc. There are errors and unknowns. Can you correct them and put light onto it.

`./gradlew -PonlyIncludeModels=lambda.2015-03-31  :sdk-codegen:build`

This fails with: 
```
> Configure project :sdk-codegen
(scanned and found a Smithy CLI version 1.30.0. You will need to add an explicit dependency on smithy-model if publishing a JAR)
> Task :smithy-aws-swift-codegen:compileKotlin FAILED
FAILURE: Build failed with an exception.
```

This probably require `smithy-go`. Checking correspondence on an [issue1079](https://github.com/aws/aws-sdk-go-v2/issues/1079#issuecomment-790048606), suggest to run `make smithy-publish-local`. But `make smithy-generate` and `make generate` fails - in fact there is no makefile target for these two. 

There seems to be a minimum requirement of Java. And Kotlin (why kotlin for swift!) is desirable from code-building perspective. I am on Macbook and building for iOS though - where is the distinction or configuration explained!? 

Faced following error after gradle build:
```
> Task :smithy-swift:buildSrc:compileKotlin
Compilation with Kotlin compile daemon was not successful
java.rmi.ServerError: Error occurred in server thread; nested exception is: 
        java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @58ecb515)
```

[Usage instructions](https://github.com/awslabs/aws-sdk-swift#sdk-usage-instructions) mention main.swift - it is absent! It also mentions "_As a result, you should be able to_", apparently there are no simulators/actual device populated in xcode top bar so how to build and run and what is the meaning of "_As a result_", result of doing what!? 

This document might need to be corrected for getting somebody onboarded with initial build of codebase. It might be good to mention/refer following here 
- required versions of language, frameworks, utilities
- the relation wrt [amplify-swift](https://github.com/aws-amplify/amplify-swift)
- escape hatch
- what are imp functions to check in the flow while xcode debugging after a development change in aws-sdk-swift codebase (change can be simpler as in print hello world or more complex like a feature request)
- caution and required points wrt production push
- testing and corresponding steps that can be done 
- call graph and class hierarchies

Thanks

### Links

https://github.com/awslabs/aws-sdk-swift

**Comment by jbelkins** [comment]
@Eumag Sorry for the trouble you've been having with our docs.  The steps in our README were indeed confusing, and the ones you have tripped up on don't need to be performed at all if you just want to use the SDK to access AWS services.  Installing Java, running Gradle tasks, etc. are steps that only need to be performed by developers of the SDK itself, and our docs did not make that clear.  The AWS SDK for Swift will install for you much the same way as any other Swift package, without dependencies other than the standard Swift toolchain.

I've just totally updated the README for this project with setup instructions that help you get credentials configured, tests the credentials with a simple command-line app that utilizes the SDK, then walks you through installing the AWS SDK for Swift into your own Swift package or Xcode project.  We will continue to refine our docs to help developers get started and find what they need without trouble.

Please take a look at the new instructions, try them out and let us know your feedback here.  Thanks!

**Comment by Eumag** [comment]
Thanks @jbelkins for addressing on usage part. 
Quick note: I had following in sight: [contributing](https://github.com/awslabs/aws-sdk-swift/blob/main/CONTRIBUTING.md) and [good first issue](https://github.com/awslabs/aws-sdk-swift/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). This is from developer and code review perspective.

**Comment by Eumag** [comment]
Third point in [Test step](https://github.com/awslabs/aws-sdk-swift#test-the-aws-sdk-for-swift-with-your-credentials) says to edit Sources/main.swift file. main.swift is absent. Directory structure that is populated is this: 
```
AWSCredentialTester
    Package.swift 
    README.md         
    Sources       
        AWSCredentialTester
            AWSCredentialTester.swift
    Tests
        AWSCredentialTesterTests
            AWSCredentialTesterTests.swift
```
By any chance, does the doc mean to create `main.swift` file and write the contents given on [doc](https://github.com/awslabs/aws-sdk-swift#test-the-aws-sdk-for-swift-with-your-credentials)? Trying that makes `swift run` to produce error and there is no terminal output stating `Caller's AWS user ID is <an alphanumeric string>`. `swift run` produces following messages: 
```
√ AWSCredentialTester % swift run
Fetching https://github.com/awslabs/aws-sdk-swift.git from cache
Fetched https://github.com/awslabs/aws-sdk-swift.git (39.71s)
.. ..
Working copy of https://github.com/apple/swift-collections resolved at 1.0.4
Building for debugging...
/Users/rbakshi/dev/AWSCredentialTester/Sources/AWSCredentialTester/AWSCredentialTester.swift:1:1: error: 'main' attribute cannot be used in a module that contains top-level code
@main
^
/Users/rbakshi/dev/AWSCredentialTester/Sources/main.swift:1:1: note: top-level code defined in this source file
import AWSSTS
^
/Users/rbakshi/dev/AWSCredentialTester/Sources/AWSCredentialTester/AWSCredentialTester.swift:1:1: error: 'main' attribute cannot be used in a module that contains top-level code
@main
^
/Users/rbakshi/dev/AWSCredentialTester/Sources/main.swift:1:1: note: top-level code defined in this source file
import AWSSTS
^
```

Platform:
```
?1 AWSCredentialTester % swift --version
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0
√ AWSCredentialTester % uname -a
Darwin Rajeevs-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
MacOS Ventura 13.0.1 
```

Objective of raising this ticket is to be able to contribute to `aws-sdk-swift` from _developer_ perspective starting from issues that are indicated and marked for being the _good first issue_. If it is not allowed or is discouraged in a way, please let me know. It is important and would do good if there is at least one issue-resolution in aws-sdk-swift that is given a walkthrough which touches on some core aspects for somebody that is onboarding for this purpose. 

It is definitely good and awesome to adopt aws services and professional quality docs are the means to enable or disable it. [amplify libraries](https://docs.amplify.aws/lib/q/platform/ios/) has done a good job on this part. But (among other things) users pointing on a broken doc and quality, waiting for long on it to get replies, testing it, re-clarifying on original question breaks that spirit and confidence on aws service adoption.

**Comment by jbelkins** [comment]
Regarding your lack of `main.swift`, be sure to create your project with the `--type executable` flag:
```
$ mkdir AWSCredentialTester
$ cd AWSCredentialTester
$ swift package init --type executable
```
If you specified executable as your type and still did not get a `main.swift` file, please let me know what Xcode and/or Swift version you are using.

Regarding this project's lack of documentation & support relative to other AWS products, it bears repeating that **this is a Developer Preview product.** That means:
- this SDK is published for experimental use only and for the purpose of collecting early feedback from developers.
- this SDK is NOT recommended for production use in any application.
- the APIs in this SDK are subject to breaking changes with every release.
- this SDK is not yet feature complete; features that you need for your intended application may not yet exist.
- Documentation for this project is NOT complete, and what documentation we have may be in a draft state.
- AWS support available for this product may be limited.

We do not have a date or timeframe for this SDK's general availability at this time.  While we appreciate your feedback and will use it to improve our product and documentation, there are 

If you want to use a mature solution for working with AWS from a mobile device, the following AWS products are currently recommended for use in production with complete documentation and API stability:
- AWS SDK for iOS: https://github.com/aws-amplify/aws-sdk-ios
- AWS Amplify for Swift: https://github.com/aws-amplify/amplify-swift

If you are building an app for any use more than experimental, or would benefit from complete documentation & support, then please investigate these other AWS products.

**Comment by Eumag** [comment]
Thanks for looking into it.
