### ISSUE TITLE
Make data streams truly asynchronous

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#985]
### Describe the bug

The three types of streams in `smithy-swift` that are used for event and data streaming currently share an implementation of `readAsync(upToCount:)` that is not truly asynchronous; instead it polls its internal storage continuously to see if it has data and then returns it to its reader.

This caused 100% CPU usage on one core while streaming, since the polling loop ran continuously.  It was documented in #974 and was then partially addressed in https://github.com/awslabs/smithy-swift/pull/552 by reducing the rate of polling with a small (1ms) asynchronous wait.

However, the problem is not completely addressed because the stream still polls for new data and CPU is wasted, even if at a lower rate than before.  This will become an issue when streaming on low-energy devices and/or in situations where the stream stays open for extended periods.  Polling also introduces a small latency where data has arrived but is not being handled until the next poll takes place.

To solve this issue, the data streams should be updated to be fully asynchronous; meaning that they do not resume a suspended read until new data is delivered to them.

### Expected Behavior

While streaming and the stream is open but idle, essentially zero CPU should be consumed and the streaming client should not be executing.

### Current Behavior

While streaming and the stream is open but idle, streams poll themselves for new data at ~1ms intervals and CPU is consumed at a rate of ~9% of one CPU core.

### Reproduction Steps

Run Kinesis integration test under Instruments
Observe test progress vs. CPU consumption

### AWS SWIFT SDK version used

Latest / main branch

### Compiler and Version used

Xcode 14.3

### Operating System and version

macOS 13.3.1

**Comment by epau** [comment]
Related, as part of this we should also fix  `BufferedStream.readToEnd`. https://github.com/awslabs/smithy-swift/blob/main/Sources/ClientRuntime/Networking/Streaming/BufferedStream.swift#LL75C17-L75C26

Currently, `readToEnd` is sync and performs a while loop that may hog the CPU. This should be async and call `readAsync` in its implementation. In-order to make `readToEnd` async, we'll need to remove equatable conformance of models https://github.com/awslabs/aws-sdk-swift/issues/898.

**Comment by jbelkins** [comment]
An asynchronous `readToEndAsync()` method had been added to the `Stream` protocol and used where possible.  More work will be required to eliminate all use of the non-async version.

**Comment by jbelkins** [comment]
#1020 & #1022 should be perfomed as follow-up to this work.

**Comment by jbelkins** [comment]
Shipped in AWS SDK for Swift 0.18.0
