### ISSUE TITLE
Please provide better instructions on how to provide credentials to iOS & iPadOS app

### ISSUE THREAD

**Issue by compassrose-ai** [awslabs/aws-sdk-swift#991]
### Describe the issue

I am creating an iPad app for my own personal use. I am simply trying to add static credentials somewhere in my iPad app and haven't been able to figure it out. I was able to use environment variables when I run the app in via Xcode, but now I need to install the app to the iPad and it crashes due to lack of credentials. A AWSStaticCredentialsProvider would be great if this could be added to the SDK.  

### Links

https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/setting-up.html

**Comment by compassrose-ai** [comment]
Figured it out if anyone else has trouble we this..note this is anti-pattern and you should NOT do on any production app.

```
        let creds = Credentials(accessKey: "*********", secret: "***********")
        let credsProvider = try! CredentialsProvider.fromStatic(creds)
        let config = try! await DynamoDBClient.DynamoDBClientConfiguration(credentialsProvider: credsProvider, region: "us-east-2")
```

**Comment by shepazon** [comment]
Improved information on this is a good idea and I will add it to my list for the developer guide.

**Comment by bryanhull** [comment]
I would be interested if any more information was provided for this still open issue.

**Comment by shepazon** [comment]
This is in work now. I have a chapter on Apple integration topics that's being added this week, and it includes as its first topic implementing Sign In With Apple using IAM roles. I'll be following that up with coverage of identity resolvers, with examples of a couple types of such. No date yet on when those will arrive but they're the very next thing I'm working on.
